### ISSUE TITLE
name 'config' is not defined on second resubmission with input: all_directions: "link" 

### ISSUE THREAD

**Issue by JanStreffing** [esm-tools/esm_tools#1009]
```
oifs:
    file_movements:
        forcing:
            all_directions: "link"
        input:
            all_directions: "link"
```
reproducibly results in:
```

::: Copying files

::: copying file category: ICMGG_INIT
- source: /work/ab0246/a270092/runtime/awicm3-v3.1.3/link_test/input/oifs/ICMGGawi3INIT
- target: /work/ab0246/a270092/runtime/awicm3-v3.1.3/link_test/run_18500501-18500630/input/oifs/ICMGGawi3INIT
Traceback (most recent call last):
  File "/home/a/a270092/.local/bin/esm_runscripts", line 33, in <module>
    sys.exit(load_entry_point('esm-tools', 'console_scripts', 'esm_runscripts')())
  File "/home/a/a270092/esm_tools/src/esm_runscripts/cli.py", line 278, in main
    Setup()
  File "/home/a/a270092/esm_tools/src/esm_runscripts/sim_objects.py", line 90, in __call__
    resubmit.maybe_resubmit(self.config)
  File "/home/a/a270092/esm_tools/src/esm_runscripts/resubmit.py", line 148, in maybe_resubmit
    nextrun = resubmit_recursively(config, jobtype=jobtype)
  File "/home/a/a270092/esm_tools/src/esm_runscripts/resubmit.py", line 189, in resubmit_recursively
    resubmit_SimulationSetup(config, cluster)
  File "/home/a/a270092/esm_tools/src/esm_runscripts/resubmit.py", line 66, in resubmit_SimulationSetup
    config["general"]["experiment_over"] = cluster_obj(kill_after_submit=False)
  File "/home/a/a270092/esm_tools/src/esm_runscripts/sim_objects.py", line 90, in __call__
    resubmit.maybe_resubmit(self.config)
  File "/home/a/a270092/esm_tools/src/esm_runscripts/resubmit.py", line 164, in maybe_resubmit
    nextrun = resubmit_recursively(
  File "/home/a/a270092/esm_tools/src/esm_runscripts/resubmit.py", line 189, in resubmit_recursively
    resubmit_SimulationSetup(config, cluster)
  File "/home/a/a270092/esm_tools/src/esm_runscripts/resubmit.py", line 66, in resubmit_SimulationSetup
    config["general"]["experiment_over"] = cluster_obj(kill_after_submit=False)
  File "/home/a/a270092/esm_tools/src/esm_runscripts/sim_objects.py", line 69, in __call__
    self.prepcompute()
  File "/home/a/a270092/esm_tools/src/esm_runscripts/sim_objects.py", line 161, in prepcompute
    self.config = prepcompute.run_job(self.config)
  File "/home/a/a270092/esm_tools/src/esm_runscripts/prepcompute.py", line 32, in run_job
    config = evaluate(config, "prepcompute", "prepcompute_recipe")
  File "/home/a/a270092/esm_tools/src/esm_runscripts/helpers.py", line 69, in evaluate
    config = esm_plugin_manager.work_through_recipe(
  File "/home/a/a270092/esm_tools/src/esm_plugin_manager/esm_plugin_manager.py", line 141, in work_through_recipe
    config = getattr(submodule, workitem)(config)
  File "/home/a/a270092/esm_tools/src/esm_runscripts/prepcompute.py", line 240, in copy_files_to_thisrun
    config = copy_files(
  File "/home/a/a270092/esm_tools/src/esm_runscripts/filelists.py", line 959, in copy_files
    file_source = resolve_symlinks(file_source)
  File "/home/a/a270092/esm_tools/src/esm_runscripts/filelists.py", line 902, in resolve_symlinks
    if config["general"]["verbose"]:
NameError: name 'config' is not defined
```
during the tidy phase of the second leg, as the work folder for the leg 3 is being made. **I'm currently making a second test if using sub yearly restarts is another required factor.** I think it might be, because we have been using the above options for AWI-ESM1 and for AWI-CM3 TCO319-DART on aleph. Only once I set the restart freq to every 2 months for TCO1279-DART did I start to see this issue.

My test is TCO95-CORE2 with the same file movements but yearly restarts. I already did the bi-monthly restarts with normal / copy file movement and that did not crash.

**Comment by JanStreffing** [comment]
Turns out the yearly restart run also crashes at the same point:
`/work/ab0246/a270092/runtime/awicm3-v3.1.3/link_test_yearly`
`/work/ab0246/a270092/runtime/awicm3-v3.1.3/link_test`

**Comment by mandresm** [comment]
Hi Jan,

I'm in the phase of testing the bug solution. I cannot test further because all the following files are gone:
```
- missing source: /work/ab0246/a270092/input/oifs-43r3/TCO95L91/ICMGGaackINIT_CORE2    
- missing target: /work/ab0995/a270152/i1009/run_20000105-20000105/input/oifs/ICMGGawi3INIT                                                                                                                                                  
                                                                                                      
- missing source: /work/ab0246/a270092/input/oifs-43r3/TCO95L91/ICMGGaackINIUA        
- missing target: /work/ab0995/a270152/i1009/run_20000105-20000105/input/oifs/ICMGGawi3INIUA

- missing source: /work/ab0246/a270092/input/oifs-43r3/TCO95L91/ICMSHaackINIT
- missing target: /work/ab0995/a270152/i1009/run_20000105-20000105/input/oifs/ICMSHawi3INIT

- missing source: /work/ab0246/a270092/input/oifs-43r3/TCO95L91/wam_grid_tables
- missing target: /work/ab0995/a270152/i1009/run_20000105-20000105/input/oifs/wam_grid_tables

- missing source: /work/ab0246/a270092/input/oifs-43r3/TCO95L91/wam_subgrid_0
- missing target: /work/ab0995/a270152/i1009/run_20000105-20000105/input/oifs/wam_subgrid_0

- missing source: /work/ab0246/a270092/input/oifs-43r3/TCO95L91/wam_subgrid_1
- missing target: /work/ab0995/a270152/i1009/run_20000105-20000105/input/oifs/wam_subgrid_1

- missing source: /work/ab0246/a270092/input/oifs-43r3/TCO95L91/wam_subgrid_2
- missing target: /work/ab0995/a270152/i1009/run_20000105-20000105/input/oifs/wam_subgrid_2

- missing source: /work/ab0246/a270092/input/oifs-43r3/TCO95L91/uwavein
- missing target: /work/ab0995/a270152/i1009/run_20000105-20000105/input/oifs/uwavein

- missing source: /work/ab0246/a270092/input/oifs-43r3/TCO95L91/specwavein
- missing target: /work/ab0995/a270152/i1009/run_20000105-20000105/input/oifs/specwavein

- missing source: /work/ab0246/a270092/input/oifs-43r3/TCO95L91/sfcwindin
- missing target: /work/ab0995/a270152/i1009/run_20000105-20000105/input/oifs/sfcwindin

- missing source: /work/ab0246/a270092/input/oifs-43r3/TCO95L91/cdwavein
- missing target: /work/ab0995/a270152/i1009/run_20000105-20000105/input/oifs/cdwavein
```

Was that intended or a mistake? It's really convenient to use TCO95 for fast testing

**Comment by pgierz** [comment]
Might be related: @JanStreffing and I nuked the work folder a few times in the process of trying to figure out what was going on.

However, the error message @mandresm is showing seems to point to missing *pool* files (or, well, input)...? 

@mandresm, I'll look at your PR now to make sure nothing is "logically" fishy. Whatever that might mean ;-)

**Comment by JanStreffing** [comment]
So i tried to solve the linking issue by putting move in all_directions. Turns out that was not my brightest idea. Because I have write permissions on the pool dir, esm_tools then promptly moved all the files from pool to my work folder...

**Comment by JanStreffing** [comment]
I'll have to recover the pool dir from another maschine..

**Comment by pgierz** [comment]
>  Because I have write permissions

Having "god mode" is sometimes a curse. I have run into that a few times on albedo, namely: "Heh? What? Why doesn't that work for user xyz? Oh...oh wait. I am root. That's why" 🤦🏻‍♂️

**Comment by JanStreffing** [comment]
Ok i recovered the pool dir. Note to self: Dont be lazy, actually decide case by case in which directions things can be moved.

**Comment by JanStreffing** [comment]
For posterity: We can't use
```
oifs:
    file_movements:
        forcing:
            all_directions: "link"
        input:
            all_directions: "link"
```
But we can use:
```
oifs
    add_file_movements:
        forcing:
            all_directions: link
        input:
            exp_to_run: copy
            init_to_exp: link
            run_to_work: link
            work_to_run: link
```
