### ISSUE TITLE
Basic CI Fails

### ISSUE THREAD

**Issue by pgierz** [esm-tools/esm_tools#1192]
Recent CI versions are failing, probably we added a dependency which isn't properly working on the test CI Ubuntu machines...

```
ash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
Standard install to user directory (likely /github/home/.local)
WARNING: The directory '/github/home/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Obtaining file:///__w/esm_tools/esm_tools
Collecting Click==8.0.4
  Downloading click-8.0.4-py3-none-any.whl (97 kB)
Collecting PyGithub==1.55
  Downloading PyGithub-1.55-py3-none-any.whl (291 kB)
Collecting colorama==0.4.5
  Downloading colorama-0.4.5-py2.py3-none-any.whl (16 kB)
Collecting coloredlogs==15.0.1
  Downloading coloredlogs-15.0.1-py2.py3-none-any.whl (46 kB)
Collecting emoji==1.7.0
  Downloading emoji-1.7.0.tar.gz (175 kB)
Collecting f90nml==1.4.2
  Downloading f90nml-1.4.2-py2.py3-none-any.whl (32 kB)
Collecting gfw-creator==0.2.2
  Downloading gfw_creator-0.2.2-py2.py3-none-any.whl (38 kB)
Collecting gitpython==3.1.41
  Downloading GitPython-3.1.41-py3-none-any.whl (196 kB)
Collecting h5netcdf>=0.8.1
  Downloading h5netcdf-1.1.0-py2.py3-none-any.whl (26 kB)
Collecting loguru==0.6.0
  Downloading loguru-0.6.0-py3-none-any.whl (58 kB)
Collecting numpy>=1.19.5
  Downloading numpy-1.24.4-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
Collecting packaging==21.3
  Downloading packaging-21.3-py3-none-any.whl (40 kB)
Collecting pandas>=1.1.5
  Downloading pandas-2.0.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.4 MB)
Collecting psutil==5.9.1
  Downloading psutil-5.9.1-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (284 kB)
Collecting pydantic==1.10.2
  Downloading pydantic-1.10.2-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (13.6 MB)
Collecting pytest==7.1.2
  Downloading pytest-7.1.2-py3-none-any.whl (297 kB)
Collecting pyyaml==6.0.1
  Downloading PyYAML-6.0.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (736 kB)
Collecting questionary==1.10.0
  Downloading questionary-1.10.0-py3-none-any.whl (31 kB)
Collecting ruamel.yaml==0.17.32
  Downloading ruamel.yaml-0.17.32-py3-none-any.whl (112 kB)
Collecting semver==2.13.0
  Downloading semver-2.13.0-py2.py3-none-any.whl (12 kB)
Collecting sqlalchemy==1.4.39
  Downloading SQLAlchemy-1.4.39-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.6 MB)
Collecting tabulate==0.8.10
  Downloading tabulate-0.8.10-py3-none-any.whl (29 kB)
Collecting tqdm==4.64.0
  Downloading tqdm-4.64.0-py2.py3-none-any.whl (78 kB)
Collecting typing_extensions==4.1.1
  Downloading typing_extensions-4.1.1-py3-none-any.whl (26 kB)
Collecting xdgenvpy==2.3.5
  Downloading xdgenvpy-2.3.5-py3-none-any.whl (13 kB)
Collecting pynacl>=1.4.0
  Downloading PyNaCl-1.5.0-cp36-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl (856 kB)
Collecting deprecated
  Downloading Deprecated-1.2.14-py2.py3-none-any.whl (9.6 kB)
Requirement already satisfied: requests>=2.14.0 in /usr/lib/python3/dist-packages (from PyGithub==1.55->esm-tools==6.35.0) (2.22.0)
Collecting pyjwt>=2.0
  Downloading PyJWT-2.8.0-py3-none-any.whl (22 kB)
Collecting humanfriendly>=9.1
  Downloading humanfriendly-10.0-py2.py3-none-any.whl (86 kB)
Collecting xarray
  Downloading xarray-2023.1.0-py3-none-any.whl (973 kB)
Collecting cdo
  Downloading cdo-1.6.0.tar.gz (31 kB)
Collecting netcdf4
  Downloading netcdf4-1.7.0.tar.gz (772 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /tmp/tmppj09mbe_ get_requires_for_build_wheel /tmp/tmpd0lk2fvb
       cwd: /tmp/pip-install-_gv6nemf/netcdf4
  Complete output (28 lines):
  -L/usr/lib/x86_64-linux-gnu -L/usr/lib/x86_64-linux-gnu/hdf5/serial -lnetcdf
  -L/usr/lib/x86_64-linux-gnu/hdf5/serial -lhdf5
  reading from setup.cfg...
  using nc-config...
  checking /usr/include...
  hdf5 headers not found in /usr/include
  checking /usr/include/hdf5/serial...
  HDF5 library version: 1.10.4 headers found in /usr/include/hdf5/serial
  using netcdf library version b'4.7.3'
  using Cython to compile netCDF4.pyx...
  netcdf lib does not have parallel functions
  Traceback (most recent call last):
    File "/tmp/tmppj09mbe_", line 280, in <module>
      main()
    File "/tmp/tmppj09mbe_", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/tmp/tmppj09mbe_", line 114, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-97jy1rom/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "/tmp/pip-build-env-97jy1rom/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-97jy1rom/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 311, in run_setup
      exec(code, locals())
    File "<string>", line 414, in <module>
    File "/usr/lib/python3.8/shutil.py", line 264, in copyfile
      with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
  FileNotFoundError: [Errno 2] No such file or directory: 'include/no_parallel_support_imports.pxi.in'
  ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 /tmp/tmppj09mbe_ get_requires_for_build_wheel /tmp/tmpd0lk2fvb Check the logs for full command output.
```

**Comment by mandresm** [comment]
Strange, the last PR was the https://github.com/esm-tools/esm_tools/pull/1146 provenance one and there the CI was working :S

**Comment by pgierz** [comment]
Yeah, I dunno either. It failed for https://github.com/esm-tools/esm_tools/pull/1191/commits/51ed068c08b49660da36daeadc5dfe23ec4aa90f, and the only thing I did was add a MOTD for provenance... Maybe it's a fluke, but we can keep the issue open anyway to record CI weirdness if it keeps happening.

**Comment by pgierz** [comment]
Hmm...seems to have gone away again: https://github.com/esm-tools/esm_tools/actions/runs/9565982591/job/26370154485?pr=1191

**Comment by mandresm** [comment]
magic!
