### ISSUE TITLE
ValueError: ("Exactly None! Couldn't find an answer for:", ['yac_inc_path'])

### ISSUE THREAD

**Issue by joakimkjellsson** [esm-tools/esm_tools#1233]
Good morning everyone

I've got a pesky bug in ESM-Tools that I can't make sense out of. The bug only happens when I try to run OpenIFS standalone (not coupled) with version 43r3-v2. 

Compiling (on `glogin`) is fine, but the error comes when I try to start the experiment: 
```bash
esm_runscripts oifs-43r3-tco95-test.yaml -e oifs-test-01 -c
...
Traceback (most recent call last):
  File "/home/shkjocke/esm/esm_tools/src/esm_parser/esm_parser.py", line 1921, in recursive_get
    result = config_to_search[this_config]
KeyError: 'oasis3mct'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/shkjocke/esm/esm_tools/src/esm_parser/esm_parser.py", line 2028, in actually_find_variable
    var_result = recursive_get(full_config, config_elements)
  File "/home/shkjocke/esm/esm_tools/src/esm_parser/esm_parser.py", line 1928, in recursive_get
    return recursive_get(result, my_config_elements)
  File "/home/shkjocke/esm/esm_tools/src/esm_parser/esm_parser.py", line 1923, in recursive_get
    raise ValueError(
ValueError: ("Exactly None! Couldn't find an answer for:", ['yac_inc_path'])
```

So ESM-Tools fails to find the `yac_inc_path` variable. I had a look in the `oifs.env.yaml` and this variable is only needed to set the location of YAC libs on Levante and Juwels. According to `oasis3mct.env.yaml`, this variable should be set to an empty string in my case, but somehow that does not happen. 

The problem does not occur if I run FOCI-OpenIFS (coupled) using the same ESM-Tools version. The finished config file then, correctly, says: 
```bash
  yac_libs: '' # /home/shkjocke/esm/esm_tools/configs/components/oasis3mct/oasis3mct.env.yaml,line:42,col:27
  yac_inc_path: '' # /home/shkjocke/esm/esm_tools/configs/components/oasis3mct/oasis3mct.env.yaml,line:43,col:31
  yac_lib_path: '' # /home/shkjocke/esm/esm_tools/configs/components/oasis3mct/oasis3mct.env.yaml,line:44,col:31
  ```

So why does it work coupled, but not uncoupled? Is anyone else successfully running OpenIFS 43r3 standalone on other machines? Does anyone have any ideas on how to solve this? 

For now, I'll do a work around which is to make a new branch where I remove all mentions of yac from `oifs.env.yaml`. 

Best
/Joakim

**Comment by joakimkjellsson** [comment]
This issue remains in branch `geomar` and likely in `release`. For myself, I've now commented out all 4 lines where `yac` is mentioned in `oifs.env.yaml` to make it work. But I still can't work out why this problem occurs. 
Ping @seb-wahl

**Comment by mandresm** [comment]
Hi @joakimkjellsson! nice to hear from you and sorry the respond comes late.

This was a development by @JanStreffing, if I remember correctly. @JanStreffing does this problem sound familiar to you? If you don't recall something like this I'll then debug.

**Comment by JanStreffing** [comment]
This comes from here, which is Miguels cleanup of my work.

https://github.com/esm-tools/esm_tools/commit/bbfc86cf7376d914907693de5b6327160d552eaa

I think this means the oifs version you are trying to use has `with_yac: true`. Can you check if setting `with_yac: false` fixes the problem?

**Comment by mandresm** [comment]
Thanks @JanStreffing. @joakimkjellsson, if that doesn't work let me know and I'll look at it.

**Comment by joakimkjellsson** [comment]
Hi both. 

I think I've found the issue. Not sure how to fix it though. 

By default, OpenIFS standalone is compiled with OASIS and XIOS, but ESM-Tools does not consider `oifs-43r3-v2` to be a model with OASIS as a component. We say that `oifs-43r3-v2` requires OASIS, but OASIS is not a component as there is no coupling to do. 

Therefore, variables set in `oasis3mct.yaml` and `oasis3mct.env.yaml` are ignored when running OpenIFS standalone. So when ESM-Tools reads `oifs.env.yaml`, it has no idea what `oasis3mct.yac_inc_path` is since it hasn't processed `oasis3mct.yaml`. The YAC compile error does not show up when I compile FOCI or FOCI-OpenIFS. 

Possible solutions: 
* Make `with_yac`, `yac_inc_path` etc variables for oifs, not oasis3mct. Annoyingly, you'd have to do the same for all other components too (FESOM, NEMO, ECHAM, ICON). 
* Make OpenIFS standalone a "coupled" model, i.e. make a `configs/setups/oifs-agcm.yaml` as well as add it to `configs/couplings/` etc. Then when we run `esm_master get-oifs-43r3-agcm`, ESM-Tools will know to check `oifs.yaml`, `oasis3mct.yaml`and `xios.yaml`. One could even have an option `with_amip_reader` to incorporate the EC-Earth style of running OpenIFS in AMIP mode. Probably the proper solution, but it would take some time...

What do you guys think?

**Comment by mandresm** [comment]
I just pushed a commit to the `geomar` branch that should solve the problem. `requires` is for the building step. `include_models` is a way of including a component into the full setup. In the end all is a setup under the hood, so you can always include another component as part of your `config`.

In the future (when we refactor the esm_master) we will probably get rid of `requires` and unify all under `include_models` or even better `include_components`. Please, let me know if that sorted out the problem.

**Comment by mandresm** [comment]
Did this do the job @joakimkjellsson?
