### ISSUE TITLE
Installing coupled setups fails

### ISSUE THREAD

**Issue by JanStreffing** [esm-tools/esm_tools#125]
I'm trying out versions:
```
esm_archiving : unknown version!
esm_autotests : unknown version!
esm_calendar: 4.0.1
esm_database: 4.0.0
esm_environment: 3.0.0 (development install, on branch: release, describe=v3.0.0)
esm_master: 4.1.2
esm_parser: 4.1.2
esm_profile: 4.0.0
esm_rcfile: 4.0.0
esm_runscripts: 4.1.5
esm_tools: 4.1.9 (development install, on branch: release, describe=v4.1.5-40-g07f82fc)
esm_plugin_manager: 4.0.0
esm_version_checker: 4.4.0
```
I can install standalone components such as fesom-2.0-o or fesom-1.4 but all coupled setup installations, such as awicm-3.1, focioifs-2.0 or awicm-1.0 crash with:

```
~/model_codes:esm_master install-awicm-3.1
    Executing commands in this order:
         mkdir -p awicm-3.1
         cd awicm-3.1
         git clone -b 3.0 https://a270092@gitlab.dkrz.de/modular_esm/oasis3-mct.git oasis
         git clone -b esm-tools https://a270092@gitlab.dkrz.de/ec-earth/runoff-mapper.git rnfmap-ec-earth
         git clone -b master https://a270092@gitlab.dkrz.de/ec-earth/oifs-43r3.git oifs-43r3-awi
         git clone -b oifs-deck https://a270092@gitlab.dkrz.de/FESOM/fesom2.git fesom-2.0-o
         sed -i '/FESOM_COUPLED/s/OFF/ON/g' fesom-2.0-o/CMakeLists.txt
         sed -i '/OIFS_COUPLED/s/OFF/ON/g' fesom-2.0-o/CMakeLists.txt
         sed -i '/FESOM_COUPLED/s/OFF/ON/g' fesom-2.0-o/CMakeLists.txt
         sed -i '/OIFS_COUPLED/s/OFF/ON/g' fesom-2.0-o/CMakeLists.txt
         cd oasis
         mkdir -p build; cd build; cmake ..; make -j `nproc --all`; mkdir ../include; [ -f ../include/oasis_os.h ] || ln -s ../lib/psmile/include/oasis_os.h ../include/; cp ../build/lib/psmile/*mod ../include/; [ -f ../include/oasis_os.h ] || ln -s ../lib/psmile/include/oasis_os.h ../include/; ln -s ../build/lib/psmile/libpsmile.a ../lib; ln -s ../build/lib/psmile/mct/libmct.a ../lib; ln -s ../build/lib/psmile/mct/mpeu/libmpeu.a ../lib; ln -s ../build/lib/psmile/scrip/libscrip.a ../lib;

         cd ..
         mkdir -p ./lib
         cp oasis/build/lib/psmile/libpsmile.a ./lib
         cp oasis/build/lib/psmile/mct/libmct.a ./lib
         cp oasis/build/lib/psmile/mct/mpeu/libmpeu.a ./lib
         cp oasis/build/lib/psmile/scrip/libscrip.a ./lib
         cd rnfmap-ec-earth
         rm -rf bin; mkdir bin; cd src; make
         cd ..
         mkdir -p ./bin
         cp rnfmap-ec-earth/bin/rnfmap.exe ./bin
         cd oifs-43r3-awi
         export OIFS_TOPLEVEL_DIR=/home/ollie/jstreffi/model_codes/awicm-3.1/oifs-43r3-awi; cd make; ../fcm/bin/fcm make -v -j8 -f oifs.cfg
         cd ..
         mkdir -p ./bin
         cp oifs-43r3-awi/make/esm/oifs/bin/master.exe ./bin
         cd fesom-2.0-o
         mkdir -p build; cd build; cmake ..;   make install
         cd ..
         mkdir -p ./bin
         cp fesom-2.0-o/bin/fesom.x ./bin
         cd ..
Traceback (most recent call last):
  File "/home/ollie/jstreffi/.local/bin/esm_master", line 8, in <module>
    sys.exit(main())
  File "/home/ollie/jstreffi/.local/lib/python3.6/site-packages/esm_master/cli.py", line 124, in main
    user_task.execute(env)
  File "/home/ollie/jstreffi/.local/lib/python3.6/site-packages/esm_master/esm_master.py", line 847, in execute
    task.package.command_list[task.todo], task.raw_name
  File "/home/ollie/jstreffi/esm_environment/esm_environment/esm_environment.py", line 134, in add_commands
    for command in commands:
TypeError: 'NoneType' object is not iterable
```

Modules:
```
 1) nco/4.7.7(default)   3) cdo/1.9.6(default)   5) perl5/perl_libs                  7) intel.mpi/18.0.4(default)         
 2) git/2.13.1           4) R/3.4.4(default)     6) intel.compiler/18.0.5(default)   8) python3/3.6.5_intel2019(default) 
```

Am I using the wrong version of something?

**Comment by seb-wahl** [comment]
esm_environment, esm_master, esm_parser, esm_runscripts have also been upgraded for 4.2 So esm_tools on the prep_release branch will only work if you run the following:
```bash
git clone https://github.com/esm-tools/esm_tools.git
cd esm_tools
./install.sh
esm_versions upgrade esm_environment=prep_release
esm_versions upgrade esm_master=prep_release
esm_versions upgrade esm_parser=prep_release
esm_versions upgrade esm_runscripts=prep_release
```

**Comment by JanStreffing** [comment]
Ah okay, I am not on prep-release. I'm on release. I thought that was already updated. I'm guessing release esm_tools is lagging behind and I should switch to prep release.

edit: I guess you can't use esm_versions while not being on the release branch?
```
esm_versions upgrade esm_environment=prep_release
esm_environment is installed in editable mode! No upgrade performed. You may consider doing a git pull here:
```
doing the git pull leads to the old awi repo that doesn't exist anymore:
```
git pull
Username for 'https://gitlab.awi.de': jstreffi
Password for 'https://jstreffi@gitlab.awi.de': 
remote: The project you were looking for could not be found.
fatal: repository 'https://gitlab.awi.de/esm_tools/esm_environment.git/' not found

```

I think I'll just wait for the release. I didn't mean to bust into the pre-release stint. Once things have solidified again and I find a bit of time I'll see where awicm-3.1 in esm_tools stands.

**Comment by JanStreffing** [comment]
With the release out I tried again. This time I just deleted the old esm_environment and upgraded twice. I can now install coupled setups correctly.
