### ISSUE TITLE
Problems downloading awiesm-2.1 (and other models)

### ISSUE THREAD

**Issue by ackerlar** [esm-tools/esm_tools#248]
**Describe the problem you are facing**
I cannot download/install awiesm-2.1 via `esm_master install-awiesm-2.1` on mistral.

**To Reproduce**
run `esm_master install-awiesm-2.1`

**Runscrip and other relevant files**
Include the runscript and/or other relevant files that you modified (indicate file paths if necessary).

**Screenshots**
Error message:
```
Traceback (most recent call last):
  File "/pf/a/a270124/.local/bin/esm_master", line 8, in <module>
    sys.exit(main())
  File "/pf/a/a270124/.local/lib/python3.6/site-packages/esm_master/cli.py", line 76, in main
    main_flow(parsed_args, target)
  File "/pf/a/a270124/.local/lib/python3.6/site-packages/esm_master/esm_master.py", line 36, in main_flow
    complete_setup = SimulationSetup(user_config=user_config)
  File "/pf/a/a270124/.local/lib/python3.6/site-packages/esm_runscripts/sim_objects.py", line 42, in __init__
    self.config = prepare.run_job(self.config)
  File "/pf/a/a270124/.local/lib/python3.6/site-packages/esm_runscripts/prepare.py", line 5, in run_job
    helpers.evaluate(config, "prepare", "prepare_recipe")
  File "/pf/a/a270124/.local/lib/python3.6/site-packages/esm_runscripts/helpers.py", line 69, in evaluate
    framework_recipe, framework_plugins, config
  File "/pf/a/a270124/.local/lib/python3.6/site-packages/esm_plugin_manager/esm_plugin_manager.py", line 130, in work_through_recipe
    config = getattr(submodule, workitem)(config)
  File "/pf/a/a270124/.local/lib/python3.6/site-packages/esm_runscripts/prepare.py", line 91, in resolve_some_choose_blocks
    choose_blocks(config, blackdict=config._blackdict)
  File "/pf/a/a270124/.local/lib/python3.6/site-packages/esm_parser/esm_parser.py", line 2293, in choose_blocks
    add_entries_to_chapter_in_config(config, all_names, config, all_names)
  File "/pf/a/a270124/.local/lib/python3.6/site-packages/esm_parser/esm_parser.py", line 914, in add_entries_to_chapter_in_config
    setup_config,
  File "/pf/a/a270124/.local/lib/python3.6/site-packages/esm_parser/esm_parser.py", line 836, in add_entry_to_chapter
    raise TypeError("Something is wrong")
TypeError: Something is wrong
```

**System (please complete the following information):**
 - Supercomputer: mistral
 - Version [Please run `esm_versions check`]:
```
a270124@mistralpp3% esm_versions check
+---------------------+-----------+---------------------------------------------------------------+----------+-------------------------+
| package_name        | version   | file                                                          | branch   | tags                    |
|---------------------+-----------+---------------------------------------------------------------+----------+-------------------------|
| esm_analysis        | 0.4.2     | /mnt/lustre01/pf/a/a270124/esm_analysis                       |          |                         |
| esm_calendar        | 5.0.0     | /mnt/lustre01/pf/a/a270124/.local/lib/python3.6/site-packages |          |                         |
| esm_database        | 5.0.0     | /mnt/lustre01/pf/a/a270124/.local/lib/python3.6/site-packages |          |                         |
| esm_environment     | 5.0.0     | /mnt/lustre01/pf/a/a270124/.local/lib/python3.6/site-packages |          |                         |
| esm_master          | 5.0.1     | /mnt/lustre01/pf/a/a270124/.local/lib/python3.6/site-packages |          |                         |
| esm_motd            | 5.0.1     | /mnt/lustre01/pf/a/a270124/.local/lib/python3.6/site-packages |          |                         |
| esm_parser          | 5.0.2     | /mnt/lustre01/pf/a/a270124/.local/lib/python3.6/site-packages |          |                         |
| esm_plugin_manager  | 5.0.0     | /mnt/lustre01/pf/a/a270124/.local/lib/python3.6/site-packages |          |                         |
| esm_profile         | 5.0.0     | /mnt/lustre01/pf/a/a270124/.local/lib/python3.6/site-packages |          |                         |
| esm_rcfile          | 5.0.0     | /mnt/lustre01/pf/a/a270124/.local/lib/python3.6/site-packages |          |                         |
| esm_runscripts      | 5.0.4     | /mnt/lustre01/pf/a/a270124/.local/lib/python3.6/site-packages |          |                         |
| esm_tools           | 5.0.4     | /mnt/lustre01/pf/a/a270124/esm_tools                          | release  | v5.0.3-4-gc805da7-dirty |
| esm_version_checker | 5.1.1     | /mnt/lustre01/pf/a/a270124/.local/lib/python3.6/site-packages |          |                         |
+---------------------+-----------+---------------------------------------------------------------+----------+-------------------------+
```

**Additional context**
It works fine for e.g. awicm-2.0 and fesom-2.0 but does not work for awicm-1.0 either. I had no problems on Ollie but I am apparently using another esm_tools version there. I cleaned my esm_tools on mistral following the instructions from the manual and installed it again form scratch.

**Comment by mandresm** [comment]
Dear @ackerlar ,

Patch 5.0.5 of esm_runscripts should fix the issue. To try that please execute `esm_versions upgrade`.

Please, let me know if that worked out.

**Comment by ackerlar** [comment]
Thank you @mandresm ,
I got the "esm_tools directory is not clean" error [https://github.com/esm-tools/esm_version_checker/issues/16](url) during the upgrade but downloading and compiling of awiesm-2.1 works. I will close this issue.

**Comment by ackerlar** [comment]
Unfortunately, the compiling of echam does not work:
```
configure: error: in `/mnt/lustre01/pf/a/a270124/awiesm-2.1/echam-6.3.05p2-concurrent_radiation-paleodyn/yaxt':
configure: error: failed to run MPI programs
See `config.log' for more details
configure: error: ./configure failed for yaxt
Traceback (most recent call last):
  File "/pf/a/a270124/.local/bin/esm_master", line 8, in <module>
    sys.exit(main())
  File "/pf/a/a270124/.local/lib/python3.6/site-packages/esm_master/cli.py", line 76, in main
    main_flow(parsed_args, target)
  File "/pf/a/a270124/.local/lib/python3.6/site-packages/esm_master/esm_master.py", line 52, in main_flow
    user_task.execute() #env)
  File "/pf/a/a270124/.local/lib/python3.6/site-packages/esm_master/task.py", line 449, in execute
    shell=(command.startswith("./") and command.endswith(".sh")),
  File "/sw/rhel6-x64/conda/anaconda3-bleeding_edge/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['./comp-echam-6.3.05p2-concurrent_radiation-paleodyn_script.sh']' returned non-zero exit status 1.
```

**Comment by mandresm** [comment]
Hi again @ackerlar ,

I get it to compile which is kind of weird. I also compared my `comp-echam-6.3.05p2-concurrent_radiation-paleodyn_script.sh` and yours (`/mnt/lustre01/pf/a/a270124/comp-echam-6.3.05p2-concurrent_radiation-paleodyn_script.sh`) and they are identical. I've also check for differences in the `esm_tools` folder with respect to origin (`git diff`) and that gave me no clue. Can you add more information so that I can get to the point to reproduce the problem?

I would suggest that you do a clean installation again (remove `/mnt/lustre01/pf/a/a270124/awiesm-2.1`) and see if you can reproduce the error.

**Comment by ackerlar** [comment]
Dear @mandresm,
I tried to make a clean installation but still got the same error: `/pf/a/a270124/comp_awiesm-2.1.log`

esm_versions check now looks like this:
```
a270124@mistralpp2% esm_versions check
esm_analysis
├─ version: 0.4.2
├─ path: /mnt/lustre01/pf/a/a270124/esm_analysis
├─ branch: 
└─ tags: 

esm_calendar
├─ version: 5.0.0
├─ path: /mnt/lustre01/pf/a/a270124/.local/lib/python3.6/site-packages
├─ branch: 
└─ tags: 

esm_database
├─ version: 5.0.0
├─ path: /mnt/lustre01/pf/a/a270124/.local/lib/python3.6/site-packages
├─ branch: 
└─ tags: 

esm_environment
├─ version: 5.0.0
├─ path: /mnt/lustre01/pf/a/a270124/.local/lib/python3.6/site-packages
├─ branch: 
└─ tags: 

esm_master
├─ version: 5.0.1
├─ path: /mnt/lustre01/pf/a/a270124/.local/lib/python3.6/site-packages
├─ branch: 
└─ tags: 

esm_motd
├─ version: 5.0.1
├─ path: /mnt/lustre01/pf/a/a270124/.local/lib/python3.6/site-packages
├─ branch: 
└─ tags: 

esm_parser
├─ version: 5.0.2
├─ path: /mnt/lustre01/pf/a/a270124/.local/lib/python3.6/site-packages
├─ branch: 
└─ tags: 

esm_plugin_manager
├─ version: 5.0.0
├─ path: /mnt/lustre01/pf/a/a270124/.local/lib/python3.6/site-packages
├─ branch: 
└─ tags: 

esm_profile
├─ version: 5.0.0
├─ path: /mnt/lustre01/pf/a/a270124/.local/lib/python3.6/site-packages
├─ branch: 
└─ tags: 

esm_rcfile
├─ version: 5.0.0
├─ path: /mnt/lustre01/pf/a/a270124/.local/lib/python3.6/site-packages
├─ branch: 
└─ tags: 

esm_runscripts
├─ version: 5.0.5
├─ path: /mnt/lustre01/pf/a/a270124/.local/lib/python3.6/site-packages
├─ branch: 
└─ tags: 

esm_tools
├─ version: 5.0.4
├─ path: /mnt/lustre01/pf/a/a270124/esm_tools
├─ branch: release
└─ tags: v5.0.3-4-gc805da7-dirty

esm_version_checker
├─ version: 5.1.1
├─ path: /mnt/lustre01/pf/a/a270124/.local/lib/python3.6/site-packages
├─ branch: 
└─ tags:
```

**Comment by denizural** [comment]
Hi Lars, just a small comment. The output of `esm_versions check` might be different since I implemented responsive design for different terminal sizes. If your terminal width is smaller than 150 characters, the packages are printed one after another to prevent the table breaking in an ugly way.

**Comment by mandresm** [comment]
Dear @ackerlar , I'm working on it

**Comment by ackerlar** [comment]
The model compiled finally, when I used `mistral.dkrz.de `to log in instead of `mistralpp.dkrz.de`
I close the issue. Thank you again for your help!

**Comment by denizural** [comment]
You are welcome!
