### ISSUE TITLE
Crash in cleanup stage

### ISSUE THREAD

**Issue by joakimkjellsson** [esm-tools/esm_tools#282]
I'm running an AMIP experiment on blogin with OpenIFS starting 1 Jan 1979 and using monthly restarts. Everything is ok until the 13th leg, i.e. 1980-01-01 to 1980-01-31. In this leg, OpenIFS finishes and seems ok, but ESM-tools then crashes in the cleanup stage: 

```bash
clean_run_dir
-------------
Traceback (most recent call last):
  File "/home/shkjocke/.local/bin/esm_runscripts", line 11, in <module>
    load_entry_point('esm-runscripts', 'console_scripts', 'esm_runscripts')()
  File "/home/shkjocke/tmp/esm_runscripts/esm_runscripts/cli.py", line 202, in main
    Setup()
  File "/home/shkjocke/tmp/esm_runscripts/esm_runscripts/sim_objects.py", line 54, in __call__
    self.tidy(*args, **kwargs)
  File "/home/shkjocke/tmp/esm_runscripts/esm_runscripts/sim_objects.py", line 248, in tidy
    self.config = tidy.run_job(self.config)
  File "/home/shkjocke/tmp/esm_runscripts/esm_runscripts/tidy.py", line 29, in run_job
    helpers.evaluate(config, "tidy", "tidy_recipe")
  File "/home/shkjocke/tmp/esm_runscripts/esm_runscripts/helpers.py", line 49, in evaluate
    framework_recipe, framework_plugins, config
  File "/home/shkjocke/.local/lib/python3.7/site-packages/esm_plugin_manager/esm_plugin_manager.py", line 130, in work_through_recipe
    config = getattr(submodule, workitem)(config)
  File "/home/shkjocke/tmp/esm_runscripts/esm_runscripts/tidy.py", line 324, in clean_run_dir
    _clean_old_rundirs_except(config)
  File "/home/shkjocke/tmp/esm_runscripts/esm_runscripts/tidy.py", line 446, in _clean_old_rundirs_except
    rm_r(run)
  File "/home/shkjocke/tmp/esm_runscripts/esm_runscripts/tidy.py", line 713, in rm_r
    if not os.path.exists(path):
  File "/sw/tools/anaconda3/2019.10/skl/lib/python3.7/genericpath.py", line 19, in exists
    os.stat(path)
ValueError: embedded null byte
```

Does anyone what the problem might be and how to solve it? 

Many thanks
Joakim

I'm using the following versions of things: 
```bash
(base) blogin4:/scratch/usr/shkjocke/esm-slask $ esm_versions check
+---------------------+-----------+---------------------------------------------------+---------------+---------------------------+
| package_name        | version   | file                                              | branch        | tags                      |
|---------------------+-----------+---------------------------------------------------+---------------+---------------------------|
| esm_calendar        | 5.0.0     | /home/shkjocke/.local/lib/python3.7/site-packages |               |                           |
| esm_database        | 5.0.0     | /home/shkjocke/.local/lib/python3.7/site-packages |               |                           |
| esm_environment     | 5.0.0     | /home/shkjocke/.local/lib/python3.7/site-packages |               |                           |
| esm_master          | 5.0.1     | /home/shkjocke/.local/lib/python3.7/site-packages |               |                           |
| esm_motd            | 5.0.1     | /home/shkjocke/.local/lib/python3.7/site-packages |               |                           |
| esm_parser          | 5.0.4     | /home/shkjocke/tmp/esm_parser                     | develop       | v5.0.4-8-g58adf2a         |
| esm_plugin_manager  | 5.0.0     | /home/shkjocke/.local/lib/python3.7/site-packages |               |                           |
| esm_profile         | 5.0.0     | /home/shkjocke/.local/lib/python3.7/site-packages |               |                           |
| esm_rcfile          | 5.0.0     | /home/shkjocke/tmp/esm_rcfile                     | develop       | v5.0.0-3-gc1d2efe         |
| esm_runscripts      | 5.0.14    | /home/shkjocke/tmp/esm_runscripts                 | develop       | v5.0.14-42-g60d5cfe       |
| esm_tools           | 5.0.2     | /home/shkjocke/esm_tools                          | geomar_awicm3 | v5.0.12-99-g3710557-dirty |
| esm_version_checker | 5.1.1     | /home/shkjocke/.local/lib/python3.7/site-packages |               |                           |
+---------------------+-----------+---------------------------------------------------+---------------+---------------------------+
```

**Comment by denizural** [comment]
Dear @joakimkjellsson,
I am able to generate the isolated error from Python and I think I know what it wrong there. Could you please send the result of these commands from your blogin shell:

```bash
$ locale
$ echo $LANG
$ echo $LC_ALL
```

Main reason why Python throws a ValueError here is that the null byte (`\x00`) goes into the path string. Eg.
```python
os.path.exists('\x00')    # or anywhere inside the string eg. "/usr/local\x00"
```

If your locale settings are fixed (if they were not set up correctly), this could be a quick fix.

**Comment by joakimkjellsson** [comment]
Hi Deniz

Ah, I think my problem is with LC_ALL then. 

```bash
(base) blogin7:~ $ locale
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=en_US.UTF-8
LC_CTYPE=UTF-8
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
(base) blogin7:~ $ echo $LANG
en_US.UTF-8
(base) blogin7:~ $ echo $LC_ALL

(base) blogin7:~ $ 
```

I should define this on my local machine and then it propagates to blogin when I log in, right? 

Cheers
Joakim

**Comment by denizural** [comment]
Hi Joakim,

could you please repeat the `locale` command after these exports. They worked in an issue with another colleague. I hope that it works again.

```bash
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export LC_CTYPE="en_US.UTF-8"
```
If `locale` command does not complain again, then you can put them into your shell login file (eg. `.bashrc`, `.bash_profile`, etc)

If the error continues then it would also be a good idea to inform the blogin admins, so that they can fix the system-wide file but I hope only setting the environment variables should work. 

Actually, `esm_runscripts` sends `export LC_ALL=en_US.utf-8` to the `sad` script which is send to Slurm, but it seems like you have more missing stuff like `LC_CTYPE`.

**Comment by mandresm** [comment]
@joakimkjellsson , is the issue solved now? can we close it?

**Comment by joakimkjellsson** [comment]
Hey @denizural @mandresm 
Yes I think it's solved now. I've added the above lines to my .bashrc and restarting seems to work just fine now. 

Thanks again!
/J

**Comment by denizural** [comment]
Thank you very much for your feedback @joakimkjellsson. I am closing the issue now.
