### ISSUE TITLE
in_date_folder not found

### ISSUE THREAD

**Issue by joakimkjellsson** [esm-tools/esm_tools#284]
Good morning @mandresm and @JanStreffing 

I just tried to re-compile oifs-43r3-v1 with the new geomar_awicm3 branch of esm-tools and develop branches of esm-parser, runscripts, and rcfile. 
But the "clean" or "comp" commands do not work properly. It's looking for an in_date_folder, which does not exist (see message below). 

I think it worked before @mandresm made some new changes to the geomar_awicm3 branch, but the traceback points to esm_parser, so I'm not sure what caused it. 

Does "clean" or "comp" command work for other models and/or other machines? Does anyone know what the problem might be? 

Cheers
Joakim 

```bash
(base) blogin6:~/model_codes $ esm_master clean-oifs-43r3-v1
************************************************************************************
Message found for package esm_tools version 5.0.12:

"ESM Tools version 5.0.5 allows for the generation of hosing files in AWI-ESM-2.1 and AWI-ESM-2.2
To use that, you still need to install a plugin. Please run:

$ pip install --user gfw_creator"

Upgrade this package by typing:              esm_versions upgrade esm_tools
Upgrade all packages by typing:              esm_versions upgrade
************************************************************************************
Traceback (most recent call last):
  File "/home/shkjocke/tmp/esm_parser/esm_parser/esm_parser.py", line 1583, in recursive_get
    result = config_to_search[this_config]
KeyError: 'in_date_folder'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/shkjocke/tmp/esm_parser/esm_parser/esm_parser.py", line 1697, in actually_find_variable
    var_result = recursive_get(full_config, config_elements)
  File "/home/shkjocke/tmp/esm_parser/esm_parser/esm_parser.py", line 1590, in recursive_get
    return recursive_get(result, my_config_elements)
  File "/home/shkjocke/tmp/esm_parser/esm_parser/esm_parser.py", line 1586, in recursive_get
    "Exactly None! Couldn't find an answer for:", my_config_elements
ValueError: ("Exactly None! Couldn't find an answer for:", [])

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/shkjocke/tmp/esm_parser/esm_parser/esm_parser.py", line 1583, in recursive_get
    result = config_to_search[this_config]
KeyError: 'in_date_folder'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/shkjocke/tmp/esm_parser/esm_parser/esm_parser.py", line 1705, in actually_find_variable
    var_result = recursive_get(full_config, config_elements)
  File "/home/shkjocke/tmp/esm_parser/esm_parser/esm_parser.py", line 1590, in recursive_get
    return recursive_get(result, my_config_elements)
  File "/home/shkjocke/tmp/esm_parser/esm_parser/esm_parser.py", line 1586, in recursive_get
    "Exactly None! Couldn't find an answer for:", my_config_elements
ValueError: ("Exactly None! Couldn't find an answer for:", [])

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/shkjocke/.local/bin/esm_master", line 10, in <module>
    sys.exit(main())
  File "/home/shkjocke/.local/lib/python3.7/site-packages/esm_master/cli.py", line 76, in main
    main_flow(parsed_args, target)
  File "/home/shkjocke/.local/lib/python3.7/site-packages/esm_master/esm_master.py", line 36, in main_flow
    complete_setup = SimulationSetup(user_config=user_config)
  File "/home/shkjocke/tmp/esm_runscripts/esm_runscripts/sim_objects.py", line 42, in __init__
    self.config = prepare.run_job(self.config)
  File "/home/shkjocke/tmp/esm_runscripts/esm_runscripts/prepare.py", line 5, in run_job
    helpers.evaluate(config, "prepare", "prepare_recipe")
  File "/home/shkjocke/tmp/esm_runscripts/esm_runscripts/helpers.py", line 49, in evaluate
    framework_recipe, framework_plugins, config
  File "/home/shkjocke/.local/lib/python3.7/site-packages/esm_plugin_manager/esm_plugin_manager.py", line 130, in work_through_recipe
    config = getattr(submodule, workitem)(config)
  File "/home/shkjocke/tmp/esm_runscripts/esm_runscripts/prepare.py", line 604, in finalize_config
    config.finalize()
  File "/home/shkjocke/tmp/esm_parser/esm_parser/esm_parser.py", line 2617, in finalize
    self.run_recursive_functions(self)
  File "/home/shkjocke/tmp/esm_parser/esm_parser/esm_parser.py", line 2632, in run_recursive_functions
    isblacklist=isblacklist,
  File "/home/shkjocke/tmp/esm_parser/esm_parser/esm_parser.py", line 1546, in recursive_run_function
    tree + [key], value, level, func, *args, **kwargs
  File "/home/shkjocke/tmp/esm_parser/esm_parser/esm_parser.py", line 1546, in recursive_run_function
    tree + [key], value, level, func, *args, **kwargs
  File "/home/shkjocke/tmp/esm_parser/esm_parser/esm_parser.py", line 1546, in recursive_run_function
    tree + [key], value, level, func, *args, **kwargs
  File "/home/shkjocke/tmp/esm_parser/esm_parser/esm_parser.py", line 1519, in recursive_run_function
    right = func(tree + [None], right, *args, **kwargs)
  File "/home/shkjocke/tmp/esm_parser/esm_parser/esm_parser.py", line 1625, in find_variable
    var_result, var_attrs = actually_find_variable(tree, var, full_config)
  File "/home/shkjocke/tmp/esm_parser/esm_parser/esm_parser.py", line 1708, in actually_find_variable
    raise EsmParserError("Sorry, a variable was not resolved: %s not found" % (rhs))
esm_parser.esm_parser.EsmParserError: Sorry, a variable was not resolved: in_date_folder not found
```

**Comment by mandresm** [comment]
I'm working on it

**Comment by joakimkjellsson** [comment]
Ok, so if I copy this from awicm3.yaml to oifs.yaml, then it seems to work. 

```bash
in_date_folder: "${parent_date!syear!smonth!sday}"
out_date_folder: "${end_date!syear!smonth!sday}"
```

I guess it's something new that needs to be defined? 

/J

**Comment by mandresm** [comment]
Correct, I'm ready to push the fix, if that's okay with you

**Comment by joakimkjellsson** [comment]
Go for it! ;-) 
/J

**Comment by mandresm** [comment]
Done. You can pull now from `geomar_awicm3`

**Comment by JanStreffing** [comment]
closing old issues that are part of https://github.com/esm-tools/esm_tools/projects/2
