### ISSUE TITLE
Database IO Error causes run to stop

### ISSUE THREAD

**Issue by pgierz** [esm-tools/esm_tools#285]
Hi,

I ran into the following problem just now:
```
database_entry
--------------
Traceback (most recent call last):
  File "/mnt/lustre02/work/ba0989/a270077/PalModII/mis3/.venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 771, in _commit_impl
    self.engine.dialect.do_commit(self.connection)
  File "/mnt/lustre02/work/ba0989/a270077/PalModII/mis3/.venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 561, in do_commit
    dbapi_connection.commit()
sqlite3.OperationalError: disk I/O error
```

no idea what is causing that. A clean resubmit helped, but it would be nice to catch that error, as otherwise the entire job just stops.

**Comment by pgierz** [comment]
Solved in esm runscripts 5.1.8
