### ISSUE TITLE
pism_standalone not working with esm_tools

### ISSUE THREAD

**Issue by ackerlar** [esm-tools/esm_tools#296]
Hi,

I try to run pism standalone with the esm_tools. It worked for me with an earlier version. I now want to use the same *yaml except for a different ocean forcing.

I tried it with `esm_runscripts` on `release` and got this error:
```
The pism_overrides.nc file will contain stress_balance.model: ssa+sia
Writing a new pism_overrides.nc file!
Traceback (most recent call last):
  File "/home/ollie/lackerma/.local/bin/esm_runscripts", line 11, in <module>
    load_entry_point('esm-runscripts', 'console_scripts', 'esm_runscripts')()
  File "/home/ollie/lackerma/esm_runscripts/esm_runscripts/cli.py", line 193, in main
    Setup()
  File "/home/ollie/lackerma/esm_runscripts/esm_runscripts/sim_objects.py", line 50, in __call__
    self.compute(*args, **kwargs)
  File "/home/ollie/lackerma/esm_runscripts/esm_runscripts/sim_objects.py", line 84, in compute
    self.config = compute.run_job(self.config)
  File "/home/ollie/lackerma/esm_runscripts/esm_runscripts/compute.py", line 31, in run_job
    config = evaluate(config, "compute", "compute_recipe")
  File "/home/ollie/lackerma/esm_runscripts/esm_runscripts/helpers.py", line 69, in evaluate
    framework_recipe, framework_plugins, config
  File "/home/ollie/lackerma/.local/lib/python3.7/site-packages/esm_plugin_manager/esm_plugin_manager.py", line 130, in work_through_recipe
    config = getattr(submodule, workitem)(config)
AttributeError: module 'esm_runscripts.compute' has no attribute 'assemble_filelists'
```

and with `esm_runscripts` on `feature/pism` and got this error:
```
2021-03-11 17:25:29.135 | ERROR    | esm_plugin_manager.esm_plugin_manager:work_through_recipe:133 - An error has been caught in function 'work_through_recipe', process 'MainProcess' (21414), thread 'MainThread' (140669303359296):
Traceback (most recent call last):

  File "/home/ollie/lackerma/.local/bin/esm_runscripts", line 11, in <module>
    load_entry_point('esm-runscripts', 'console_scripts', 'esm_runscripts')()
    └ <function load_entry_point at 0x7ff017ce19e0>

  File "/home/ollie/lackerma/esm_runscripts/esm_runscripts/cli.py", line 168, in main
    Setup()
    └ <esm_runscripts.esm_sim_objects.SimulationSetup object at 0x7ff0183a7b50>

  File "/home/ollie/lackerma/esm_runscripts/esm_runscripts/esm_sim_objects.py", line 169, in __call__
    self.compute(*args, **kwargs)
    │    │        │       └ {}
    │    │        └ ()
    │    └ <function SimulationSetup.compute at 0x7fefcec93c20>
    └ <esm_runscripts.esm_sim_objects.SimulationSetup object at 0x7ff0183a7b50>

  File "/home/ollie/lackerma/esm_runscripts/esm_runscripts/esm_sim_objects.py", line 195, in compute
    self.config = Compute.evaluate(self.config)
    │    │        │       │        │    └ {'computer': {'name': 'ollie', 'accounting': False, 'batch_system': 'slurm', 'operating_system': 'linux-centos', 'jobtype': '...
    │    │        │       │        └ <esm_runscripts.esm_sim_objects.SimulationSetup object at 0x7ff0183a7b50>
    │    │        │       └ <function jobclass.evaluate at 0x7fefcec0a8c0>
    │    │        └ <esm_runscripts.compute.compute object at 0x7fefcdc1bc90>
    │    └ {'computer': {'name': 'ollie', 'accounting': False, 'batch_system': 'slurm', 'operating_system': 'linux-centos', 'jobtype': '...
    └ <esm_runscripts.esm_sim_objects.SimulationSetup object at 0x7ff0183a7b50>

  File "/home/ollie/lackerma/esm_runscripts/esm_runscripts/jobclass.py", line 38, in evaluate
    config = esm_plugin_manager.work_through_recipe(self.framework_recipe, self.framework_plugins, config)
             │                  │                   │    │                 │    │                  └ {'computer': {'name': 'ollie', 'accounting': False, 'batch_system': 'slurm', 'operating_system': 'linux-centos', 'jobtype': '...
             │                  │                   │    │                 │    └ {'_create_setup_folders': {'module': 'esm_runscripts', 'submodule': 'compute', 'type': 'core'}, '_create_component_folders': ...
             │                  │                   │    │                 └ <esm_runscripts.compute.compute object at 0x7fefcdc1bc90>
             │                  │                   │    └ {'debug_info': {'loaded_from_file': '/home/ollie/lackerma/esm_tools/configs/esm_software/esm_runscripts/esm_runscripts.yaml'}...
             │                  │                   └ <esm_runscripts.compute.compute object at 0x7fefcdc1bc90>
             │                  └ <function work_through_recipe at 0x7fefcec11200>
             └ <module 'esm_plugin_manager' from '/home/ollie/lackerma/.local/lib/python3.7/site-packages/esm_plugin_manager/__init__.py'>

> File "/home/ollie/lackerma/.local/lib/python3.7/site-packages/esm_plugin_manager/esm_plugin_manager.py", line 133, in work_through_recipe
    config = plugins[workitem]["callable"](config)
             │       │                     └ {'computer': {'name': 'ollie', 'accounting': False, 'batch_system': 'slurm', 'operating_system': 'linux-centos', 'jobtype': '...
             │       └ 'pism_assemble_command'
             └ {'_create_setup_folders': {'module': 'esm_runscripts', 'submodule': 'compute', 'type': 'core'}, '_create_component_folders': ...
  File "/home/ollie/lackerma/.local/lib/python3.7/site-packages/esm_pism/plugin.py", line 267, in pism_assemble_command
    + f" -o_size {config['pism']['outdata_size']} -options_left"

KeyError: 'restart_out_in_work'
Traceback (most recent call last):
  File "/home/ollie/lackerma/.local/bin/esm_runscripts", line 11, in <module>
    load_entry_point('esm-runscripts', 'console_scripts', 'esm_runscripts')()
  File "/home/ollie/lackerma/esm_runscripts/esm_runscripts/cli.py", line 168, in main
    Setup()
  File "/home/ollie/lackerma/esm_runscripts/esm_runscripts/esm_sim_objects.py", line 169, in __call__
    self.compute(*args, **kwargs)
  File "/home/ollie/lackerma/esm_runscripts/esm_runscripts/esm_sim_objects.py", line 195, in compute
    self.config = Compute.evaluate(self.config)
  File "/home/ollie/lackerma/esm_runscripts/esm_runscripts/jobclass.py", line 38, in evaluate
    config = esm_plugin_manager.work_through_recipe(self.framework_recipe, self.framework_plugins, config)
  File "/home/ollie/lackerma/.local/lib/python3.7/site-packages/esm_plugin_manager/esm_plugin_manager.py", line 124, in work_through_recipe
    if config["general"].get("verbose",False):
TypeError: 'NoneType' object is not subscriptable
```

My *yaml file can be found here: `/work/ollie/lackerma/awicm_pism_tests/pism_antarctica09/scripts/example_config.yaml` and `esm_versions check` gives:
```
+---------------------+-------------+---------------------------------------------------------+--------------------------+--------------------+
| package_name        | version     | file                                                    | branch                   | tags               |
|---------------------+-------------+---------------------------------------------------------+--------------------------+--------------------|
| esm_calendar        | 5.0.0       | /home/ollie/lackerma/.local/lib/python3.7/site-packages |                          |                    |
| esm_database        | 5.0.0       | /home/ollie/lackerma/.local/lib/python3.7/site-packages |                          |                    |
| esm_environment     | 5.0.0       | /home/ollie/lackerma/.local/lib/python3.7/site-packages |                          |                    |
| esm_master          | 5.0.1       | /home/ollie/lackerma/.local/lib/python3.7/site-packages |                          |                    |
| esm_motd            | 5.0.1       | /home/ollie/lackerma/.local/lib/python3.7/site-packages |                          |                    |
| esm_parser          | 5.0.3       | /home/ollie/lackerma/.local/lib/python3.7/site-packages |                          |                    |
| esm_pism            | 0.0.1.dev12 | /home/ollie/lackerma/.local/lib/python3.7/site-packages |                          |                    |
| esm_plugin_manager  | 5.0.0       | /home/ollie/lackerma/.local/lib/python3.7/site-packages |                          |                    |
| esm_profile         | 5.0.0       | /home/ollie/lackerma/.local/lib/python3.7/site-packages |                          |                    |
| esm_rcfile          | 5.0.0       | /home/ollie/lackerma/.local/lib/python3.7/site-packages |                          |                    |
| esm_runscripts      | 4.2.1       | /home/ollie/lackerma/esm_runscripts                     | feature/pism             | v4.2.1-16-ga6733ac |
| esm_tools           | 5.0.16      | /home/ollie/lackerma/esm_tools                          | duplicate_variables_pism | v5.0.16-2-g2b2b869 |
| esm_version_checker | 5.1.1       | /home/ollie/lackerma/.local/lib/python3.7/site-packages |                          |                    |
+---------------------+-------------+---------------------------------------------------------+--------------------------+--------------------+
```

Does someone hast got a clue what to do about this?

**Comment by pgierz** [comment]
Trying merging the duplicate variables branch into the one you were using yesterday, that may help

**Comment by ackerlar** [comment]
Unfortunately, this does not help. I tried it yesterday already.
