### ISSUE TITLE
OpenIFS long run restart workaround

### ISSUE THREAD

**Issue by JanStreffing** [esm-tools/esm_tools#300]
OpenIFS has memory and runtime explosion issues with runs where the time between the start of the leg and the inital date gets too large. I devices a workaround in the legacy tools that I am trying to transfer over to the python tools. The general idea is:

Instead of making the time between init and current larger with every simulation leg, start from the 3rd leg we move the inital time forward. Implementation includes:

- In a shell plugin script modifying OpenIFS and wam inital files such that: 
  Leg1: change to inital date
  Leg2: dont do anything
  Leg3 onwards: change to start date to last_start_date
- In a shell plugin script modify the restart control files rcf and waminfo the same way.
- With the general namelist replacer modify wam_namelist in the same way.
- While linking the restart files into the work directory rename them to fit the shifting initial date

The first shot can be seen at: https://github.com/esm-tools/esm_tools/commit/722a3b8263a720e6778c85cc7b100180467ea1f7
It also required a minor addition in the esm_runscripts, which can be seen here: https://github.com/esm-tools/esm_runscripts/commits/eternal_restarts_for_oifs

```
+---------------------+-----------+---------------------------------------------------------------+---------------------------+----------------------------+
| package_name        | version   | file                                                          | branch                    | tags                       |
|---------------------+-----------+---------------------------------------------------------------+---------------------------+----------------------------|
| esm_calendar        | 5.0.0     | /mnt/lustre01/pf/a/a270092/.local/lib/python3.6/site-packages |                           |                            |
| esm_database        | 5.0.0     | /mnt/lustre01/pf/a/a270092/.local/lib/python3.6/site-packages |                           |                            |
| esm_environment     | 5.0.0     | /mnt/lustre01/pf/a/a270092/.local/lib/python3.6/site-packages |                           |                            |
| esm_master          | 5.0.1     | /mnt/lustre01/pf/a/a270092/.local/lib/python3.6/site-packages |                           |                            |
| esm_motd            | 5.0.1     | /mnt/lustre01/pf/a/a270092/.local/lib/python3.6/site-packages |                           |                            |
| esm_parser          | 5.0.6     | /mnt/lustre01/pf/a/a270092/esm_parser                         | develop                   | v5.0.7-14-g6545da3         |
| esm_plugin_manager  | 5.0.0     | /mnt/lustre01/pf/a/a270092/.local/lib/python3.6/site-packages |                           |                            |
| esm_profile         | 5.0.0     | /mnt/lustre01/pf/a/a270092/.local/lib/python3.6/site-packages |                           |                            |
| esm_rcfile          | 5.0.0     | /mnt/lustre01/pf/a/a270092/esm_rcfile                         | develop                   | v5.0.0-3-gc1d2efe          |
| esm_runscripts      | 5.0.9     | /mnt/lustre01/pf/a/a270092/esm_runscripts                     | eternal_restarts_for_oifs | v5.0.16-64-g6a0e8c4        |
| esm_tools           | 5.0.8     | /mnt/lustre01/pf/a/a270092/esm_tools                          | eternal_restarts_for_oifs | v5.0.12-137-g722a3b8-dirty |
| esm_version_checker | 5.1.1     | /mnt/lustre01/pf/a/a270092/.local/lib/python3.6/site-packages |                           |                            |
+---------------------+-----------+---------------------------------------------------------------+---------------------------+----------------------------+
```
Currently this crashes with:
```
esm_runscripts awicm3-mistral-TL159L60-CORE2.yaml -e ER01 --open-run
Traceback (most recent call last):
  File "/mnt/lustre01/pf/a/a270092/esm_parser/esm_parser/esm_parser.py", line 1640, in recursive_get
    result = config_to_search[this_config]
KeyError: 'start_seconds'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/lustre01/pf/a/a270092/esm_parser/esm_parser/esm_parser.py", line 1754, in actually_find_variable
    var_result = recursive_get(full_config, config_elements)
  File "/mnt/lustre01/pf/a/a270092/esm_parser/esm_parser/esm_parser.py", line 1647, in recursive_get
    return recursive_get(result, my_config_elements)
  File "/mnt/lustre01/pf/a/a270092/esm_parser/esm_parser/esm_parser.py", line 1643, in recursive_get
    "Exactly None! Couldn't find an answer for:", my_config_elements
ValueError: ("Exactly None! Couldn't find an answer for:", [])

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/lustre01/pf/a/a270092/esm_parser/esm_parser/esm_parser.py", line 1640, in recursive_get
    result = config_to_search[this_config]
KeyError: 'start_seconds'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/lustre01/pf/a/a270092/esm_parser/esm_parser/esm_parser.py", line 1762, in actually_find_variable
    var_result = recursive_get(full_config, config_elements)
  File "/mnt/lustre01/pf/a/a270092/esm_parser/esm_parser/esm_parser.py", line 1647, in recursive_get
    return recursive_get(result, my_config_elements)
  File "/mnt/lustre01/pf/a/a270092/esm_parser/esm_parser/esm_parser.py", line 1643, in recursive_get
    "Exactly None! Couldn't find an answer for:", my_config_elements
ValueError: ("Exactly None! Couldn't find an answer for:", [])

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/pf/a/a270092/.local/bin/esm_runscripts", line 11, in <module>
    load_entry_point('esm-runscripts', 'console_scripts', 'esm_runscripts')()
  File "/mnt/lustre01/pf/a/a270092/esm_runscripts/esm_runscripts/cli.py", line 199, in main
    Setup = SimulationSetup(command_line_config)
  File "/mnt/lustre01/pf/a/a270092/esm_runscripts/esm_runscripts/sim_objects.py", line 42, in __init__
    self.config = prepare.run_job(self.config)
  File "/mnt/lustre01/pf/a/a270092/esm_runscripts/esm_runscripts/prepare.py", line 6, in run_job
    helpers.evaluate(config, "prepare", "prepare_recipe")
  File "/mnt/lustre01/pf/a/a270092/esm_runscripts/esm_runscripts/helpers.py", line 49, in evaluate
    framework_recipe, framework_plugins, config
  File "/pf/a/a270092/.local/lib/python3.6/site-packages/esm_plugin_manager/esm_plugin_manager.py", line 130, in work_through_recipe
    config = getattr(submodule, workitem)(config)
  File "/mnt/lustre01/pf/a/a270092/esm_runscripts/esm_runscripts/prepare.py", line 645, in finalize_config
    config.finalize()
  File "/mnt/lustre01/pf/a/a270092/esm_parser/esm_parser/esm_parser.py", line 2674, in finalize
    self.run_recursive_functions(self)
  File "/mnt/lustre01/pf/a/a270092/esm_parser/esm_parser/esm_parser.py", line 2681, in run_recursive_functions
    recursive_run_function([], config, "atomic", perform_actions, config)
  File "/mnt/lustre01/pf/a/a270092/esm_parser/esm_parser/esm_parser.py", line 1603, in recursive_run_function
    tree + [key], value, level, func, *args, **kwargs
  File "/mnt/lustre01/pf/a/a270092/esm_parser/esm_parser/esm_parser.py", line 1603, in recursive_run_function
    tree + [key], value, level, func, *args, **kwargs
  File "/mnt/lustre01/pf/a/a270092/esm_parser/esm_parser/esm_parser.py", line 1576, in recursive_run_function
    right = func(tree + [None], right, *args, **kwargs)
  File "/mnt/lustre01/pf/a/a270092/esm_parser/esm_parser/esm_parser.py", line 2165, in perform_actions
    True,
  File "/mnt/lustre01/pf/a/a270092/esm_parser/esm_parser/esm_parser.py", line 1691, in find_variable
    isblacklist,
  File "/mnt/lustre01/pf/a/a270092/esm_parser/esm_parser/esm_parser.py", line 1682, in find_variable
    var_result, var_attrs = actually_find_variable(tree, var, full_config)
  File "/mnt/lustre01/pf/a/a270092/esm_parser/esm_parser/esm_parser.py", line 1765, in actually_find_variable
    raise EsmParserError("Sorry, a variable was not resolved: %s not found" % (rhs))
esm_parser.esm_parser.EsmParserError: Sorry, a variable was not resolved: start_seconds not found

```

Is this another case of things that are defined in the choose block are not available outside of it yet? Does the variable run_number not exist yet?

**Comment by mandresm** [comment]
The problem here is that you need to specify it's in the `general` chapter:
```
choose_general.run_number:
    1:
        [ ... ]
```
Then, a new problem rises complaining about `seconds_since_initial`. I'm already looking at it.

**Comment by mandresm** [comment]
The next problem is that there is a problem with the curly braces in the last line of the `awicm3` preprocessing:
```
        preprocess:
                preprocess_shell:

                        choose_run_number: 
                                1:  
                                        method: "${general.esm_function_dir}/components/oifs/change_icm_date.sh ${thisrun_input_dir}/ ${oifs.input_expid} ${oifs.input_expid} ${initial_date!syear!smonth!sday} ${start_date!syear!smonth!sday}  ${thisrun_input_dir} ${oifs.wam_number} ${oifs.perturb} ${oifs.nx} ${oifs.ensemble_id}"
                                        type: shell
                                2:  
                                        method: "${general.esm_function_dir}/components/oifs/skip.sh"
                                        type: shell
                                "*":
                                        method: "${general.esm_function_dir}/components/oifs/change_icm_date.sh ${thisrun_input_dir}/ ${oifs.input_expid} ${oifs.input_expid} ${last_start_date!syear!smonth!sday} ${start_date!syear!smonth!sday}  ${thisrun_input_dir} ${oifs.wam_number} ${oifs.perturb} ${oifs.nx} ${oifs.ensemble_id}; 
                                                ${general.esm_function_dir}/components/oifs/change_rcf_date.sh ${thisrun_input_dir}/ ${last_start_date!syear!smonth!sday} ${last_start_date!sday} ${oifs.time_step ${oifs.seconds_since_initial}} ${oifs.days_since_initial} ${oifs.wam}"
```

This in particular:
```
 ${oifs.time_step ${oifs.seconds_since_initial}} 
```

**Comment by JanStreffing** [comment]
Ah i get the first one.
Second one I must have just been tired. It should be:` ${oifs.time_step} ${oifs.seconds_since_initial}`
Ty!
