### ISSUE TITLE
computer.fc not found

### ISSUE THREAD

**Issue by JanStreffing** [esm-tools/esm_tools#305]
Hey everyone,
I'm working on a new machine file for [aleph.iccp.kr](https://ibsclimate.org/research/facilities/aleph-supercomputer/). I'm trying to install-awicm3-1.0-deck there and I'm getting this error:
```

Traceback (most recent call last):
  File "/mnt/lustre/home/awiiccp2/esm/esm_parser/esm_parser/esm_parser.py", line 1643, in recursive_get
    result = config_to_search[this_config]
KeyError: 'fc'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/lustre/home/awiiccp2/esm/esm_parser/esm_parser/esm_parser.py", line 1758, in actually_find_variable
    var_result = recursive_get(full_config, config_elements)
  File "/mnt/lustre/home/awiiccp2/esm/esm_parser/esm_parser/esm_parser.py", line 1650, in recursive_get
    return recursive_get(result, my_config_elements)
  File "/mnt/lustre/home/awiiccp2/esm/esm_parser/esm_parser/esm_parser.py", line 1645, in recursive_get
    raise ValueError(
ValueError: ("Exactly None! Couldn't find an answer for:", [])

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/lustre/home/awiiccp2/esm/esm_parser/esm_parser/esm_parser.py", line 1643, in recursive_get
    result = config_to_search[this_config]
KeyError: 'fc'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/lustre/home/awiiccp2/esm/esm_parser/esm_parser/esm_parser.py", line 1766, in actually_find_variable
    var_result = recursive_get(full_config, config_elements)
  File "/mnt/lustre/home/awiiccp2/esm/esm_parser/esm_parser/esm_parser.py", line 1650, in recursive_get
    return recursive_get(result, my_config_elements)
  File "/mnt/lustre/home/awiiccp2/esm/esm_parser/esm_parser/esm_parser.py", line 1645, in recursive_get
    raise ValueError(
ValueError: ("Exactly None! Couldn't find an answer for:", [])

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/awiiccp2/.local/bin/esm_master", line 8, in <module>
    sys.exit(main())
  File "/home/awiiccp2/.local/lib/python3.9/site-packages/esm_master/cli.py", line 76, in main
    main_flow(parsed_args, target)
  File "/home/awiiccp2/.local/lib/python3.9/site-packages/esm_master/esm_master.py", line 36, in main_flow
    complete_setup = SimulationSetup(user_config=user_config)
  File "/mnt/lustre/home/awiiccp2/esm/esm_runscripts/esm_runscripts/sim_objects.py", line 42, in __init__
    self.config = prepare.run_job(self.config)
  File "/mnt/lustre/home/awiiccp2/esm/esm_runscripts/esm_runscripts/prepare.py", line 6, in run_job
    helpers.evaluate(config, "prepare", "prepare_recipe")
  File "/mnt/lustre/home/awiiccp2/esm/esm_runscripts/esm_runscripts/helpers.py", line 48, in evaluate
    config = esm_plugin_manager.work_through_recipe(
  File "/home/awiiccp2/.local/lib/python3.9/site-packages/esm_plugin_manager/esm_plugin_manager.py", line 138, in work_through_recipe
    config = getattr(submodule, workitem)(config)
  File "/mnt/lustre/home/awiiccp2/esm/esm_runscripts/esm_runscripts/prepare.py", line 629, in finalize_config
    config.finalize()
  File "/mnt/lustre/home/awiiccp2/esm/esm_parser/esm_parser/esm_parser.py", line 2683, in finalize
    self.run_recursive_functions(self)
  File "/mnt/lustre/home/awiiccp2/esm/esm_parser/esm_parser/esm_parser.py", line 2691, in run_recursive_functions
    recursive_run_function(
  File "/mnt/lustre/home/awiiccp2/esm/esm_parser/esm_parser/esm_parser.py", line 1605, in recursive_run_function
    right[key] = recursive_run_function(
  File "/mnt/lustre/home/awiiccp2/esm/esm_parser/esm_parser/esm_parser.py", line 1605, in recursive_run_function
    right[key] = recursive_run_function(
  File "/mnt/lustre/home/awiiccp2/esm/esm_parser/esm_parser/esm_parser.py", line 1605, in recursive_run_function
    right[key] = recursive_run_function(
  [Previous line repeated 2 more times]
  File "/mnt/lustre/home/awiiccp2/esm/esm_parser/esm_parser/esm_parser.py", line 1586, in recursive_run_function
    new_item = recursive_run_function(
  File "/mnt/lustre/home/awiiccp2/esm/esm_parser/esm_parser/esm_parser.py", line 1579, in recursive_run_function
    right = func(tree + [None], right, *args, **kwargs)
  File "/mnt/lustre/home/awiiccp2/esm/esm_parser/esm_parser/esm_parser.py", line 1685, in find_variable
    var_result, var_attrs = actually_find_variable(tree, var, full_config)
  File "/mnt/lustre/home/awiiccp2/esm/esm_parser/esm_parser/esm_parser.py", line 1769, in actually_find_variable
    raise EsmParserError("Sorry, a variable was not resolved: %s not found" % (rhs))
esm_parser.esm_parser.EsmParserError: Sorry, a variable was not resolved: computer.fc not found
```
I'm using:
```
+---------------------+-----------+--------------------------------------------------------------+--------------------+----------------------+
| package_name        | version   | file                                                         | branch             | tags                 |
|---------------------+-----------+--------------------------------------------------------------+--------------------+----------------------|
| esm_calendar        | 5.0.0     | /mnt/lustre/home/awiiccp2/.local/lib/python3.9/site-packages |                    |                      |
| esm_database        | 5.0.0     | /mnt/lustre/home/awiiccp2/.local/lib/python3.9/site-packages |                    |                      |
| esm_environment     | 5.0.0     | /mnt/lustre/home/awiiccp2/esm/esm_environment                | develop            | v5.0.0-16-gfe53112   |
| esm_master          | 5.0.6     | /mnt/lustre/home/awiiccp2/.local/lib/python3.9/site-packages |                    |                      |
| esm_motd            | 5.0.2     | /mnt/lustre/home/awiiccp2/.local/lib/python3.9/site-packages |                    |                      |
| esm_parser          | 5.0.7     | /mnt/lustre/home/awiiccp2/esm/esm_parser                     | develop            | v5.0.7-17-gf9a8b8d   |
| esm_plugin_manager  | 5.0.1     | /mnt/lustre/home/awiiccp2/.local/lib/python3.9/site-packages |                    |                      |
| esm_profile         | 5.0.0     | /mnt/lustre/home/awiiccp2/.local/lib/python3.9/site-packages |                    |                      |
| esm_rcfile          | 5.0.0     | /mnt/lustre/home/awiiccp2/esm/esm_rcfile                     | develop            | v5.0.0-3-gc1d2efe    |
| esm_runscripts      | 5.0.17    | /mnt/lustre/home/awiiccp2/esm/esm_runscripts                 | develop            | v5.0.17-70-g029ff1d  |
| esm_tools           | 5.0.12    | /mnt/lustre/home/awiiccp2/esm/esm_tools                      | aleph_machine_file | v5.0.12-163-gd51328a |
| esm_version_checker | 5.1.2     | /mnt/lustre/home/awiiccp2/.local/lib/python3.9/site-packages |                    |                      |
+---------------------+-----------+--------------------------------------------------------------+--------------------+----------------------+
```
Branch: https://github.com/esm-tools/esm_tools/commits/aleph_machine_file

I printed out rhs in esm_parser just before the crash and I found that this happens on the first computer. variable that is processed by the parser. Somehow I'm not sure if the tools recognize that they are on Aleph. The login nodes there are called elogin1 and elogin2. Is the entry in all_machines.yaml that I made enough for the tools to figure out where they are, and which machine file to parse?

Do you se any other issue where the missing computer.fc might come from?

**Comment by denizural** [comment]
Hi @JanStreffing, 
such errors occur when a variable is encountered but it is not resolved in the base YAML files. Here, I think what is going on is `fc` variable which is likely to be in the `computer` section of the config is not assigned to any value and the parser is complaining about that it does not have any value. 

I checked the branch that you provided. It looks like `fc` variable is not filled with anything. You can provide a default value for that. Try with moving the `fc` out of the `choose_` block. I guess, the parser will not complain then. Of course this is not the final solution. 

I think when you are trying to use anything other than the intel_mpi where `fc` is defined, the parser complains since it can't find the value. 

In this commit: https://github.com/esm-tools/esm_tools/commit/946d39d8fa51e661af54beda2e5c5f007c1c5b12#diff-2d14b350b9e27bf48bdcea7d1afd6314f4ba88343504387c25c9bee18062c8d4
you are using `craympi` and `${fc}` will therefore be undefined.

I don't really think that this issue deserves to be labelled as a `bug`, by the way.

**Comment by JanStreffing** [comment]
Hey Deniz,
thank you for having a look at this. This was also the conclusion I reached yesterday. I tried to fix this in the second commit: https://github.com/esm-tools/esm_tools/commit/d51328aea14f3157cde790cb424098b62c880153
As you can see I provide the correct fortran compiler for cray (ftn) and I do so without any choose block or the need to read ${FC} from the environment:

https://github.com/esm-tools/esm_tools/blob/d51328aea14f3157cde790cb424098b62c880153/configs/machines/aleph.yaml#L55-L62

I would have expected for this to resolve the error, but it did not.

I have removed bug and made it a questions. I more thought of it as a bug in my code.

**Comment by JanStreffing** [comment]
Turns out that those lines 57-62 are case sensitive and must be lowercase. Thanks @mandresm for the fix.
