### ISSUE TITLE
I chose an idiotic month: FOCIOIFS

### ISSUE THREAD

**Issue by joakimkjellsson** [esm-tools/esm_tools#33]
Hey guys

I lost the ability to compile FOCI-OpenIFS. I haven't done it for a while so it's possible something changed somewhere. 
The problem seems to have to do with the dates, but I don't know which dates. 
Any help here is much appreciated. 

This is using branch "foci2" of esm_tools, and here's the output:

```
b350090@mlogin105% esm_master get-focioifs-2.0
esm_calendar: makesense: ndate [2000, 1, 0, 0, 0, 0]
esm_calendar: makesense: ndate [2001, 1, 1, 0, 0, 0]
esm_calendar: makesense: ndate [1999, 1, 1, 0, 0, 0]
esm_calendar: makesense: ndate [2001, 1, 0, 0, 0, 0]
esm_calendar: makesense: ndate [2000, 1, 0, 23, 0, 0]
esm_calendar: makesense: ndate [2000, 1, 0, 23, 30, 0]
esm_calendar: makesense: ndate [2000, 1, 0, 23, 45, 0]
esm_calendar: makesense: ndate [2000, 12, 32, 0, 0, 0]
Traceback (most recent call last):
  File "/pf/b/b350090/.local/bin/esm_master", line 8, in <module>
    sys.exit(main())
  File "/pf/b/b350090/.local/lib/python3.6/site-packages/esm_master/cli.py", line 69, in main
    complete_setup = SimulationSetup(user_config = user_config)
  File "/pf/b/b350090/.local/lib/python3.6/site-packages/esm_runscripts-4.0.2-py3.6.egg/esm_runscripts/esm_sim_objects.py", line 48, in __init__
    self.get_total_config_from_user_config(user_config)
  File "/pf/b/b350090/.local/lib/python3.6/site-packages/esm_runscripts-4.0.2-py3.6.egg/esm_runscripts/esm_sim_objects.py", line 261, in get_total_config_from_user_config
    self.config.finalize()
  File "/pf/b/b350090/.local/lib/python3.6/site-packages/esm_parser-4.0.1-py3.6.egg/esm_parser/esm_parser.py", line 2165, in finalize
    self.run_recursive_functions(self)
  File "/pf/b/b350090/.local/lib/python3.6/site-packages/esm_parser-4.0.1-py3.6.egg/esm_parser/esm_parser.py", line 2182, in run_recursive_functions
    isblacklist=isblacklist,
  File "/pf/b/b350090/.local/lib/python3.6/site-packages/esm_parser-4.0.1-py3.6.egg/esm_parser/esm_parser.py", line 1287, in recursive_run_function
    tree + [key], value, level, func, *args, **kwargs
  File "/pf/b/b350090/.local/lib/python3.6/site-packages/esm_parser-4.0.1-py3.6.egg/esm_parser/esm_parser.py", line 1287, in recursive_run_function
    tree + [key], value, level, func, *args, **kwargs
  File "/pf/b/b350090/.local/lib/python3.6/site-packages/esm_parser-4.0.1-py3.6.egg/esm_parser/esm_parser.py", line 1272, in recursive_run_function
    right = func(tree + [None], right, *args, **kwargs)
  File "/pf/b/b350090/.local/lib/python3.6/site-packages/esm_parser-4.0.1-py3.6.egg/esm_parser/esm_parser.py", line 1379, in find_variable
    var_result = do_math_in_entry(tree, var_result, full_config)
  File "/pf/b/b350090/.local/lib/python3.6/site-packages/esm_parser-4.0.1-py3.6.egg/esm_parser/esm_parser.py", line 1761, in do_math_in_entry
    result = eval(math)
  File "<string>", line 1, in <module>
  File "/pf/b/b350090/.local/lib/python3.6/site-packages/esm_calendar-4.0.0-py3.6.egg/esm_calendar/esm_calendar.py", line 846, in add
    result = self.makesense(result)
  File "/pf/b/b350090/.local/lib/python3.6/site-packages/esm_calendar-4.0.0-py3.6.egg/esm_calendar/esm_calendar.py", line 802, in makesense
    while ndate[2] > self._calendar.day_in_month(ndate[0], ndate[1]):
  File "/pf/b/b350090/.local/lib/python3.6/site-packages/esm_calendar-4.0.0-py3.6.egg/esm_calendar/esm_calendar.py", line 183, in day_in_month
    raise TypeError("You have given an idiotic month, please reconsider")
TypeError: You have given an idiotic month, please reconsider
```

I know I'm an idiot, but I don't understand why I need a date when I'm trying to compile the model ;-) 
The first few lines are from a print statement I added in esm_calendar. The error comes from the 32nd day of December 2000, but why and how has this date been set? 

For info, this is on mistral and I'm using the following esm_versions

```
b350090@mlogin105% esm_versions check
You are using the following esm_tools versions:
-----------------------------------------------
esm_archiving : unknown version!
esm_autotests : unknown version!
esm_calendar : 4.0.0
esm_database : 4.0.0
esm_environment : 4.0.0
esm_master : 4.0.0
esm_parser : 4.0.1
esm_profile : 4.0.0
esm_rcfile : 4.0.0
esm_runscripts : 4.0.2
esm_tools : 4.0.3
esm_plugin_manager : 4.0.0
esm_version_checker : 4.0.0
```

My esm_runscripts is branch "oifs_stuff". 

Cheers
Joakim

**Comment by dbarbi** [comment]
HI, just pushed a bugfix to "release" of esm_calendar, please check

**Comment by joakimkjellsson** [comment]
Awesome! "get" worked and "compile" seems to work too! 
Thanks!
/Joakim
