### ISSUE TITLE
general.account not found

### ISSUE THREAD

**Issue by chrisdane** [esm-tools/esm_tools#334]
Hi

**Describe the bug**
Following the [Ten Steps to a Running Model](https://esm-tools.readthedocs.io/en/latest/ten_steps.html), I have this error when submitting the job: 
```
cd /pf/a/a270073/esm/runscripts
esm_runscripts fesom2-ollie-initial-monthly.yaml -e test -c

Traceback (most recent call last):
  File "/pf/a/a270073/.local/lib/python3.6/site-packages/esm_parser/esm_parser.py", line 1725, in recursive_get
    result = config_to_search[this_config]
KeyError: 'account'
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/pf/a/a270073/.local/lib/python3.6/site-packages/esm_parser/esm_parser.py", line 1839, in actually_find_variable
    var_result = recursive_get(full_config, config_elements)
  File "/pf/a/a270073/.local/lib/python3.6/site-packages/esm_parser/esm_parser.py", line 1732, in recursive_get
    return recursive_get(result, my_config_elements)
  File "/pf/a/a270073/.local/lib/python3.6/site-packages/esm_parser/esm_parser.py", line 1728, in recursive_get
    "Exactly None! Couldn't find an answer for:", my_config_elements
ValueError: ("Exactly None! Couldn't find an answer for:", [])

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/pf/a/a270073/.local/lib/python3.6/site-packages/esm_parser/esm_parser.py", line 1725, in recursive_get
    result = config_to_search[this_config]
KeyError: 'account'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/pf/a/a270073/.local/lib/python3.6/site-packages/esm_parser/esm_parser.py", line 1847, in actually_find_variable
    var_result = recursive_get(full_config, config_elements)
  File "/pf/a/a270073/.local/lib/python3.6/site-packages/esm_parser/esm_parser.py", line 1732, in recursive_get
    return recursive_get(result, my_config_elements)
  File "/pf/a/a270073/.local/lib/python3.6/site-packages/esm_parser/esm_parser.py", line 1728, in recursive_get
    "Exactly None! Couldn't find an answer for:", my_config_elements
ValueError: ("Exactly None! Couldn't find an answer for:", [])

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/pf/a/a270073/.local/bin/esm_runscripts", line 8, in <module>
    sys.exit(main())
  File "/pf/a/a270073/.local/lib/python3.6/site-packages/esm_runscripts/cli.py", line 199, in main
    Setup = SimulationSetup(command_line_config)
  File "/pf/a/a270073/.local/lib/python3.6/site-packages/esm_runscripts/sim_objects.py", line 43, in __init__
    self.config = prepare.run_job(self.config)
  File "/pf/a/a270073/.local/lib/python3.6/site-packages/esm_runscripts/prepare.py", line 6, in run_job
    helpers.evaluate(config, "prepare", "prepare_recipe")
  File "/pf/a/a270073/.local/lib/python3.6/site-packages/esm_runscripts/helpers.py", line 101, in evaluate
    framework_recipe, framework_plugins, config
  File "/pf/a/a270073/.local/lib/python3.6/site-packages/esm_plugin_manager/esm_plugin_manager.py", line 138, in work_through_recipe
    config = getattr(submodule, workitem)(config)
  File "/pf/a/a270073/.local/lib/python3.6/site-packages/esm_runscripts/prepare.py", line 645, in finalize_config
    config.finalize()
  File "/pf/a/a270073/.local/lib/python3.6/site-packages/esm_parser/esm_parser.py", line 2781, in finalize
    self.run_recursive_functions(self)
  File "/pf/a/a270073/.local/lib/python3.6/site-packages/esm_parser/esm_parser.py", line 2796, in run_recursive_functions
    isblacklist=isblacklist,
  File "/pf/a/a270073/.local/lib/python3.6/site-packages/esm_parser/esm_parser.py", line 1688, in recursive_run_function
    tree + [key], value, level, func, *args, **kwargs
  File "/pf/a/a270073/.local/lib/python3.6/site-packages/esm_parser/esm_parser.py", line 1688, in recursive_run_function
    tree + [key], value, level, func, *args, **kwargs
  File "/pf/a/a270073/.local/lib/python3.6/site-packages/esm_parser/esm_parser.py", line 1657, in recursive_run_function
    right = func(tree + [None], right, *args, **kwargs)
  File "/pf/a/a270073/.local/lib/python3.6/site-packages/esm_parser/esm_parser.py", line 1767, in find_variable
    var_result, var_attrs = actually_find_variable(tree, var, full_config)
  File "/pf/a/a270073/.local/lib/python3.6/site-packages/esm_parser/esm_parser.py", line 1850, in actually_find_variable
    raise EsmParserError("Sorry, a variable was not resolved: %s not found" % (rhs))
esm_parser.esm_parser.EsmParserError: Sorry, a variable was not resolved: general.account not found
```

**To Reproduce**
```
cd /pf/a/a270073/esm/runscripts
esm_runscripts fesom2-ollie-initial-monthly.yaml -e test -c
```

**Expected behavior**
Running job (with or without `-c`).

**System (please complete the following information):**
 - Supercomputer: mistral
 - Version: `esm_versions check` (the output of  `esm_versions check` does not work for markdown: the `+` need to be replaced by `|`!)

| package_name        | version   | file                                                          | branch   | tags   |
|---------------------|-----------|---------------------------------------------------------------|----------|--------|
| esm_analysis        | 0.3.0     | /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages |          |        |
| esm_archiving       | 0.1.0     | /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages |          |        |
| esm_calendar        | 5.0.0     | /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages |          |        |
| esm_database        | 5.0.0     | /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages |          |        |
| esm_environment     | 5.1.0     | /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages |          |        |
| esm_master          | 5.1.0     | /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages |          |        |
| esm_motd            | 5.0.2     | /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages |          |        |
| esm_parser          | 5.1.2     | /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages |          |        |
| esm_plugin_manager  | 5.0.1     | /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages |          |        |
| esm_profile         | 5.0.0     | /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages |          |        |
| esm_rcfile          | 5.1.0     | /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages |          |        |
| esm_runscripts      | 5.1.9     | /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages |          |        |
| esm_tools           | 5.1.0     | /mnt/lustre01/pf/a/a270073/esm/esm_tools                      | release  | v5.1.0 |
| esm_version_checker | 5.1.3     | /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages |          |        |

Cheers,
Chris

**Comment by mandresm** [comment]
Hi @chrisdane ,

I think the problem is that you are using an `ollie` runscript in `mistral`. The main difference in the runscripts is that `ollie` does not have the `account` variable which you need for `mistral` to submit the simulation.

Adding `account: <your_project_ID>` to the `general` section of your chapter should solve the issue.

**Comment by pgierz** [comment]
You need to set general.account. The error message isn't particularly friendly.

Try if this works:
```diff
general:
        setup_name: fesom
        compute_time: "00:08:00"
        initial_date: '2001-01-01'
        final_date: '2001-03-31'
        base_dir: "/work/ab0246/a270073/out/fesom-2.0"
        nyear: 0
        nmonth: 1
        use_venv: False
+       account: ab0246

fesom:
        version: 2.0
        model_dir: "/pf/a/a270073/esm/fesom-2.0"
        pool_dir: "/pool/data/AWICM/FESOM2"
        mesh_dir: "/pool/data/AWICM/FESOM2/MESHES/CORE2"
        res: CORE2
        lresume: 0
        restart_rate: 1
        restart_first: 1
        restart_unit: 'm'
        post_processing: 0

```

**Comment by pgierz** [comment]
....damnit Miguel was faster than I was

**Comment by chrisdane** [comment]
Yes that works. Thanks! 

Could you include default runscripts for mistral?

**Comment by mandresm** [comment]
I think I will reopen it, cause more than a mistral runscript we need a better error that tells you what to do in this case. Then, I'll leave it open until we make a fix for the error handling.

**Comment by mandresm** [comment]
After upgrading to the last patch of `esm_runscripts`, it now notifies displays a nice error if your `account` is not defined in the runscript and it is needed for the system you are using.
