### ISSUE TITLE
maximum recursion depth exceeded in comparison

### ISSUE THREAD

**Issue by chrisdane** [esm-tools/esm_tools#341]
I tried to enhance `/pf/a/a270073/esm/esm_tools/configs/components/fesom/fesom-2.0.yaml` by adding the lines
```
choose_computer.name:
  mistral:
    pool_dir: "${pool_dir}/AWICM/FESOM2"
    climate_data_dir: "${pool_dir}/INITIAL/phc3.0/" # variable for different initial data needed?
    forcing_data_dir: "${pool_dir}/FORCING/"
```
However, running `esm_runscripts /pf/a/a270073/esm/runscripts/fesom2-mistral-initial-monthly.yaml -e test -U -c` yields
```
Traceback (most recent call last):
  File "/pf/a/a270073/.local/bin/esm_runscripts", line 8, in <module>
    sys.exit(main())
  File "/pf/a/a270073/.local/lib/python3.6/site-packages/esm_runscripts/cli.py", line 199, in main
    Setup = SimulationSetup(command_line_config)
  File "/pf/a/a270073/.local/lib/python3.6/site-packages/esm_runscripts/sim_objects.py", line 43, in __init__
    self.config = prepare.run_job(self.config)
  File "/pf/a/a270073/.local/lib/python3.6/site-packages/esm_runscripts/prepare.py", line 6, in run_job
    helpers.evaluate(config, "prepare", "prepare_recipe")
  File "/pf/a/a270073/.local/lib/python3.6/site-packages/esm_runscripts/helpers.py", line 101, in evaluate
    framework_recipe, framework_plugins, config
  File "/pf/a/a270073/.local/lib/python3.6/site-packages/esm_plugin_manager/esm_plugin_manager.py", line 138, in work_through_recipe
    config = getattr(submodule, workitem)(config)
  File "/pf/a/a270073/.local/lib/python3.6/site-packages/esm_runscripts/prepare.py", line 645, in finalize_config
    config.finalize()
  File "/pf/a/a270073/.local/lib/python3.6/site-packages/esm_parser/esm_parser.py", line 2781, in finalize
    self.run_recursive_functions(self)
  File "/pf/a/a270073/.local/lib/python3.6/site-packages/esm_parser/esm_parser.py", line 2796, in run_recursive_functions
    isblacklist=isblacklist,
  File "/pf/a/a270073/.local/lib/python3.6/site-packages/esm_parser/esm_parser.py", line 1688, in recursive_run_function
    tree + [key], value, level, func, *args, **kwargs
  File "/pf/a/a270073/.local/lib/python3.6/site-packages/esm_parser/esm_parser.py", line 1688, in recursive_run_function
    tree + [key], value, level, func, *args, **kwargs
  File "/pf/a/a270073/.local/lib/python3.6/site-packages/esm_parser/esm_parser.py", line 1657, in recursive_run_function
    right = func(tree + [None], right, *args, **kwargs)
  File "/pf/a/a270073/.local/lib/python3.6/site-packages/esm_parser/esm_parser.py", line 1776, in find_variable
    isblacklist,
  File "/pf/a/a270073/.local/lib/python3.6/site-packages/esm_parser/esm_parser.py", line 1776, in find_variable
    isblacklist,
  File "/pf/a/a270073/.local/lib/python3.6/site-packages/esm_parser/esm_parser.py", line 1776, in find_variable
    isblacklist,
  [Previous line repeated 970 more times]
  File "/pf/a/a270073/.local/lib/python3.6/site-packages/esm_parser/esm_parser.py", line 1767, in find_variable
    var_result, var_attrs = actually_find_variable(tree, var, full_config)
  File "/pf/a/a270073/.local/lib/python3.6/site-packages/esm_parser/esm_parser.py", line 1839, in actually_find_variable
    var_result = recursive_get(full_config, config_elements)
  File "/pf/a/a270073/.local/lib/python3.6/site-packages/esm_parser/esm_parser.py", line 1732, in recursive_get
    return recursive_get(result, my_config_elements)
  File "/pf/a/a270073/.local/lib/python3.6/site-packages/esm_parser/esm_parser.py", line 1718, in recursive_get
    logging.debug("Incoming config elements: %s", config_elements)
  File "/sw/rhel6-x64/conda/anaconda3-bleeding_edge/lib/python3.6/logging/__init__.py", line 1912, in debug
    root.debug(msg, *args, **kwargs)
  File "/sw/rhel6-x64/conda/anaconda3-bleeding_edge/lib/python3.6/logging/__init__.py", line 1295, in debug
    if self.isEnabledFor(DEBUG):
  File "/sw/rhel6-x64/conda/anaconda3-bleeding_edge/lib/python3.6/logging/__init__.py", line 1548, in isEnabledFor
    if self.manager.disable >= level:
RecursionError: maximum recursion depth exceeded in comparison
```

esm_tools
├─ version: 5.1.1
├─ path: /mnt/lustre01/pf/a/a270073/esm/esm_tools
├─ branch: fesom2-mistral-config
└─ tags: v5.1.1-1-g4120f7d-dirty

**Comment by dbarbi** [comment]
Hi Chris, 
the problem is that you are trying to do:
pool_dir: ${pool_dir}/blabla
That would be perfectly Ok in a shell language, but here it leads to a recursive function trying to resolve that without conflict. The way to resolve that is to use different variable names, like so:
actual_pool_dir:${pool_dir}/blabla
or 
pool_dir: ${base_pool_dir}/blabla

**Comment by chrisdane** [comment]
Ok but pool_dir is already defined earlier:
```
pool_dir: ${computer.pool_directories.pool}
climate_data_dir: "${pool_dir}/hydrography/"
forcing_data_dir: "${pool_dir}/forcing/"
ini_data_dir: "${pool_dir}/pool-data/"
choose_computer.name:
  mistral:
    pool_dir: "${pool_dir}/AWICM/FESOM2"
    climate_data_dir: "${pool_dir}/INITIAL/phc3.0/" # variable for different initial data needed?
    forcing_data_dir: "${pool_dir}/FORCING/"
```
this is not possible? Is this a limitation of yaml or pyhton or what? Maybe this information could be included in `docs/yaml.rst`.
