### ISSUE TITLE
esm_master no_motd 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by mandresm** [esm-tools/esm_tools#343]
**Describe the bug**
Bug occurs when running `esm_master install-<model>`
```
esm_master install-awiesm-2.1
************************************************************************************
Message found for package esm_tools version 5.0.12:

"The new minor release 5.1 is now available!
This minor release include no new models or couple setups but new features to the following packages:
    - esm_master
    - esm_parser
    - esm_environment
    - esm_rcfiles
    - esm_version_checker
    - esm_tools
To get this updates simply run 'esm_versions upgrade'.

NOTE TO DEVELOPERS AND ADVANCE USERS: if you intend to use an branch of 'esm_tools' that is not 'release'
you might face conflicts with the new 'esm_environment'. These conflicts are easily solved by copying the
new machine files into your 'esm_tools' branch (make sure you commit the changes in your branch before
copying the machine files over). Feel free to contact us if you need any assistance with this issue.
"

Upgrade this package by typing:              esm_versions upgrade esm_tools
Upgrade all packages by typing:              esm_versions upgrade
************************************************************************************
Traceback (most recent call last):
  File "/home/ollie/mandresm/.local/bin/esm_master", line 8, in <module>
    sys.exit(main())
  File "/home/ollie/mandresm/.local/lib/python3.7/site-packages/esm_master/cli.py", line 111, in main
    main_flow(parsed_args, target)
  File "/home/ollie/mandresm/.local/lib/python3.7/site-packages/esm_master/esm_master.py", line 56, in main_flow
    complete_setup = SimulationSetup(user_config=user_config)
  File "/home/ollie/mandresm/esm_runscripts/esm_runscripts/sim_objects.py", line 37, in __init__
    if command_line_config["no_motd"]:
TypeError: 'NoneType' object is not subscriptable
```

**Expected behavior**
It should work with `esm_master` command without any additional flag.

**System (please complete the following information):**
 - Supercomputer: any
 - Version 
``` 
+---------------------+-----------+---------------------------------------------------------+----------------------------------+----------------------+
| package_name        | version   | file                                                    | branch                           | tags                 |
|---------------------+-----------+---------------------------------------------------------+----------------------------------+----------------------|
| esm_archiving       | 5.0.0     | /home/ollie/mandresm/.local/lib/python3.7/site-packages |                                  |                      |
| esm_calendar        | 5.0.0     | /home/ollie/mandresm/.local/lib/python3.7/site-packages |                                  |                      |
| esm_database        | 5.0.0     | /home/ollie/mandresm/.local/lib/python3.7/site-packages |                                  |                      |
| esm_environment     | 5.1.0     | /home/ollie/mandresm/.local/lib/python3.7/site-packages |                                  |                      |
| esm_master          | 5.1.1     | /home/ollie/mandresm/.local/lib/python3.7/site-packages |                                  |                      |
| esm_motd            | 5.0.2     | /home/ollie/mandresm/.local/lib/python3.7/site-packages |                                  |                      |
| esm_parser          | 5.1.3     | /home/ollie/mandresm/.local/lib/python3.7/site-packages |                                  |                      |
| esm_plugin_manager  | 5.0.1     | /home/ollie/mandresm/.local/lib/python3.7/site-packages |                                  |                      |
| esm_profile         | 5.0.0     | /home/ollie/mandresm/.local/lib/python3.7/site-packages |                                  |                      |
| esm_rcfile          | 5.1.0     | /home/ollie/mandresm/.local/lib/python3.7/site-packages |                                  |                      |
| esm_runscripts      | 5.1.10    | /home/ollie/mandresm/esm_runscripts                     | release                          | v5.1.10-1-gfc7299e   |
| esm_tools           | 5.1.0     | /home/ollie/mandresm/esm_tools                          | feature/awicm3_prep_merge_geomar | v5.0.12-220-g3c85578 |
| esm_version_checker | 5.1.3     | /home/ollie/mandresm/.local/lib/python3.7/site-packages |                                  |                      |
+---------------------+-----------+---------------------------------------------------------+----------------------------------+----------------------+
```

**Comment by denizural** [comment]
https://github.com/esm-tools/esm_runscripts/pull/128 should solve this.
