### ISSUE TITLE
problems installing awiesm-2.1-wiso

### ISSUE THREAD

**Issue by ackerlar** [esm-tools/esm_tools#345]
**Describe the bug**
I cannot install or download awiesm-2.1-wiso or awiesm-2.1-recom via `esm_master get-awiesm-2.1-wiso`
This is the error I get:
```
ERROR: YAML syntax
------------------

The general ``add_export_vars`` and ``add_`` in ``choose_`` are not compatible in /pf/a/a270124/esm_tools/configs/components/pism/pism.compiletime_env_changes.yaml:
    - choose_computer.name.ollie.environment_changes.add_export_vars
    - choose_computer.name.mistral.environment_changes.add_export_vars

Note that multiple ``add_<variable>`` in a single file are compatible as long as they are included inside ``choose_`` blocks. An ``add_<variable>`` out of a ``choose_`` block and the same ``add_<variable>`` inside of a ``choose_`` block are considered incompatible. If the general ``add_<variable>`` should be added as a default, please include it to ``<variable>`` instead.

```

When commenting out the `add_export_vars` section in `configs/components/pism/pism.compiletime_env_changes.yaml`, I still get this error:
```
Traceback (most recent call last):
  File "/pf/a/a270124/.local/bin/esm_master", line 8, in <module>
    sys.exit(main())
  File "/pf/a/a270124/.local/lib/python3.6/site-packages/esm_master/cli.py", line 76, in main
    main_flow(parsed_args, target)
  File "/pf/a/a270124/.local/lib/python3.6/site-packages/esm_master/esm_master.py", line 36, in main_flow
    complete_setup = SimulationSetup(user_config=user_config)
  File "/mnt/lustre01/pf/a/a270124/esm_runscripts/esm_runscripts/sim_objects.py", line 37, in __init__
    if command_line_config["no_motd"]:
TypeError: 'NoneType' object is not subscriptable
```

**System (please complete the following information):**
 - Supercomputer: mistral
 - Version
 ```
+---------------------+-------------+---------------------------------------------------------------+----------+--------------------+
| package_name        | version     | file                                                          | branch   | tags               |
|---------------------+-------------+---------------------------------------------------------------+----------+--------------------|
| esm_analysis        | 0.4.2       | /mnt/lustre01/pf/a/a270124/esm_analysis                       |          |                    |
| esm_calendar        | 5.0.0       | /mnt/lustre01/pf/a/a270124/.local/lib/python3.6/site-packages |          |                    |
| esm_database        | 5.0.0       | /mnt/lustre01/pf/a/a270124/.local/lib/python3.6/site-packages |          |                    |
| esm_environment     | 5.0.0       | /mnt/lustre01/pf/a/a270124/.local/lib/python3.6/site-packages |          |                    |
| esm_master          | 5.0.1       | /mnt/lustre01/pf/a/a270124/.local/lib/python3.6/site-packages |          |                    |
| esm_motd            | 5.0.1       | /mnt/lustre01/pf/a/a270124/.local/lib/python3.6/site-packages |          |                    |
| esm_parser          | 5.0.2       | /mnt/lustre01/pf/a/a270124/.local/lib/python3.6/site-packages |          |                    |
| esm_pism            | 0.0.1.dev14 | /mnt/lustre01/pf/a/a270124/.local/lib/python3.6/site-packages |          |                    |
| esm_plugin_manager  | 5.0.0       | /mnt/lustre01/pf/a/a270124/.local/lib/python3.6/site-packages |          |                    |
| esm_profile         | 5.0.0       | /mnt/lustre01/pf/a/a270124/.local/lib/python3.6/site-packages |          |                    |
| esm_rcfile          | 5.1.0       | /mnt/lustre01/pf/a/a270124/esm_rcfile                         | release  | v5.1.0             |
| esm_runscripts      | 5.1.10      | /mnt/lustre01/pf/a/a270124/esm_runscripts                     | release  | v5.1.10-1-gfc7299e |
| esm_tools           | 5.1.0       | /mnt/lustre01/pf/a/a270124/esm_tools                          | wiso     | v5.1.0-10-g847d394 |
| esm_version_checker | 5.1.1       | /mnt/lustre01/pf/a/a270124/.local/lib/python3.6/site-packages |          |                    |
+---------------------+-------------+---------------------------------------------------------------+----------+--------------------+
```

**Additional context**

**Comment by mandresm** [comment]
The second error was solved for a newer version of `esm_runscripts`. Could please pull from `esm_runscrtipts` and `esm_rcfile` and do an `esm_versions upgrade`?

**Comment by ackerlar** [comment]
Thank you for the fast reply! Is there a way to "freeze" my current `esm_tools` setup? It's working fine besides the mentioned error and I am bit afraid to mess up anything with the upgrading...

**Comment by mandresm** [comment]
The second error should be solved by pulling in `esm_runscripts` so in principle you should be fine just with that without having to do `esm_versions` upgrade.

**Comment by ackerlar** [comment]
After the pull I get this error:
```
a270124@mlogin105% esm_master get-awiesm-2.1-wiso
Traceback (most recent call last):
  File "/pf/a/a270124/.local/bin/esm_master", line 8, in <module>
    sys.exit(main())
  File "/pf/a/a270124/.local/lib/python3.6/site-packages/esm_master/cli.py", line 76, in main
    main_flow(parsed_args, target)
  File "/pf/a/a270124/.local/lib/python3.6/site-packages/esm_master/esm_master.py", line 36, in main_flow
    complete_setup = SimulationSetup(user_config=user_config)
  File "/mnt/lustre01/pf/a/a270124/esm_runscripts/esm_runscripts/sim_objects.py", line 47, in __init__
    self.config = prepare.run_job(self.config)
  File "/mnt/lustre01/pf/a/a270124/esm_runscripts/esm_runscripts/prepare.py", line 6, in run_job
    helpers.evaluate(config, "prepare", "prepare_recipe")
  File "/mnt/lustre01/pf/a/a270124/esm_runscripts/esm_runscripts/helpers.py", line 101, in evaluate
    framework_recipe, framework_plugins, config
  File "/pf/a/a270124/.local/lib/python3.6/site-packages/esm_plugin_manager/esm_plugin_manager.py", line 130, in work_through_recipe
    config = getattr(submodule, workitem)(config)
  File "/mnt/lustre01/pf/a/a270124/esm_runscripts/esm_runscripts/prepare.py", line 645, in finalize_config
    config.finalize()
  File "/pf/a/a270124/.local/lib/python3.6/site-packages/esm_parser/esm_parser.py", line 2629, in finalize
    self.run_recursive_functions(self)
  File "/pf/a/a270124/.local/lib/python3.6/site-packages/esm_parser/esm_parser.py", line 2635, in run_recursive_functions
    recursive_run_function([], config, "atomic", mark_dates, config)
  File "/pf/a/a270124/.local/lib/python3.6/site-packages/esm_parser/esm_parser.py", line 1553, in recursive_run_function
    tree + [key], value, level, func, *args, **kwargs
  File "/pf/a/a270124/.local/lib/python3.6/site-packages/esm_parser/esm_parser.py", line 1553, in recursive_run_function
    tree + [key], value, level, func, *args, **kwargs
  File "/pf/a/a270124/.local/lib/python3.6/site-packages/esm_parser/esm_parser.py", line 1553, in recursive_run_function
    tree + [key], value, level, func, *args, **kwargs
  [Previous line repeated 487 more times]
  File "/pf/a/a270124/.local/lib/python3.6/site-packages/esm_parser/esm_parser.py", line 1551, in recursive_run_function
    value = right[key]
  File "/mnt/lustre01/pf/a/a270124/esm_runscripts/esm_runscripts/sim_objects.py", line 346, in __getitem__
    value = PrevRunInfo(prev_config=self._prev_config)
RecursionError: maximum recursion depth exceeded
```

**Comment by mandresm** [comment]
There were a number of bugs fixed this week in different packages. i would strongly suggest you to do `esm_versions upgrade`. Release branches should be relatively stable, at least as you remain inside minor release numbers (5.1 in this case) and the 3rd number are only bug fixes so you probably want them anyway.

**Comment by mandresm** [comment]
I actually take back what I said, I've seen you have many packages in release 5.0. Better not to upgrade right now.

**Comment by mandresm** [comment]
Dear @ackerlar , can this issue be closed now, or are you still confronting problems?

**Comment by ackerlar** [comment]
@mandresm Yes, I close this issue!
