### ISSUE TITLE
recompiling fesom2.0  using the new branch pico_cpl fails

### ISSUE THREAD

**Issue by gknorr** [esm-tools/esm_tools#354]
Dear All,

I try to run the new fesom2.0 version pico_cpl: https://github.com/FESOM/fesom2/tree/pico_cpl

On mistral in folder /work/ba0989/a270083/model_codes/fesom-2.0

I execute the following commands esm_tool version 5.0.8:
 

$ git remote set-url origin https://github.com/FESOM/fesom2.git
$ git  fetch   
$ git checkout pico_cpl   
$ cd ..
$ esm_master recomp-fesom-2.0

During the recompilation I receive the following error message:

[ 30%] Linking C static library libparms.a
[ 30%] Built target parms
make: *** [all] Error 2
Traceback (most recent call last):
  File "/pf/a/a270083/.local/bin/esm_master", line 8, in <module>
    sys.exit(main())
  File "/pf/a/a270083/.local/lib/python3.6/site-packages/esm_master/cli.py", line 76, in main
    main_flow(parsed_args, target)
  File "/pf/a/a270083/.local/lib/python3.6/site-packages/esm_master/esm_master.py", line 52, in main_flow
    user_task.execute() #env)
  File "/pf/a/a270083/.local/lib/python3.6/site-packages/esm_master/task.py", line 449, in execute
    shell=(command.startswith("./") and command.endswith(".sh")),
  File "/sw/rhel6-x64/conda/anaconda3-bleeding_edge/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['./comp-fesom-2.0_script.sh']' returned non-zero exit status 2.

Best regards,

Gregor

**Comment by dbarbi** [comment]
Not an ESM-Tools problem. Compilation of normal fesom-2.0 tag 2.0.2 works, pico_cpl is not supported. I also get a compilation error for pico_cpl and for master. Something in the fesom code probably

**Comment by dbarbi** [comment]
Ok, compilation of pico_cpl works using fesom build stack, which is the same as esm-tools except for some environment settings

**Comment by gknorr** [comment]
Would it be possible to align these settings?

**Comment by dbarbi** [comment]
i am looking into it. until then you can still compile using the fesom build system, which is basically what esm_tools is doing anyway

**Comment by gknorr** [comment]
okay - thanks!

**Comment by dbarbi** [comment]
ok, just pushed a patch that includes support for pico_cpl. please 'git pull' the latest version (5.1.7) of esm_tools. Then you can use
esm_master install-fesom-2.0pico 
to get what you wanted

**Comment by gknorr** [comment]
shall  I perform:

esm_versions upgrade

?

**Comment by dbarbi** [comment]
for example. or:
esm_versions upgrade esm_tools
or:
cd your_path_to_esm_tools; git pull

**Comment by gknorr** [comment]
nice

**Comment by gknorr** [comment]
I did successfully cd your_path_to_esm_tools; git pull

and now have the following problem after the command: esm_master install-fesom-2.0

Traceback (most recent call last):
  File "/pf/a/a270083/.local/bin/esm_master", line 8, in <module>
    sys.exit(main())
  File "/pf/a/a270083/.local/lib/python3.6/site-packages/esm_master/cli.py", line 76, in main
    main_flow(parsed_args, target)
  File "/pf/a/a270083/.local/lib/python3.6/site-packages/esm_master/esm_master.py", line 36, in main_flow
    complete_setup = SimulationSetup(user_config=user_config)
  File "/pf/a/a270083/.local/lib/python3.6/site-packages/esm_runscripts/sim_objects.py", line 42, in __init__
    self.config = prepare.run_job(self.config)
  File "/pf/a/a270083/.local/lib/python3.6/site-packages/esm_runscripts/prepare.py", line 5, in run_job
    helpers.evaluate(config, "prepare", "prepare_recipe")
  File "/pf/a/a270083/.local/lib/python3.6/site-packages/esm_runscripts/helpers.py", line 69, in evaluate
    framework_recipe, framework_plugins, config
  File "/pf/a/a270083/.local/lib/python3.6/site-packages/esm_plugin_manager/esm_plugin_manager.py", line 129, in work_through_recipe
    submodule = getattr(thismodule, plugins[workitem]["submodule"])
AttributeError: module 'esm_runscripts' has no attribute 'last_minute'

**Comment by gknorr** [comment]
esm_versions upgrade

hat das problem behoben

**Comment by dbarbi** [comment]
Ja, da war dann der Rest der ESM-Tools älter als 5.1.0. Passte dann nicht mehr zu den Config Dateien. Gut wenn es jetzt funktioniert.
