### ISSUE TITLE
Implementation histvolcanir not found for filetype forcing of model echam

### ISSUE THREAD

**Issue by chrisdane** [esm-tools/esm_tools#379]
Hi

On mistral, running 
```
esm_runscripts /pf/a/a270073/esm/runscripts/awicm_recom_hist_run.yaml --verbose --open-run -e historical
```
yields
```
========================================================================
::: Executing the step:  assemble    (step [12/22] of the job:  compute)
========================================================================
Implementation histvolcanir not found for filetype forcing of model echam
{'aerocoarse': 'piaerocoarse', 'aerofarir': 'piaerofarir', 'aerofin': 'histaerofin', 'ozone': 'histozone', 'greenhouse': 'histgreenh', 'volcanir': 'histvolcanir', 'volcsw': 'histvolcsw', 'swflux': 'histswflux'}<br>
{'amipsst': {'/pool/data/ECHAM6/input/r0007/T63/amip/T63_amipsst_@YEAR@.nc': {'from': 1870, 'to': 2016}}, 'pisst': '/pool/data/ECHAM6/input/r0007/T63/T63CORE2_piControl-LR_sst_1880-2379.nc', 'amipsic': {'/pool/data/ECHAM6/input/r0007/T63/amip/T63_amipsic_@YEAR@.nc': {'from': 1870, 'to': 2016}}, 'pisic': '/pool/data/ECHAM6/input/r0007/T63/T63CORE2_piControl-LR_sic_1880-2379.nc', 'piaerocoarse': '/pool/data/ECHAM6/input/r0007/T63/aero/T63_aeropt_kinne_sw_b14_coa.nc', 'piaerofarir': '/pool/data/ECHAM6/input/r0007/T63/aero/T63_aeropt_kinne_lw_b16_coa.nc', 'histaerofin': {'/pool/data/ECHAM6/input/r0007/T63/aero/T63_aeropt_kinne_sw_b14_fin_1865.nc': {'to': 1864}, '/pool/data/ECHAM6/input/r0007/T63/aero/T63_aeropt_kinne_sw_b14_fin_@YEAR@.nc': {'from': 1865, 'to': 2000}}, 'piaerofin': '/pool/data/ECHAM6/input/r0007/T63/aero/T63_aeropt_kinne_sw_b14_fin_1865.nc', 'histvolcir': {'/pool/data/ECHAM6/input/r0007/T63/volcano_aerosols/strat_aerosol_ir_T63_1850.nc': {'to': 1850}, '/pool/data/ECHAM6/input/r0007/T63/volcano_aerosols/strat_aerosol_ir_T63_@YEAR@.nc': {'from': 1851, 'to': 2014}, '/pool/data/ECHAM6/input/r0007/T63/volcano_aerosols/strat_aerosol_ir_T63_2014.nc': {'from': 2015}}, 'histvolcsw': {'/pool/data/ECHAM6/input/r0007/T63/volcano_aerosols/strat_aerosol_sw_T63_1850.nc': {'to': 1850}, '/pool/data/ECHAM6/input/r0007/T63/volcano_aerosols/strat_aerosol_sw_T63_@YEAR@.nc': {'from': 1851, 'to': 2014}, '/pool/data/ECHAM6/input/r0007/T63/volcano_aerosols/strat_aerosol_sw_T63_2014.nc': {'from': 2015}}, 'histgreenh': '/pool/data/ECHAM6/input/r0007/T63/greenhouse_historical.nc', '1percCO2greenh': '/pool/data/ECHAM6/input/r0007/T63/greenhouse_1pctCO2.nc', 'histswflux': {'/pool/data/ECHAM6/input/r0007/solar_irradiance/swflux_14band_1850.nc': {'to': 1850}, '/pool/data/ECHAM6/input/r0007/solar_irradiance/swflux_14band_@YEAR@.nc': {'from': 1851}}, 'histozone': {'/pool/data/ECHAM6/input/r0007/T63/ozone/T63_ozone_historical_1850.nc': {'to': 1850}, '/pool/data/ECHAM6/input/r0007/T63/ozone/T63_ozone_historical_@YEAR@.nc': {'from': 1851, 'to': 2008}}, '1850ozone': '/pool/data/ECHAM6/input/r0007/T63/ozone/T63_ozone_historical_1850.nc', '1950ozone': '/pool/data/ECHAM6/input/r0007/T63/ozone/T63_ozone_historical_1950.nc', 'piozone': '/pool/data/ECHAM6/input/r0007/T63/ozone/T63_ozone_picontrol.nc'}
2021-07-04 15:57:37.392102
Exiting entire Python process!
```
The same happens with `-c`.

This experiment shall be a branching off and redate experiment to start a historical run.

Thanks a lot for help!
Chris

<details>
<summary>esm_versions check</summary>

```
esm_analysis
├─ version: 0.3.0
├─ path: /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages
├─ branch: 
└─ tags: 

esm_archiving
├─ version: 0.1.0
├─ path: /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages
├─ branch: 
└─ tags: 

esm_calendar
├─ version: 5.0.0
├─ path: /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages
├─ branch: 
└─ tags: 

esm_database
├─ version: 5.0.0
├─ path: /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages
├─ branch: 
└─ tags: 

esm_environment
├─ version: 5.1.0
├─ path: /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages
├─ branch: 
└─ tags: 

esm_master
├─ version: 5.1.2
├─ path: /mnt/lustre01/pf/a/a270073/esm/src/esm_master
├─ branch: release
└─ tags: v5.1.2-1-gf5196ac

esm_motd
├─ version: 5.0.2
├─ path: /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages
├─ branch: 
└─ tags: 

esm_parser
├─ version: 5.1.5
├─ path: /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages
├─ branch: 
└─ tags: 

esm_plugin_manager
├─ version: 5.0.1
├─ path: /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages
├─ branch: 
└─ tags: 

esm_profile
├─ version: 5.0.0
├─ path: /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages
├─ branch: 
└─ tags: 

esm_rcfile
├─ version: 5.1.0
├─ path: /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages
├─ branch: 
└─ tags: 

esm_runscripts
├─ version: 5.1.12
├─ path: /mnt/lustre01/pf/a/a270073/esm/src/esm_runscripts
├─ branch: release
└─ tags: v5.1.12-1-g5d9fa0b

esm_tools
├─ version: 5.1.0
├─ path: /mnt/lustre01/pf/a/a270073/esm/esm_tools
├─ branch: awicm_recom
└─ tags: v5.0.17-63-ge46ff3f

esm_version_checker
├─ version: 5.1.4
├─ path: /mnt/lustre01/pf/a/a270073/esm/src/esm_version_checker
├─ branch: release
└─ tags: v5.1.4
```
</details>

**Comment by denizural** [comment]
Hi @chrisdane, I made quite a number of changes to historical runs but they are on a different branch (`esm_tools` and `esm_runscripts`). The main changes are on using more advanced aerosol schemes (iaero=9). They are not merged yet and I need to talk to Echam experts like @pgierz. However you can use the `hist_fixed` branch for the time being.

**Comment by chrisdane** [comment]
Hi Deniz

With `esm_runscripts` branch `hist_fixed`:
```
| esm_runscripts      | 5.1.12    | /mnt/lustre01/pf/a/a270073/esm/src/esm_runscripts             | DETACHED at cb36307 | v5.0.17-76-gcb36307       |
```
the same error occurs.

When I additionally change 
```
--- a/configs/components/echam/echam.yaml
+++ b/configs/components/echam/echam.yaml
-                        volcanir: histvolcanir
+                        #volcanir: histvolcanir
+                        volcanir: histvolcir
```
as in the `esm_tools` branch `hotfix/echam_volcan`, the error changes to 
```
========================================================================
::: Executing the step:  assemble    (step [12/22] of the job:  compute)
========================================================================
...
Renaming sources to targets for filetype ignore in model echam
Renaming sources to targets for filetype ignore in model fesom
Renaming sources to targets for filetype ignore in model jsbach
Traceback (most recent call last):
  File "/pf/a/a270073/.local/bin/esm_runscripts", line 11, in <module>
    load_entry_point('esm-runscripts', 'console_scripts', 'esm_runscripts')()
  File "/mnt/lustre01/pf/a/a270073/esm/src/esm_runscripts/esm_runscripts/cli.py", line 202, in main
    Setup()
  File "/mnt/lustre01/pf/a/a270073/esm/src/esm_runscripts/esm_runscripts/sim_objects.py", line 50, in __call__
    self.compute(*args, **kwargs)
  File "/mnt/lustre01/pf/a/a270073/esm/src/esm_runscripts/esm_runscripts/sim_objects.py", line 84, in compute
    self.config = compute.run_job(self.config)
  File "/mnt/lustre01/pf/a/a270073/esm/src/esm_runscripts/esm_runscripts/compute.py", line 32, in run_job
    config = evaluate(config, "compute", "compute_recipe")
  File "/mnt/lustre01/pf/a/a270073/esm/src/esm_runscripts/esm_runscripts/helpers.py", line 49, in evaluate
    framework_recipe, framework_plugins, config
  File "/pf/a/a270073/.local/lib/python3.6/site-packages/esm_plugin_manager/esm_plugin_manager.py", line 138, in work_through_recipe
    config = getattr(submodule, workitem)(config)
  File "/mnt/lustre01/pf/a/a270073/esm/src/esm_runscripts/esm_runscripts/filelists.py", line 892, in assemble
    config = complete_targets(config)
  File "/mnt/lustre01/pf/a/a270073/esm/src/esm_runscripts/esm_runscripts/filelists.py", line 126, in complete_targets
    config[model][filetype + "_sources"][categ]
  File "/sw/rhel6-x64/conda/anaconda3-bleeding_edge/lib/python3.6/posixpath.py", line 146, in basename
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not dict
```

**Comment by pgierz** [comment]
Wait since when am I an echam expert?

**Comment by pgierz** [comment]
Alright, I need a bit of info to get going. Please confirm

- Machine: mistral
- Model: awiesm 2? Echam only?
- Scenario: historic?
- Missing files: volcano forcing? 

Sounds like a pool issue once again

**Comment by chrisdane** [comment]
Thanks Paul

- machine: mistral
- model: /pf/a/a270073/esm/awicm-1.0-recom
- scenario: historical
- missing files: I dont know if the issue are missing files. There are only the errors above.

**Comment by pgierz** [comment]
You never needed to change echam for recom, right?

**Comment by chrisdane** [comment]
You mean changes after the
```
esm_master install-awicm-1.0-recom
```
command? No.

**Comment by pgierz** [comment]
OK, I'm using the release branch as a basis. The problem is in the `echam.datasets.yaml` file. You will need to add a new block there for `histvolcanir` files, yet I do not know which ones need to actually be there. You can use the other ones as a template.

I also can't cleanly reproduce everything, I don't have recom access.

For whoever wants to work on this next, all of my stuff is here:
/work/ab0246/a270077/For_Chris

**Comment by pgierz** [comment]
@chrisdane, can you ask the recom crew to give me access? Just for future.....

**Comment by dbarbi** [comment]
If I see that correctly, then it is just a type in echam.datasets.yaml. It should be histvolcanir, not histvolcir. I will bugfix that now into release, develop and prep_release. Does it work in the hist branches?

**Comment by denizural** [comment]
@dbarbi, I have that covered. I should get into the release.

**Comment by dbarbi** [comment]
just pushed it

**Comment by ackerlar** [comment]
I am trying to run a historical simulation and I have got the same error as @chrisdane got before:
```
Traceback (most recent call last):
  File "/pf/a/a270124/.local/bin/esm_runscripts", line 11, in <module>
    load_entry_point('esm-runscripts', 'console_scripts', 'esm_runscripts')()
  File "/mnt/lustre01/pf/a/a270124/esm_runscripts/esm_runscripts/cli.py", line 202, in main
    Setup()
  File "/mnt/lustre01/pf/a/a270124/esm_runscripts/esm_runscripts/sim_objects.py", line 50, in __call__
    self.compute(*args, **kwargs)
  File "/mnt/lustre01/pf/a/a270124/esm_runscripts/esm_runscripts/sim_objects.py", line 84, in compute
    self.config = compute.run_job(self.config)
  File "/mnt/lustre01/pf/a/a270124/esm_runscripts/esm_runscripts/compute.py", line 32, in run_job
    config = evaluate(config, "compute", "compute_recipe")
  File "/mnt/lustre01/pf/a/a270124/esm_runscripts/esm_runscripts/helpers.py", line 49, in evaluate
    framework_recipe, framework_plugins, config
  File "/pf/a/a270124/.local/lib/python3.6/site-packages/esm_plugin_manager/esm_plugin_manager.py", line 138, in work_through_recipe
    config = getattr(submodule, workitem)(config)
  File "/mnt/lustre01/pf/a/a270124/esm_runscripts/esm_runscripts/filelists.py", line 892, in assemble
    config = complete_targets(config)
  File "/mnt/lustre01/pf/a/a270124/esm_runscripts/esm_runscripts/filelists.py", line 126, in complete_targets
    config[model][filetype + "_sources"][categ]
  File "/sw/rhel6-x64/conda/anaconda3-bleeding_edge/lib/python3.6/posixpath.py", line 146, in basename
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not dict
```
I have tried `release`, `hotfix/echam_volcan` and `hist_fixed` for `esm_tools` and `esm_runscripts`, respectively. 

On `prep_release`, I get this error:
```
all_years =  [1850, 1849, 1851]
file_category =  aerocoarse
config[model] =  /pool/data/ECHAM6/input/r0007/T63/aero/T63_aeropt_kinne_sw_b14_coa.nc
all_years =  [1850, 1849, 1851]
file_category =  aerocoarse
config[model] =  /pool/data/ECHAM6/input/r0007/T63/aero/T63_aeropt_kinne_sw_b14_coa.nc
all_years =  [1850, 1849, 1851]
file_category =  aerocoarse
config[model] =  /pool/data/ECHAM6/input/r0007/T63/aero/T63_aeropt_kinne_sw_b14_coa.nc
all_years =  [1850, 1849, 1851]
file_category =  aerofin
config[model] =  {'/pool/data/ECHAM6/input/r0007/T63/aero/T63_aeropt_kinne_sw_b14_fin_1865.nc': {'to': 1864}, '/pool/data/ECHAM6/input/r0007/T63/aero/T63_aeropt_kinne_sw_b14_fin_@YEAR@.nc': {'from': 1865, 'to': 2000}}
Traceback (most recent call last):
  File "/pf/a/a270124/.local/bin/esm_runscripts", line 11, in <module>
    load_entry_point('esm-runscripts', 'console_scripts', 'esm_runscripts')()
  File "/mnt/lustre01/pf/a/a270124/esm_runscripts/esm_runscripts/cli.py", line 229, in main
    Setup()
  File "/mnt/lustre01/pf/a/a270124/esm_runscripts/esm_runscripts/sim_objects.py", line 61, in __call__
    self.prepcompute()
  File "/mnt/lustre01/pf/a/a270124/esm_runscripts/esm_runscripts/sim_objects.py", line 153, in prepcompute
    self.config = prepcompute.run_job(self.config)
  File "/mnt/lustre01/pf/a/a270124/esm_runscripts/esm_runscripts/prepcompute.py", line 36, in run_job
    config = evaluate(config, "prepcompute", "prepcompute_recipe")
  File "/mnt/lustre01/pf/a/a270124/esm_runscripts/esm_runscripts/helpers.py", line 58, in evaluate
    framework_recipe, framework_plugins, config
  File "/pf/a/a270124/.local/lib/python3.6/site-packages/esm_plugin_manager/esm_plugin_manager.py", line 138, in work_through_recipe
    config = getattr(submodule, workitem)(config)
  File "/mnt/lustre01/pf/a/a270124/esm_runscripts/esm_runscripts/filelists.py", line 857, in assemble
    config = replace_year_placeholder(config)
  File "/mnt/lustre01/pf/a/a270124/esm_runscripts/esm_runscripts/filelists.py", line 476, in replace_year_placeholder
    ][file_category].replace("@YEAR@", str(year))
AttributeError: 'dict' object has no attribute 'replace'
```

 Is there a fix for it I didn't recognize?

**Comment by denizural** [comment]
Hi @ackerlar, did I get it correctly that you tried with `hist_fixed` branch in `esm_runscripts`?

**Comment by ackerlar** [comment]
Yes, I also tried `hist_fixed` in `esm_runscripts`:

```
sm_versions check
+---------------------+-------------+---------------------------------------------------------------+------------+---------------------+
| package_name        | version     | file                                                          | branch     | tags                |
|---------------------+-------------+---------------------------------------------------------------+------------+---------------------|
| esm_calendar        | 5.0.0       | /mnt/lustre01/pf/a/a270124/.local/lib/python3.6/site-packages |            |                     |
| esm_database        | 5.0.0       | /mnt/lustre01/pf/a/a270124/.local/lib/python3.6/site-packages |            |                     |
| esm_environment     | 5.1.1       | /mnt/lustre01/pf/a/a270124/.local/lib/python3.6/site-packages |            |                     |
| esm_master          | 5.1.3       | /mnt/lustre01/pf/a/a270124/.local/lib/python3.6/site-packages |            |                     |
| esm_motd            | 5.0.2       | /mnt/lustre01/pf/a/a270124/.local/lib/python3.6/site-packages |            |                     |
| esm_parser          | 5.1.7       | /mnt/lustre01/pf/a/a270124/.local/lib/python3.6/site-packages |            |                     |
| esm_pism            | 0.0.1.dev15 | /mnt/lustre01/pf/a/a270124/.local/lib/python3.6/site-packages | main       | Error               |
| esm_plugin_manager  | 5.0.1       | /mnt/lustre01/pf/a/a270124/.local/lib/python3.6/site-packages |            |                     |
| esm_profile         | 5.0.0       | /mnt/lustre01/pf/a/a270124/.local/lib/python3.6/site-packages |            |                     |
| esm_rcfile          | 5.1.0       | /mnt/lustre01/pf/a/a270124/.local/lib/python3.6/site-packages |            |                     |
| esm_runscripts      | 5.0.17      | /mnt/lustre01/pf/a/a270124/esm_runscripts                     | hist_fixed | v5.0.17-76-gcb36307 |
| esm_tools           | 5.1.17      | /mnt/lustre01/pf/a/a270124/esm_tools                          | release    | v5.1.17-3-g8a4ff20  |
| esm_version_checker | 5.1.5       | /mnt/lustre01/pf/a/a270124/.local/lib/python3.6/site-packages |            |                     |
+---------------------+-------------+---------------------------------------------------------------+------------+---------------------+
```

With this error occuring:
```
Traceback (most recent call last):
  File "/pf/a/a270124/.local/bin/esm_runscripts", line 11, in <module>
    load_entry_point('esm-runscripts', 'console_scripts', 'esm_runscripts')()
  File "/mnt/lustre01/pf/a/a270124/esm_runscripts/esm_runscripts/cli.py", line 202, in main
    Setup()
  File "/mnt/lustre01/pf/a/a270124/esm_runscripts/esm_runscripts/sim_objects.py", line 50, in __call__
    self.compute(*args, **kwargs)
  File "/mnt/lustre01/pf/a/a270124/esm_runscripts/esm_runscripts/sim_objects.py", line 84, in compute
    self.config = compute.run_job(self.config)
  File "/mnt/lustre01/pf/a/a270124/esm_runscripts/esm_runscripts/compute.py", line 32, in run_job
    config = evaluate(config, "compute", "compute_recipe")
  File "/mnt/lustre01/pf/a/a270124/esm_runscripts/esm_runscripts/helpers.py", line 49, in evaluate
    framework_recipe, framework_plugins, config
  File "/pf/a/a270124/.local/lib/python3.6/site-packages/esm_plugin_manager/esm_plugin_manager.py", line 138, in work_through_recipe
    config = getattr(submodule, workitem)(config)
  File "/mnt/lustre01/pf/a/a270124/esm_runscripts/esm_runscripts/filelists.py", line 892, in assemble
    config = complete_targets(config)
  File "/mnt/lustre01/pf/a/a270124/esm_runscripts/esm_runscripts/filelists.py", line 126, in complete_targets
    config[model][filetype + "_sources"][categ]
  File "/sw/rhel6-x64/conda/anaconda3-bleeding_edge/lib/python3.6/posixpath.py", line 146, in basename
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not dict
```

**Comment by denizural** [comment]
Ok, I will look at this asap. Could you please provide a path to your runscript

**Comment by ackerlar** [comment]
@denizural thank you! Here is my runscript: `/pf/a/a270124/for_fernanda/run_hist.yaml`

**Comment by ackerlar** [comment]
Sorry, closed the issue accidently...

**Comment by pgierz** [comment]
Hello, I am going through the issues to clean up before we start preparing everything for version 6. Can this one be closed? Lars, is your stuff running now?

**Comment by ackerlar** [comment]
It is not running for me, yet. But maybe there were some updates I am not aware of?

**Comment by JanStreffing** [comment]
Is this solved in release 6?

**Comment by chrisdane** [comment]
Yes
