### ISSUE TITLE
PISM not running on prep_release

### ISSUE THREAD

**Issue by ackerlar** [esm-tools/esm_tools#385]
**Describe the bug**
When I try to run PISM, esm_tools exit with this error:
```
Traceback (most recent call last):
  File "/work/ollie/lackerma/processor-partitioning/.direnv/python-3.7.4/bin/esm_runscripts", line 11, in <module>
    load_entry_point('esm-runscripts', 'console_scripts', 'esm_runscripts')()
  File "/work/ollie/lackerma/processor-partitioning/software/github.com/esm-tools/esm_runscripts/esm_runscripts/cli.py", line 229, in main
    Setup()
  File "/work/ollie/lackerma/processor-partitioning/software/github.com/esm-tools/esm_runscripts/esm_runscripts/sim_objects.py", line 60, in __call__
    self.prepcompute()
  File "/work/ollie/lackerma/processor-partitioning/software/github.com/esm-tools/esm_runscripts/esm_runscripts/sim_objects.py", line 143, in prepcompute
    self.config = prepcompute.run_job(self.config)
  File "/work/ollie/lackerma/processor-partitioning/software/github.com/esm-tools/esm_runscripts/esm_runscripts/prepcompute.py", line 35, in run_job
    config = evaluate(config, "prepcompute", "prepcompute_recipe")
  File "/work/ollie/lackerma/processor-partitioning/software/github.com/esm-tools/esm_runscripts/esm_runscripts/helpers.py", line 50, in evaluate
    framework_recipe, framework_plugins, config
  File "/work/ollie/lackerma/processor-partitioning/software/github.com/esm-tools/esm_plugin_manager/esm_plugin_manager/esm_plugin_manager.py", line 130, in work_through_recipe
    if plugins[workitem]["type"] == "core":
KeyError: 'pism_set_kv_pairs'
```

**Expected behavior**
The PISM job should start.

**System (please complete the following information):**
 - Supercomputer: ollie
 - Version
 ```
+---------------------+-----------+----------------------------------------------------------------------------------------------+--------------+---------------------------+
| package_name        | version   | file                                                                                         | branch       | tags                      |
|---------------------+-----------+----------------------------------------------------------------------------------------------+--------------+---------------------------|
| esm_calendar        | 5.0.0     | /work/ollie/lackerma/processor-partitioning/.direnv/python-3.7.4/lib/python3.7/site-packages |              |                           |
| esm_database        | 5.0.0     | /work/ollie/lackerma/processor-partitioning/.direnv/python-3.7.4/lib/python3.7/site-packages |              |                           |
| esm_environment     | 5.1.1     | /work/ollie/lackerma/processor-partitioning/.direnv/python-3.7.4/lib/python3.7/site-packages |              |                           |
| esm_master          | 5.1.3     | /work/ollie/lackerma/processor-partitioning/.direnv/python-3.7.4/lib/python3.7/site-packages |              |                           |
| esm_motd            | 5.0.2     | /work/ollie/lackerma/processor-partitioning/.direnv/python-3.7.4/lib/python3.7/site-packages |              |                           |
| esm_parser          | 5.1.7     | /work/ollie/lackerma/processor-partitioning/software/github.com/esm-tools/esm_parser         | prep_release | v5.1.7-17-g333f8ec        |
| esm_plugin_manager  | 5.0.0     | /work/ollie/lackerma/processor-partitioning/software/github.com/esm-tools/esm_plugin_manager | vilma        | v5.0.0-1-gc6cb2f7-dirty   |
| esm_profile         | 5.0.0     | /work/ollie/lackerma/processor-partitioning/.direnv/python-3.7.4/lib/python3.7/site-packages |              |                           |
| esm_rcfile          | 5.1.0     | /work/ollie/lackerma/processor-partitioning/.direnv/python-3.7.4/lib/python3.7/site-packages | develop      | v5.1.0                    |
| esm_runscripts      | 5.0.14    | /work/ollie/lackerma/processor-partitioning/software/github.com/esm-tools/esm_runscripts     | prep_release | v5.0.14-48-g120e0c8-dirty |
| esm_tools           | 5.1.9     | /work/ollie/lackerma/processor-partitioning/software/github.com/esm-tools/esm_tools          | prep_release | v5.1.9-37-g0bfa88b-dirty  |
| esm_version_checker | 5.1.4     | /work/ollie/lackerma/processor-partitioning/.direnv/python-3.7.4/lib/python3.7/site-packages |              |                           |
+---------------------+-----------+----------------------------------------------------------------------------------------------+--------------+---------------------------+
```

**Additional context**

**Comment by pgierz** [comment]
Hi Lars, can you send me your runscript? I can look this afternoon.

**Comment by ackerlar** [comment]
@pgierz Here it is: `/work/ollie/lackerma/processor-partitioning/experiments/pism05/scripts/pism-ollie-initial-yearly.yaml`

**Comment by dbarbi** [comment]
Did you install Pauls esm_pism plugin? That is still needed at this time...

**Comment by ackerlar** [comment]
No, it was not installed... It starts now but runs only for one year and gives this error:
```
Traceback (most recent call last):
  File "/work/ollie/lackerma/processor-partitioning/.direnv/python-3.7.4/bin/esm_runscripts", line 11, in <module>
    load_entry_point('esm-runscripts', 'console_scripts', 'esm_runscripts')()
  File "/work/ollie/lackerma/processor-partitioning/software/github.com/esm-tools/esm_runscripts/esm_runscripts/cli.py", line 225, in main
    Setup = SimulationSetup(command_line_config)
  File "/work/ollie/lackerma/processor-partitioning/software/github.com/esm-tools/esm_runscripts/esm_runscripts/sim_objects.py", line 32, in __init__
    self.config = prepare.run_job(self.config)
  File "/work/ollie/lackerma/processor-partitioning/software/github.com/esm-tools/esm_runscripts/esm_runscripts/prepare.py", line 14, in run_job
    helpers.evaluate(config, "prepare", "prepare_recipe")
  File "/work/ollie/lackerma/processor-partitioning/software/github.com/esm-tools/esm_runscripts/esm_runscripts/helpers.py", line 45, in evaluate
    plugins_bare, framework_recipe, need_to_parse_plugins
  File "/work/ollie/lackerma/processor-partitioning/software/github.com/esm-tools/esm_plugin_manager/esm_plugin_manager/esm_plugin_manager.py", line 58, in read_plugin_information
    attach_installed_plugins_to_all(plugins)
  File "/work/ollie/lackerma/processor-partitioning/software/github.com/esm-tools/esm_plugin_manager/esm_plugin_manager/esm_plugin_manager.py", line 73, in attach_installed_plugins_to_all
    plugins.update(find_installed_plugins())
  File "/work/ollie/lackerma/processor-partitioning/software/github.com/esm-tools/esm_plugin_manager/esm_plugin_manager/esm_plugin_manager.py", line 67, in find_installed_plugins
    for entry_point in pkg_resources.iter_entry_points("esm_tools.plugins")
  File "/work/ollie/lackerma/processor-partitioning/software/github.com/esm-tools/esm_plugin_manager/esm_plugin_manager/esm_plugin_manager.py", line 67, in <dictcomp>
    for entry_point in pkg_resources.iter_entry_points("esm_tools.plugins")
  File "/work/ollie/lackerma/processor-partitioning/.direnv/python-3.7.4/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/work/ollie/lackerma/processor-partitioning/.direnv/python-3.7.4/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/work/ollie/lackerma/processor-partitioning/.direnv/python-3.7.4/lib/python3.7/site-packages/gfw_creator/__init__.py", line 9, in <module>
    from .gfw_creator import *
  File "/work/ollie/lackerma/processor-partitioning/.direnv/python-3.7.4/lib/python3.7/site-packages/gfw_creator/gfw_creator.py", line 6, in <module>
    import xarray as xr
  File "/work/ollie/lackerma/processor-partitioning/.direnv/python-3.7.4/lib/python3.7/site-packages/xarray/__init__.py", line 3, in <module>
    from . import testing, tutorial, ufuncs
  File "/work/ollie/lackerma/processor-partitioning/.direnv/python-3.7.4/lib/python3.7/site-packages/xarray/tutorial.py", line 13, in <module>
    from .backends.api import open_dataset as _open_dataset
  File "/work/ollie/lackerma/processor-partitioning/.direnv/python-3.7.4/lib/python3.7/site-packages/xarray/backends/__init__.py", line 9, in <module>
    from .h5netcdf_ import H5NetCDFStore
  File "/work/ollie/lackerma/processor-partitioning/.direnv/python-3.7.4/lib/python3.7/site-packages/xarray/backends/h5netcdf_.py", line 25, in <module>
    from .netCDF4_ import (
  File "/work/ollie/lackerma/processor-partitioning/.direnv/python-3.7.4/lib/python3.7/site-packages/xarray/backends/netCDF4_.py", line 34, in <module>
    import netCDF4
  File "/global/AWIsoft/tkleiner/lib/python2.7/site-packages/netCDF4-1.2.4-py2.7-linux-x86_64.egg/netCDF4/__init__.py", line 3, in <module>
  File "/global/AWIsoft/tkleiner/lib/python2.7/site-packages/netCDF4-1.2.4-py2.7-linux-x86_64.egg/netCDF4/_netCDF4.py", line 7, in <module>
  File "/global/AWIsoft/tkleiner/lib/python2.7/site-packages/netCDF4-1.2.4-py2.7-linux-x86_64.egg/netCDF4/_netCDF4.py", line 6, in __bootstrap__
  File "/global/AWIsoft/miniconda/4.7.12/lib/python3.7/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: dynamic module does not define module export function (PyInit__netCDF4)
 0: v$$Eh  diffusivity (overrides end of the run) (dt=0.05230)
 0: S     2000.183:    2.91181    4.22152          1.81882      0.00000
```

`/work/ollie/lackerma/processor-partitioning/experiments/pism10/log/pism10_pism_compute_20000101-20001231.log`

There is output in `run_20000101-20001231/work/` but not in `outdata/pism/` and it's only for one time step.

**Comment by dbarbi** [comment]
That refers to gfw_creator... I have no idea. Do you have that installed?

**Comment by pgierz** [comment]
I’m afraid I’m stuck here too…. It is trying to use netcdf from Thomas Kleiner, Python 2.7, but the rest of the tools from Python 3.7?

Lars, do you need to do some sort of `module load` for PISM to work?

On Jul 9, 2021, at 11:48 AM, ackerlar ***@***.******@***.***>> wrote:



No, it was not installed... It starts now but runs only for one year and gives this error:

Traceback (most recent call last):
  File "/work/ollie/lackerma/processor-partitioning/.direnv/python-3.7.4/bin/esm_runscripts", line 11, in <module>
    load_entry_point('esm-runscripts', 'console_scripts', 'esm_runscripts')()
  File "/work/ollie/lackerma/processor-partitioning/software/github.com/esm-tools/esm_runscripts/esm_runscripts/cli.py<http://github.com/esm-tools/esm_runscripts/esm_runscripts/cli.py>", line 225, in main
    Setup = SimulationSetup(command_line_config)
  File "/work/ollie/lackerma/processor-partitioning/software/github.com/esm-tools/esm_runscripts/esm_runscripts/sim_objects.py<http://github.com/esm-tools/esm_runscripts/esm_runscripts/sim_objects.py>", line 32, in __init__
    self.config = prepare.run_job(self.config)
  File "/work/ollie/lackerma/processor-partitioning/software/github.com/esm-tools/esm_runscripts/esm_runscripts/prepare.py<http://github.com/esm-tools/esm_runscripts/esm_runscripts/prepare.py>", line 14, in run_job
    helpers.evaluate(config, "prepare", "prepare_recipe")
  File "/work/ollie/lackerma/processor-partitioning/software/github.com/esm-tools/esm_runscripts/esm_runscripts/helpers.py<http://github.com/esm-tools/esm_runscripts/esm_runscripts/helpers.py>", line 45, in evaluate
    plugins_bare, framework_recipe, need_to_parse_plugins
  File "/work/ollie/lackerma/processor-partitioning/software/github.com/esm-tools/esm_plugin_manager/esm_plugin_manager/esm_plugin_manager.py<http://github.com/esm-tools/esm_plugin_manager/esm_plugin_manager/esm_plugin_manager.py>", line 58, in read_plugin_information
    attach_installed_plugins_to_all(plugins)
  File "/work/ollie/lackerma/processor-partitioning/software/github.com/esm-tools/esm_plugin_manager/esm_plugin_manager/esm_plugin_manager.py<http://github.com/esm-tools/esm_plugin_manager/esm_plugin_manager/esm_plugin_manager.py>", line 73, in attach_installed_plugins_to_all
    plugins.update(find_installed_plugins())
  File "/work/ollie/lackerma/processor-partitioning/software/github.com/esm-tools/esm_plugin_manager/esm_plugin_manager/esm_plugin_manager.py<http://github.com/esm-tools/esm_plugin_manager/esm_plugin_manager/esm_plugin_manager.py>", line 67, in find_installed_plugins
    for entry_point in pkg_resources.iter_entry_points("esm_tools.plugins")
  File "/work/ollie/lackerma/processor-partitioning/software/github.com/esm-tools/esm_plugin_manager/esm_plugin_manager/esm_plugin_manager.py<http://github.com/esm-tools/esm_plugin_manager/esm_plugin_manager/esm_plugin_manager.py>", line 67, in <dictcomp>
    for entry_point in pkg_resources.iter_entry_points("esm_tools.plugins")
  File "/work/ollie/lackerma/processor-partitioning/.direnv/python-3.7.4/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/work/ollie/lackerma/processor-partitioning/.direnv/python-3.7.4/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/work/ollie/lackerma/processor-partitioning/.direnv/python-3.7.4/lib/python3.7/site-packages/gfw_creator/__init__.py", line 9, in <module>
    from .gfw_creator import *
  File "/work/ollie/lackerma/processor-partitioning/.direnv/python-3.7.4/lib/python3.7/site-packages/gfw_creator/gfw_creator.py", line 6, in <module>
    import xarray as xr
  File "/work/ollie/lackerma/processor-partitioning/.direnv/python-3.7.4/lib/python3.7/site-packages/xarray/__init__.py", line 3, in <module>
    from . import testing, tutorial, ufuncs
  File "/work/ollie/lackerma/processor-partitioning/.direnv/python-3.7.4/lib/python3.7/site-packages/xarray/tutorial.py", line 13, in <module>
    from .backends.api import open_dataset as _open_dataset
  File "/work/ollie/lackerma/processor-partitioning/.direnv/python-3.7.4/lib/python3.7/site-packages/xarray/backends/__init__.py", line 9, in <module>
    from .h5netcdf_ import H5NetCDFStore
  File "/work/ollie/lackerma/processor-partitioning/.direnv/python-3.7.4/lib/python3.7/site-packages/xarray/backends/h5netcdf_.py", line 25, in <module>
    from .netCDF4_ import (
  File "/work/ollie/lackerma/processor-partitioning/.direnv/python-3.7.4/lib/python3.7/site-packages/xarray/backends/netCDF4_.py", line 34, in <module>
    import netCDF4
  File "/global/AWIsoft/tkleiner/lib/python2.7/site-packages/netCDF4-1.2.4-py2.7-linux-x86_64.egg/netCDF4/__init__.py", line 3, in <module>
  File "/global/AWIsoft/tkleiner/lib/python2.7/site-packages/netCDF4-1.2.4-py2.7-linux-x86_64.egg/netCDF4/_netCDF4.py", line 7, in <module>
  File "/global/AWIsoft/tkleiner/lib/python2.7/site-packages/netCDF4-1.2.4-py2.7-linux-x86_64.egg/netCDF4/_netCDF4.py", line 6, in __bootstrap__
  File "/global/AWIsoft/miniconda/4.7.12/lib/python3.7/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: dynamic module does not define module export function (PyInit__netCDF4)
 0: v$$Eh  diffusivity (overrides end of the run) (dt=0.05230)
 0: S     2000.183:    2.91181    4.22152          1.81882      0.00000


/work/ollie/lackerma/processor-partitioning/experiments/pism10/log/pism10_pism_compute_20000101-20001231.log

There is output in run_20000101-20001231/work/ but not in outdata/pism/ and it's only for one time step.

**Comment by ackerlar** [comment]
@dbarbi Yes, gfw_creator is installed.
@pgierz Yes, it happens when `netCDF4` is imported but when I try to import it within my interactive python shell it is imported from here: `/work/ollie/lackerma/processor-partitioning/.direnv/python-3.7.4/lib/python3.7/site-packages/netCDF4/__init__.py`
I don't have any modules loaded.

**Comment by dbarbi** [comment]
module load pism_externals? that module was first built by tkleiner, and once by me, referring to thomas' folders...
yup, does say so in pism.compiletime_env_changes.yaml, "load pism_externals". That's where the tkleiner stuff comes from

**Comment by ackerlar** [comment]
As a fast workaround I removed the tkleiner paths from the python path in `evaluate` in `esm_runscripts/helpers.py`
https://github.com/esm-tools/esm_runscripts/commit/59918c6c6ceb671687cf783bde66d9dca0789213
