### ISSUE TITLE
Wrong config subfolder

### ISSUE THREAD

**Issue by JanStreffing** [esm-tools/esm_tools#4]
I ran into the following issue trying to install awicm-3.1:

```
esm_master comp-awicm-3.1
Traceback (most recent call last):
  File "/home/ollie/jstreffi/.local/lib/python3.6/site-packages/esm_parser/esm_parser.py", line 304, in attach_to_config_and_reduce_keyword
    tmp_config = yaml_file_to_dict(FUNCTION_PATH + "/" + model + "/" + item)
  File "/home/ollie/jstreffi/.local/lib/python3.6/site-packages/esm_parser/yaml_to_dict.py", line 37, in yaml_file_to_dict
    "All file extensions tried and none worked for %s" % filepath
FileNotFoundError: All file extensions tried and none worked for /home/ollie/jstreffi/esm_tools/configs/fesom2/fesom2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ollie/jstreffi/.local/bin/esm_master", line 8, in <module>
    sys.exit(main())
  File "/home/ollie/jstreffi/.local/lib/python3.6/site-packages/esm_master/cli.py", line 66, in main
    complete_setup = SimulationSetup(user_config = user_config)
  File "/home/ollie/jstreffi/.local/lib/python3.6/site-packages/esm_runscripts/esm_sim_objects.py", line 48, in __init__
    self.get_total_config_from_user_config(user_config)
  File "/home/ollie/jstreffi/.local/lib/python3.6/site-packages/esm_runscripts/esm_sim_objects.py", line 356, in get_total_config_from_user_config
    user_config)
  File "/home/ollie/jstreffi/.local/lib/python3.6/site-packages/esm_parser/esm_parser.py", line 1988, in __init__
    self._config_init(user_config)
  File "/home/ollie/jstreffi/.local/lib/python3.6/site-packages/esm_parser/esm_parser.py", line 2085, in _config_init
    setup_config["general"], model_config, "include_models", "models"
  File "/home/ollie/jstreffi/.local/lib/python3.6/site-packages/esm_parser/esm_parser.py", line 307, in attach_to_config_and_reduce_keyword
    tmp_config = yaml_file_to_dict(FUNCTION_PATH + "/" + model + "/" + model)
  File "/home/ollie/jstreffi/.local/lib/python3.6/site-packages/esm_parser/yaml_to_dict.py", line 37, in yaml_file_to_dict
    "All file extensions tried and none worked for %s" % filepath
FileNotFoundError: All file extensions tried and none worked for /home/ollie/jstreffi/esm_tools/configs/fesom2/fesom2
```

There is no `fesom2` folder. There is only a `fesom` folder containing the `fesom-2.0.yaml`. The immediate cause of the error is therefore evident. However I don't see where the folder is set. `setups2models.yaml` does not contain any reference to `fesom2`.

This issue was previously reported at https://gitlab.awi.de/esm_tools/esm_tools/issues/16#note_887

**Comment by JanStreffing** [comment]
@dbarbi @pgierz Do you know where the fesom2 entry is? I can't add notifications or assignees on github. I'm not sure if you are getting an email about this as you would on gitlab.

**Comment by pgierz** [comment]
We really need better error handling, see https://github.com/esm-tools/esm_parser/issues/1.

@JanStreffing, I'll have a look at this tomorrow. Maybe @dbarbi is faster than I am ;-). He also did some changes for how the version numbers are actually handled by the parser and I haven't look at that part of the code yet, so maybe he is the better person to ask.

**Comment by JanStreffing** [comment]
This error no longer exists on branch foci2. https://github.com/esm-tools/esm_tools/tree/foci2
