### ISSUE TITLE
fesom_mesh_part install not working

### ISSUE THREAD

**Issue by vkolatschek** [esm-tools/esm_tools#455]
**Problem**
I'm trying to create the partitioning files for a new mesh for fesom-1.4. To do that I tried to install fesom_mesh_part-1.4. The installation doesn't finish because of a mismatch of directory names.

**To Reproduce**
`esm_master install-fesom_mesh_part-1.4`

**Error message**
```
[100%] Built target fesom_ini
cp: cannot stat `fesom_mesh_part-1.4/mesh_part/build/fesom.x.ini': No such file or directory
Traceback (most recent call last):
  File "/pf/a/a270147/.local/bin/esm_master", line 11, in <module>
    load_entry_point('esm-master', 'console_scripts', 'esm_master')()
  File "/mnt/lustre01/pf/a/a270147/esm_tools_all/esm_master/esm_master/esm_master/cli.py", line 111, in main
    main_flow(parsed_args, target)
  File "/mnt/lustre01/pf/a/a270147/esm_tools_all/esm_master/esm_master/esm_master/esm_master.py", line 84, in main_flow
    user_task.execute(ignore_errors) #env)
  File "/mnt/lustre01/pf/a/a270147/esm_tools_all/esm_master/esm_master/esm_master/task.py", line 457, in execute
    subprocess.run(command.split(), check= not ignore_errors)
  File "/sw/rhel6-x64/conda/anaconda3-bleeding_edge/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['cp', 'fesom_mesh_part-1.4/mesh_part/build/fesom.x.ini', 'fesom_mesh_part-1.4/bin']' returned non-zero exit status 1.
```
Of course it can't find fesom_mesh_part-1.4/**mesh_part**/build/fesom.x.ini, because that directory doesn't exist. The directory is called fesom_mesh_partitioning. 

**Additional**
in the installation of fesom-1.4 there is a job_script fesom_part_init.job. Does it do the same thing as the fesom_mesh_part-1.4 would be doing when it's working? Or do I need to compile fesom differently for that?
And when the compilation / installation of fesom_mesh_part-1.4 works, do you have an example for a runscript for me? Which input does it need?

**System**
 - Supercomputer: mistral
 - Version 
```
 +---------------------+-----------+----------------------------------------------------------------------------------+------------+---------------------------+
| package_name        | version   | file                                                                             | branch     | tags                      |
|---------------------+-----------+----------------------------------------------------------------------------------+------------+---------------------------|
| esm_calendar        | 5.0.0     | /mnt/lustre01/pf/a/a270147/esm_tools_all/esm_calendar/esm_calendar               | release    | v5.0.0                    |
| esm_database        | 5.0.0     | /mnt/lustre01/pf/a/a270147/.local/lib/python3.6/site-packages                    |            |                           |
| esm_environment     | 5.1.0     | /mnt/lustre01/pf/a/a270147/esm_tools_all/esm_environment/esm_environment         | develop    | v5.1.0                    |
| esm_master          | 5.1.1     | /mnt/lustre01/pf/a/a270147/esm_tools_all/esm_master/esm_master                   | develop    | v5.1.1-1-g2996342         |
| esm_motd            | 5.0.2     | /mnt/lustre01/pf/a/a270147/esm_tools_all/esm_motd/esm_motd                       | release    | v5.0.2-1-g9904c96         |
| esm_parser          | 5.1.5     | /mnt/lustre01/pf/a/a270147/esm_tools_all/esm_parser/esm_parser                   | develop    | v5.1.5-5-ge1729f7         |
| esm_plugin_manager  | 5.0.1     | /mnt/lustre01/pf/a/a270147/esm_tools_all/esm_plugin_manager/esm_plugin_manager   | release    | v5.0.1-1-g42544c3         |
| esm_profile         | 5.0.0     | /mnt/lustre01/pf/a/a270147/.local/lib/python3.6/site-packages                    |            |                           |
| esm_rcfile          | 5.1.0     | /mnt/lustre01/pf/a/a270147/esm_tools_all/esm_rcfile/esm_rcfile                   | develop    | v5.1.0                    |
| esm_runscripts      | 5.0.17    | /mnt/lustre01/pf/a/a270147/esm_tools_all/esm_runscripts/esm_runscripts           | hist_fixed | v5.0.17-76-gcb36307       |
| esm_tools           | 5.0.17    | /mnt/lustre01/pf/a/a270147/esm_tools_all/esm_tools                               | hist_fixed | v5.0.17-61-g3c2720e-dirty |
| esm_version_checker | 5.1.4     | /mnt/lustre01/pf/a/a270147/esm_tools_all/esm_version_checker/esm_version_checker | release    | v5.1.4                    |
+---------------------+-----------+----------------------------------------------------------------------------------+------------+---------------------------+

```

**Comment by mandresm** [comment]
Hi @vkolatschek, I have made a fix and applied to `hist_fixed` branch in `esm_tools`. You should be able to don't face this problem anymore after pulling that branch.

Please, let me know if that worked.

**Comment by vkolatschek** [comment]
Yes, that look good. Thank you @mandresm !

**Comment by mandresm** [comment]
Great! Thanks for reporting. I'll close the issue now.
