### ISSUE TITLE
Better error handling of problems in the namelists

### ISSUE THREAD

**Issue by mandresm** [esm-tools/esm_tools#468]
**Is your feature request related to a problem? Please describe.**
When users submit a simulation with `namelist_changes` in the runscript that are missing either a section inside the namelist, or the name of the namelist they are trying to modify (but still specifying the variables), they get (the case for @sveta-loza who reported the problem) a criptic error:
```
Traceback (most recent call last):
  File "/home/hbksloza/.local/bin/esm_runscripts", line 10, in <module>
    sys.exit(main())
  File "/home/hbksloza/.local/lib/python3.7/site-packages/esm_runscripts/cli.py", line 225, in main
    Setup()
  File "/home/hbksloza/.local/lib/python3.7/site-packages/esm_runscripts/sim_objects.py", line 55, in __call__
    self.compute(*args, **kwargs)
  File "/home/hbksloza/.local/lib/python3.7/site-packages/esm_runscripts/sim_objects.py", line 89, in compute
    self.config = compute.run_job(self.config)
  File "/home/hbksloza/.local/lib/python3.7/site-packages/esm_runscripts/compute.py", line 36, in run_job
    config = evaluate(config, "compute", "compute_recipe")
  File "/home/hbksloza/.local/lib/python3.7/site-packages/esm_runscripts/helpers.py", line 101, in evaluate
    framework_recipe, framework_plugins, config
  File "/home/hbksloza/.local/lib/python3.7/site-packages/esm_plugin_manager/esm_plugin_manager.py", line 138, in work_through_recipe
    config = getattr(submodule, workitem)(config)
  File "/home/hbksloza/.local/lib/python3.7/site-packages/esm_runscripts/compute.py", line 176, in modify_namelists
    config[model] = Namelist.nmls_remove(config[model])
  File "/home/hbksloza/.local/lib/python3.7/site-packages/esm_runscripts/namelists.py", line 125, in nmls_remove
    for key in list(change_entries):
TypeError: 'int' object is not iterable
```

Error handling for incorrectly written `namelist_chages` is needed.

**Describe the solution you'd like**
Modify `namelist.py` in `esm_runscripts` so that it checks that the changes make sense (everything is in a dictionary with three levels: namelist, section, variable).

**Comment by nwieters** [comment]
This issue has been raised again and solved in issue #1001.
