### ISSUE TITLE
TypeError: '>=' not supported between instances of 'int' and 'NoneType' if job resubmitted with venv 

### ISSUE THREAD

**Issue by chrisdane** [esm-tools/esm_tools#473]
**Describe the bug**
When I continue a run that already has a `.venv_esmtools` dir, the following error occurs at the end of the `esm_runscripts runscript.yaml -e expid`-call:
```
Submitting jobscript to batch system...

Output written by slurm:
Submitted batch job 32675430
Exception ignored in: <function _ConnectionRecord.checkout.<locals>.<lambda> at 0x2ab7e861ed90>
Traceback (most recent call last):
  File "/work/ba1103/a270073/out/awicm-1.0-recom/awi-esm-1-1-lr_kh800/piControl/.venv_esmtools/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 437, in <lambda>
  File "/work/ba1103/a270073/out/awicm-1.0-recom/awi-esm-1-1-lr_kh800/piControl/.venv_esmtools/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 717, in _finalize_fairy
  File "/work/ba1103/a270073/out/awicm-1.0-recom/awi-esm-1-1-lr_kh800/piControl/.venv_esmtools/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 472, in checkin
  File "/work/ba1103/a270073/out/awicm-1.0-recom/awi-esm-1-1-lr_kh800/piControl/.venv_esmtools/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 316, in _return_conn
  File "/work/ba1103/a270073/out/awicm-1.0-recom/awi-esm-1-1-lr_kh800/piControl/.venv_esmtools/lib/python3.6/site-packages/sqlalchemy/pool/impl.py", line 253, in _do_return_conn
  File "/work/ba1103/a270073/out/awicm-1.0-recom/awi-esm-1-1-lr_kh800/piControl/.venv_esmtools/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 484, in close
  File "/work/ba1103/a270073/out/awicm-1.0-recom/awi-esm-1-1-lr_kh800/piControl/.venv_esmtools/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 594, in __close
  File "/work/ba1103/a270073/out/awicm-1.0-recom/awi-esm-1-1-lr_kh800/piControl/.venv_esmtools/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 241, in _close_connection
  File "/sw/rhel6-x64/conda/anaconda3-bleeding_edge/lib/python3.6/logging/__init__.py", line 1295, in debug
  File "/sw/rhel6-x64/conda/anaconda3-bleeding_edge/lib/python3.6/logging/__init__.py", line 1548, in isEnabledFor
TypeError: '>=' not supported between instances of 'int' and 'NoneType'
```

**To Reproduce**
Complete a run with venv. Continue the run.

**Expected behavior**
No error.

**System (please complete the following information):**
 - Supercomputer: mistral
 - Version [Please run `esm_versions check`]
<details>
<summary>Click to expand</summary>

```
+---------------------+-----------+---------------------------------------------------------------+----------------------------+---------------------+
| package_name        | version   | file                                                          | branch                     | tags                |
|---------------------+-----------+---------------------------------------------------------------+----------------------------+---------------------|
| esm_analysis        | 0.3.0     | /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages |                            |                     |
| esm_archiving       | 5.0.0     | /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages |                            |                     |
| esm_calendar        | 5.0.0     | /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages |                            |                     |
| esm_database        | 5.0.0     | /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages |                            |                     |
| esm_environment     | 5.1.3     | /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages |                            |                     |
| esm_master          | 5.1.6     | /mnt/lustre01/pf/a/a270073/esm/src/esm_master                 | develop                    | v5.1.6-10-g96c2b66  |
| esm_motd            | 5.0.2     | /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages |                            |                     |
| esm_parser          | 5.1.12    | /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages |                            |                     |
| esm_plugin_manager  | 5.0.1     | /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages |                            |                     |
| esm_profile         | 5.0.0     | /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages |                            |                     |
| esm_rcfile          | 5.1.0     | /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages |                            |                     |
| esm_runscripts      | 5.1.12    | /mnt/lustre01/pf/a/a270073/esm/src/esm_runscripts             | hist_fixed                 | v5.0.17-80-g51d71e6 |
| esm_tools           | 5.1.0     | /mnt/lustre01/pf/a/a270073/esm/esm_tools                      | hist_fixed_and_awicm_recom | v5.0.17-84-g85c207e |
| esm_version_checker | 5.1.5     | /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages |                            |                     |
+---------------------+-----------+---------------------------------------------------------------+----------------------------+---------------------+
```
</details>

**Additional context**

**Comment by denizural** [comment]
Hi @chrisdane, could you please try again with `use_database: false` under the `general` section.

**Comment by chrisdane** [comment]
same

**Comment by pgierz** [comment]
Please re-open if this is still relevant as the original issue is now 8 months old.
