### ISSUE TITLE
TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by chrisdane** [esm-tools/esm_tools#485]
**Describe the bug**
A resubmitted job suddenly throws this error:
```
========================================================================
::: Executing the step:  assemble    (step [12/22] of the job:  compute)
========================================================================
Renaming sources to targets for filetype log in model echam
Renaming sources to targets for filetype log in model fesom
Renaming sources to targets for filetype log in model oasis3mct
Renaming sources to targets for filetype outdata in model echam
Renaming sources to targets for filetype outdata in model fesom
Renaming sources to targets for filetype outdata in model recom
Renaming sources to targets for filetype outdata in model oasis3mct
Renaming sources to targets for filetype outdata in model jsbach
Renaming sources to targets for filetype restart_out in model echam
Renaming sources to targets for filetype restart_out in model fesom
Renaming sources to targets for filetype restart_out in model recom
Renaming sources to targets for filetype restart_out in model oasis3mct
Renaming sources to targets for filetype restart_out in model jsbach
Renaming sources to targets for filetype restart_out in model hdmodel
Renaming sources to targets for filetype ignore in model echam
Renaming sources to targets for filetype ignore in model fesom
Renaming sources to targets for filetype ignore in model jsbach
Complete sources
Traceback (most recent call last):
  File "/work/ba1103/a270073/out/awicm-1.0-recom/awi-esm-1-1-lr_kh800/historical2/.venv_esmtools/bin/esm_runscripts", line 8, in <module>
    sys.exit(main())
  File "/work/ba1103/a270073/out/awicm-1.0-recom/awi-esm-1-1-lr_kh800/historical2/.venv_esmtools/lib/python3.6/site-packages/esm_runscripts/cli.py", line 202, in main
    Setup()
  File "/work/ba1103/a270073/out/awicm-1.0-recom/awi-esm-1-1-lr_kh800/historical2/.venv_esmtools/lib/python3.6/site-packages/esm_runscripts/sim_objects.py", line 54, in __call__
    self.tidy(*args, **kwargs)
  File "/work/ba1103/a270073/out/awicm-1.0-recom/awi-esm-1-1-lr_kh800/historical2/.venv_esmtools/lib/python3.6/site-packages/esm_runscripts/sim_objects.py", line 248, in tidy
    self.config = tidy.run_job(self.config)
  File "/work/ba1103/a270073/out/awicm-1.0-recom/awi-esm-1-1-lr_kh800/historical2/.venv_esmtools/lib/python3.6/site-packages/esm_runscripts/tidy.py", line 29, in run_job
    helpers.evaluate(config, "tidy", "tidy_recipe")
  File "/work/ba1103/a270073/out/awicm-1.0-recom/awi-esm-1-1-lr_kh800/historical2/.venv_esmtools/lib/python3.6/site-packages/esm_runscripts/helpers.py", line 49, in evaluate
    framework_recipe, framework_plugins, config
  File "/work/ba1103/a270073/out/awicm-1.0-recom/awi-esm-1-1-lr_kh800/historical2/.venv_esmtools/lib/python3.6/site-packages/esm_plugin_manager/esm_plugin_manager.py", line 138, in work_through_recipe
    config = getattr(submodule, workitem)(config)
  File "/work/ba1103/a270073/out/awicm-1.0-recom/awi-esm-1-1-lr_kh800/historical2/.venv_esmtools/lib/python3.6/site-packages/esm_runscripts/tidy.py", line 577, in maybe_resubmit
    next_compute(kill_after_submit=False)
  File "/work/ba1103/a270073/out/awicm-1.0-recom/awi-esm-1-1-lr_kh800/historical2/.venv_esmtools/lib/python3.6/site-packages/esm_runscripts/sim_objects.py", line 50, in __call__
    self.compute(*args, **kwargs)
  File "/work/ba1103/a270073/out/awicm-1.0-recom/awi-esm-1-1-lr_kh800/historical2/.venv_esmtools/lib/python3.6/site-packages/esm_runscripts/sim_objects.py", line 84, in compute
    self.config = compute.run_job(self.config)
  File "/work/ba1103/a270073/out/awicm-1.0-recom/awi-esm-1-1-lr_kh800/historical2/.venv_esmtools/lib/python3.6/site-packages/esm_runscripts/compute.py", line 32, in run_job
    config = evaluate(config, "compute", "compute_recipe")
  File "/work/ba1103/a270073/out/awicm-1.0-recom/awi-esm-1-1-lr_kh800/historical2/.venv_esmtools/lib/python3.6/site-packages/esm_runscripts/helpers.py", line 49, in evaluate
    framework_recipe, framework_plugins, config
  File "/work/ba1103/a270073/out/awicm-1.0-recom/awi-esm-1-1-lr_kh800/historical2/.venv_esmtools/lib/python3.6/site-packages/esm_plugin_manager/esm_plugin_manager.py", line 138, in work_through_recipe
    config = getattr(submodule, workitem)(config)
  File "/work/ba1103/a270073/out/awicm-1.0-recom/awi-esm-1-1-lr_kh800/historical2/.venv_esmtools/lib/python3.6/site-packages/esm_runscripts/filelists.py", line 944, in assemble
    config = replace_year_placeholder(config)
  File "/work/ba1103/a270073/out/awicm-1.0-recom/awi-esm-1-1-lr_kh800/historical2/.venv_esmtools/lib/python3.6/site-packages/esm_runscripts/filelists.py", line 470, in replace_year_placeholder
    in config[model][filetype + "_sources"][new_category]
TypeError: argument of type 'NoneType' is not iterable
```
Everything was ok before, nothing changed.

**To Reproduce**
```
esm_runscripts /work/ba1103/a270073/out/awicm-1.0-recom/awi-esm-1-1-lr_kh800/historical2/scripts/awicm_recom_historical.run.yaml -e historical2
```
will immediately yield the error.

**Expected behavior**
No error.

**System (please complete the following information):**
 - Supercomputer: mistral
 - Version [Please run `esm_versions check`]
<details>
<summary>Click to expand</summary>

esm_analysis
├─ version: 0.3.0
├─ path: /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages
├─ branch: 
└─ tags: 

esm_archiving
├─ version: 5.0.0
├─ path: /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages
├─ branch: 
└─ tags: 

esm_calendar
├─ version: 5.0.0
├─ path: /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages
├─ branch: 
└─ tags: 

esm_database
├─ version: 5.0.0
├─ path: /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages
├─ branch: 
└─ tags: 

esm_environment
├─ version: 5.1.3
├─ path: /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages
├─ branch: 
└─ tags: 

esm_master
├─ version: 5.1.6
├─ path: /mnt/lustre01/pf/a/a270073/esm/src/esm_master
├─ branch: develop
└─ tags: v5.1.6-10-g96c2b66

esm_motd
├─ version: 5.0.2
├─ path: /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages
├─ branch: 
└─ tags: 

esm_parser
├─ version: 5.1.12
├─ path: /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages
├─ branch: 
└─ tags: 

esm_plugin_manager
├─ version: 5.0.1
├─ path: /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages
├─ branch: 
└─ tags: 

esm_profile
├─ version: 5.0.0
├─ path: /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages
├─ branch: 
└─ tags: 

esm_rcfile
├─ version: 5.1.0
├─ path: /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages
├─ branch: 
└─ tags: 

esm_runscripts
├─ version: 5.1.12
├─ path: /mnt/lustre01/pf/a/a270073/esm/src/esm_runscripts
├─ branch: hist_fixed
└─ tags: v5.0.17-80-g51d71e6

esm_tools
├─ version: 5.1.0
├─ path: /mnt/lustre01/pf/a/a270073/esm/esm_tools
├─ branch: hist_fixed_and_awicm_recom
└─ tags: v5.0.17-84-g85c207e

esm_version_checker
├─ version: 5.1.5
├─ path: /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages
├─ branch: 
└─ tags: 
</details>

**Comment by denizural** [comment]
I will have a look at this now.

**Comment by pgierz** [comment]
Expected behaviour: No error. I love it ❤️

**Comment by pgierz** [comment]
Ok I have some time to look now. Please confirm the following:

- [x] You are on a development branch, hist fixed
- [x] You are using a virtual environment and should be shielded from outside changes
- [x] the run works in one year, and suddenly stops in the next
- [x] The cleanup step is what is messing up
- [x] Your Esmtoolsrc file in the home folder does not contain any paths, just your user names. (This one is really important)

**Comment by chrisdane** [comment]
Point one is not precise. As given in my initial post, there are different non-release branches involved:
```
esm_master
├─ version: 5.1.6
├─ path: /mnt/lustre01/pf/a/a270073/esm/src/esm_master
├─ branch: develop
└─ tags: v5.1.6-10-g96c2b66

esm_runscripts
├─ version: 5.1.12
├─ path: /mnt/lustre01/pf/a/a270073/esm/src/esm_runscripts
├─ branch: hist_fixed
└─ tags: v5.0.17-80-g51d71e6

esm_tools
├─ version: 5.1.0
├─ path: /mnt/lustre01/pf/a/a270073/esm/esm_tools
├─ branch: hist_fixed_and_awicm_recom
└─ tags: v5.0.17-84-g85c207e
```

Point 4 is not clear to me. The runscript says 
```
========================================================================
::: Executing the step:  assemble    (step [12/22] of the job:  compute)
========================================================================
```
before the error. So no cleanup but next compute job submission?

**Comment by pgierz** [comment]
Well, cleanup and send next job are the same step, so that one is also a checkmark...

To clarify here, "step" is (on my side) a misleading term. Perhaps "phase" is better. Effectively you always have something like "Python part: build the next job" --> "Slurm part: run the model" --> "Python part: clean up and build the next job"

**Comment by pgierz** [comment]
OK, the version of esm_master is (for this problem) completely irrelevant. I am more confused as to what (if anything) changed in `esm_tools`. Something must have. That means, though, that the virtual environment isn't behaving properly, which would be bad news.

**Comment by JanStreffing** [comment]
I checked the run folder on mistral. It seems that @chrisdane was able to fix this error and continue a few weeks after the last comment here. Closing issue here. If you think the solution might be of interest for others, feel free to document it here.
