### ISSUE TITLE
Error treatment with invalid fortran namelist

### ISSUE THREAD

**Issue by JanStreffing** [esm-tools/esm_tools#487]
Another issue from the error handling wishlist: I accidentally provided an invalid fortran namelist, which esm_tools tries to parse.  At the moment ones gets the following error message:

```
Traceback (most recent call last):
  File "/home/ollie/jstreffi/.local/bin/esm_runscripts", line 30, in <module>
    sys.exit(load_entry_point('esm-runscripts', 'console_scripts', 'esm_runscripts')())
  File "/home/ollie/jstreffi/esm_runscripts/esm_runscripts/cli.py", line 225, in main
    Setup()
  File "/home/ollie/jstreffi/esm_runscripts/esm_runscripts/sim_objects.py", line 55, in __call__
    self.compute(*args, **kwargs)
  File "/home/ollie/jstreffi/esm_runscripts/esm_runscripts/sim_objects.py", line 89, in compute
    self.config = compute.run_job(self.config)
  File "/home/ollie/jstreffi/esm_runscripts/esm_runscripts/compute.py", line 36, in run_job
    config = evaluate(config, "compute", "compute_recipe")
  File "/home/ollie/jstreffi/esm_runscripts/esm_runscripts/helpers.py", line 101, in evaluate
    framework_recipe, framework_plugins, config
  File "/home/ollie/jstreffi/.local/lib/python3.7/site-packages/esm_plugin_manager/esm_plugin_manager.py", line 138, in work_through_recipe
    config = getattr(submodule, workitem)(config)
  File "/home/ollie/jstreffi/esm_runscripts/esm_runscripts/compute.py", line 175, in modify_namelists
    config[model] = Namelist.nmls_load(config[model])
  File "/home/ollie/jstreffi/esm_runscripts/esm_runscripts/namelists.py", line 76, in nmls_load
    os.path.join(mconfig["thisrun_config_dir"], nml)
  File "/global/AWIsoft/intel-python/2020.2.902/lib/python3.7/site-packages/f90nml-1.1.2-py3.7.egg/f90nml/__init__.py", line 31, in read
  File "/global/AWIsoft/intel-python/2020.2.902/lib/python3.7/site-packages/f90nml-1.1.2-py3.7.egg/f90nml/parser.py", line 264, in read
  File "/global/AWIsoft/intel-python/2020.2.902/lib/python3.7/site-packages/f90nml-1.1.2-py3.7.egg/f90nml/parser.py", line 358, in _readstream
  File "/global/AWIsoft/intel-python/2020.2.902/lib/python3.7/site-packages/f90nml-1.1.2-py3.7.egg/f90nml/parser.py", line 626, in _parse_variable
  File "/global/AWIsoft/intel-python/2020.2.902/lib/python3.7/site-packages/f90nml-1.1.2-py3.7.egg/f90nml/parser.py", line 759, in _update_tokens
StopIteration
The program exited via sys.exit(). Exit status: 
> /home/ollie/jstreffi/.local/bin/esm_runscripts(3)<module>()
-> import re
```

While it is fairly clear from the message that something went wrong with f90nml/parser, it's not clear that invalid namelist format was the problem, nor which namelist was affected. I would suggest an error message that notifies the user in which text file is not a valid fortran namelist.

**Comment by denizural** [comment]
Hi @JanStreffing,
could you please provide an excerpt from the buggy namelist so that we can replicate the issue. Maybe we can even point this out to `f90nml` developers

**Comment by JanStreffing** [comment]
Hey Deniz, sure thing! The namelist template was missing the final `/` in the last line:
```
&NAMAMIP
    RunLengthSec = 1
    TimeStepSec  = 1
    StartYear    = 1
    StartMonth   = 1
    StartDay     = 1
    FixYear      = 1
    FileListSST  = 1
    FileListSIC  = 1
    LDebug       = false
    LInterpolate = true
```

**Comment by pgierz** [comment]
Not sure if this pops up automatically, but in case not, please see: https://github.com/esm-tools/esm_tools/commit/202f2b592308143d4c00aa8ce228be450253e104. I am not particularly happy with `f90nml` giving `StopIteration`, but, now it should at least print something slightly less cryptic.

**Comment by mandresm** [comment]
[ESM-149]

[ESM-149]: https://esm-tools.atlassian.net/browse/ESM-149?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by JanStreffing** [comment]
We picked up on this at the esm_tools retreat. Working on more less verbose more useful error handling is still high on the priority list.
