### ISSUE TITLE
Using venv on glogin works, but displays confusing error message.

### ISSUE THREAD

**Issue by seb-wahl** [esm-tools/esm_tools#505]
**Describe the bug**
```bash
glogin8:~/esm/esm_tools/runscripts/foci $ esm_runscripts -e venv_foci foci-initial-piCtl-test_daily_restart_lowcpu.yaml
Building virtual env, please be patient (this takes about 3 minutes)...
...finished 0:05:32.355885, restarting your job in the virtual env
Copying standard yamls from:  /home/shkifmsw/esm/esm-experiments/venv_foci/.venv_esmtools/lib/python3.7/site-packages/esm_tools/configs/
Copying standard namelists from:  /home/shkifmsw/esm/esm-experiments/venv_foci/.venv_esmtools/lib/python3.7/site-packages/esm_tools/namelists/
/home/shkifmsw/esm/esm_tools/runscripts/foci/foci-initial-piCtl-test_daily_restart_lowcpu.yaml
First year, checking if we need to compile...

================================================================================
STARTING SIMULATION JOB!
Experiment ID = venv_foci
Setup = foci
This setup consists of:
- echam
- nemo
- xios
- oasis3mct
- jsbach
- hdmodel
Experiment is installed in:
       /home/shkifmsw/esm/esm-experiments//venv_foci
================================================================================

- NOTE: removing the variable: dt_resume from the namelist: namelist.echam
/home/shkifmsw/esm/esm-experiments/venv_foci/.venv_esmtools/lib/python3.7/site-packages/f90nml/parser.py:831: UserWarning: f90nml: warning: Value       is not assigned to any variable and has been removed.
  ''.format(v=next_value)
/home/shkifmsw/esm/esm-experiments/venv_foci/.venv_esmtools/lib/python3.7/site-packages/f90nml/parser.py:831: UserWarning: f90nml: warning: Value s is not assigned to any variable and has been removed.
  ''.format(v=next_value)
/home/shkifmsw/esm/esm-experiments/venv_foci/.venv_esmtools/lib/python3.7/site-packages/f90nml/parser.py:831: UserWarning: f90nml: warning: Value False is not assigned to any variable and has been removed.
  ''.format(v=next_value)
/home/shkifmsw/esm/esm-experiments/venv_foci/.venv_esmtools/lib/python3.7/site-packages/f90nml/parser.py:831: UserWarning: f90nml: warning: Value True is not assigned to any variable and has been removed.
  ''.format(v=next_value)
Submitting jobscript to batch system...

Output written by slurm:
Submitted batch job 3251812
Exception ignored in: <function _ConnectionRecord.checkout.<locals>.<lambda> at 0x2b7f936e72f0>
Traceback (most recent call last):
  File "/home/shkifmsw/esm/esm-experiments/venv_foci/.venv_esmtools/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 488, in <lambda>
  File "/home/shkifmsw/esm/esm-experiments/venv_foci/.venv_esmtools/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 774, in _finalize_fairy
  File "/home/shkifmsw/esm/esm-experiments/venv_foci/.venv_esmtools/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 523, in checkin
  File "/home/shkifmsw/esm/esm-experiments/venv_foci/.venv_esmtools/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 319, in _return_conn
  File "/home/shkifmsw/esm/esm-experiments/venv_foci/.venv_esmtools/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 253, in _do_return_conn
  File "/home/shkifmsw/esm/esm-experiments/venv_foci/.venv_esmtools/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 535, in close
  File "/home/shkifmsw/esm/esm-experiments/venv_foci/.venv_esmtools/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 650, in __close
  File "/home/shkifmsw/esm/esm-experiments/venv_foci/.venv_esmtools/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 244, in _close_connection
  File "/sw/tools/python/anaconda3/2019.03/skl/lib/python3.7/logging/__init__.py", line 1370, in debug
  File "/sw/tools/python/anaconda3/2019.03/skl/lib/python3.7/logging/__init__.py", line 1626, in isEnabledFor
```
**To Reproduce**
Run any model in a venv on glogin.

**Expected behavior**
Well... No error message even though everything seems to work ok

**System (please complete the following information):**
HLRN4 Göttingen (glogin)
```bash
glogin8:~/esm/esm-experiments/venv_foci/.venv_esmtools/lib/python3.7/site-packages $ esm_versions check
+---------------------+-----------+---------------------------------------------------+----------+--------+
| package_name        | version   | file                                              | branch   | tags   |
|---------------------+-----------+---------------------------------------------------+----------+--------|
| esm_calendar        | 5.0.0     | /home/shkifmsw/.local/lib/python3.7/site-packages |          |        |
| esm_database        | 5.0.0     | /home/shkifmsw/.local/lib/python3.7/site-packages |          |        |
| esm_environment     | 5.1.3     | /home/shkifmsw/.local/lib/python3.7/site-packages |          |        |
| esm_master          | 5.1.6     | /home/shkifmsw/.local/lib/python3.7/site-packages |          |        |
| esm_motd            | 5.0.2     | /home/shkifmsw/.local/lib/python3.7/site-packages |          |        |
| esm_parser          | 5.1.12    | /home/shkifmsw/.local/lib/python3.7/site-packages |          |        |
| esm_plugin_manager  | 5.0.1     | /home/shkifmsw/.local/lib/python3.7/site-packages |          |        |
| esm_profile         | 5.0.0     | /home/shkifmsw/.local/lib/python3.7/site-packages |          |        |
| esm_rcfile          | 5.1.0     | /home/shkifmsw/.local/lib/python3.7/site-packages |          |        |
| esm_runscripts      | 5.1.31    | /home/shkifmsw/.local/lib/python3.7/site-packages |          |        |
| esm_version_checker | 5.1.5     | /home/shkifmsw/.local/lib/python3.7/site-packages |          |        |
+---------------------+-----------+---------------------------------------------------+----------+--------+
```

**Additional context**

**Comment by denizural** [comment]
Hi Sebastian,
Do you have `use_database: false` in your finished config? In a recent commit, I made it `false` by default.

**Comment by seb-wahl** [comment]
yes

**Comment by seb-wahl** [comment]
In the run with the venv yes, in another test run from yesterday there is no entry `use_database: `

**Comment by pgierz** [comment]
This actually isn't linked to `venv`, I think, but rather how the database is being disconnected from. I unfortunately don't have access to glogin, so I can't look at your log files in detail. Do you know who I can get in contact with for that?

Also, just to note: I'm visiting my parents, so I'm 9 hours behind European time, and might respond at strange times.

**Comment by seb-wahl** [comment]
We can have a look at this once you are back.

**Comment by chrisdane** [comment]
similar but different behavior on mistral: #473

**Comment by pgierz** [comment]
Is this still relevant in the newest version? If yes, please re-open.
