### ISSUE TITLE
ESM parser seems not to fully support ECHAM6 mvstreamctl syntax

### ISSUE THREAD

**Issue by christian-stepanek** [esm-tools/esm_tools#509]
I have added a mvstreamctl definition that is legal and valid according to ECHAM6 namelist standards. Yet, with esm-tools the submission process is interrupted, it seems due to the fact that ECHAM6 legal syntax is in this case interpreted as invalid, or just not understood, by the parser.

**To Reproduce**
Add the following mvstream definition to a working namelist to trigger the above described error:
```
&mvstreamctl
    interval = 1, 'days', 'last', 0
    target = 'g3bdayminmax'
    source = 'g3b'
    variables = 'temp2:max>t2max=201'
/
```
My guess is that the ">"-character is the culprit.

**Expected behavior**
As "variable-redirection" via the ">" character works with standard ECHAM6 (see e.g. /pf/a/a270061/mpiesm-1.2.01p1_CMIP6/mpiesm-1.2.01p1/experiments/LIG_127k_CMIP6_output/scripts/LIG_127k_CMIP6_output.run, lines 1173ff and 1203ff), it should in my humble opinion also work if esm-tools are used as the infrastructure. Maybe this will lead to a feature request.

**Error log**
Here the esm-tools stdout, containing the relevant error messages:
```
a270188@mlogin108% esm_runscripts run_hist_working2.yaml -e run_hist_f_new_32_minmax -c
Copying standard yamls from:  /mnt/lustre02/work/ab0246/a270188/awiesm-2.1-wiso_copy_model_from_Fernanda_3/pico-fesom/software/github.com/esm-tools/esm_tools/configs/
Copying standard namelists from:  /mnt/lustre02/work/ab0246/a270188/awiesm-2.1-wiso_copy_model_from_Fernanda_3/pico-fesom/software/github.com/esm-tools/esm_tools/namelists/
/mnt/lustre02/work/ab0246/a270188/awiesm-2.1-wiso_copy_model_from_Fernanda_3/pico-fesom/run_configs/run_hist_working2.yaml
First year, checking if we need to compile...

================================================================================
STARTING SIMULATION JOB!
Experiment ID = run_hist_f_new_32_minmax
Setup = awiesm
This setup consists of:
- echam
- fesom
- oasis3mct
- jsbach
- hdmodel
Experiment is installed in:
       /work/ab0246/a270188/awiesm-2.1-wiso_copy_model_from_Fernanda_3/pico-fesom/experiments/run_hist_f_new_32_minmax
================================================================================

Traceback (most recent call last):
  File "/mnt/lustre02/work/ab0246/a270188/awiesm-2.1-wiso_copy_model_from_Fernanda_3/pico-fesom/.direnv/python-3.8.6/lib/python3.8/site-packages/f90nml/parser.py", line 281, in read
    return self._readstream(nml_file, nml_patch)
  File "/mnt/lustre02/work/ab0246/a270188/awiesm-2.1-wiso_copy_model_from_Fernanda_3/pico-fesom/.direnv/python-3.8.6/lib/python3.8/site-packages/f90nml/parser.py", line 314, in _readstream
    new_toks = tokenizer.parse(next(nml_file))
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/lustre02/work/ab0246/a270188/awiesm-2.1-wiso_copy_model_from_Fernanda_3/pico-fesom/.direnv/python-3.8.6/bin/esm_runscripts", line 33, in <module>
    sys.exit(load_entry_point('esm-runscripts', 'console_scripts', 'esm_runscripts')())
  File "/mnt/lustre02/work/ab0246/a270188/awiesm-2.1-wiso_copy_model_from_Fernanda_3/pico-fesom/software/github.com/esm-tools/esm_runscripts/esm_runscripts/cli.py", line 202, in main
    Setup()
  File "/mnt/lustre02/work/ab0246/a270188/awiesm-2.1-wiso_copy_model_from_Fernanda_3/pico-fesom/software/github.com/esm-tools/esm_runscripts/esm_runscripts/sim_objects.py", line 50, in __call__
    self.compute(*args, **kwargs)
  File "/mnt/lustre02/work/ab0246/a270188/awiesm-2.1-wiso_copy_model_from_Fernanda_3/pico-fesom/software/github.com/esm-tools/esm_runscripts/esm_runscripts/sim_objects.py", line 84, in compute
    self.config = compute.run_job(self.config)
  File "/mnt/lustre02/work/ab0246/a270188/awiesm-2.1-wiso_copy_model_from_Fernanda_3/pico-fesom/software/github.com/esm-tools/esm_runscripts/esm_runscripts/compute.py", line 32, in run_job
    config = evaluate(config, "compute", "compute_recipe")
  File "/mnt/lustre02/work/ab0246/a270188/awiesm-2.1-wiso_copy_model_from_Fernanda_3/pico-fesom/software/github.com/esm-tools/esm_runscripts/esm_runscripts/helpers.py", line 48, in evaluate
    config = esm_plugin_manager.work_through_recipe(
  File "/mnt/lustre02/work/ab0246/a270188/awiesm-2.1-wiso_copy_model_from_Fernanda_3/pico-fesom/.direnv/python-3.8.6/lib/python3.8/site-packages/esm_plugin_manager/esm_plugin_manager.py", line 138, in work_through_recipe
    config = getattr(submodule, workitem)(config)
  File "/mnt/lustre02/work/ab0246/a270188/awiesm-2.1-wiso_copy_model_from_Fernanda_3/pico-fesom/software/github.com/esm-tools/esm_runscripts/esm_runscripts/compute.py", line 162, in modify_namelists
    config[model] = Namelist.nmls_load(config[model])
  File "/mnt/lustre02/work/ab0246/a270188/awiesm-2.1-wiso_copy_model_from_Fernanda_3/pico-fesom/software/github.com/esm-tools/esm_runscripts/esm_runscripts/namelists.py", line 75, in nmls_load
    mconfig["namelists"][nml] = f90nml.read(
  File "/mnt/lustre02/work/ab0246/a270188/awiesm-2.1-wiso_copy_model_from_Fernanda_3/pico-fesom/.direnv/python-3.8.6/lib/python3.8/site-packages/f90nml/__init__.py", line 31, in read
    return parser.read(nml_path)
  File "/mnt/lustre02/work/ab0246/a270188/awiesm-2.1-wiso_copy_model_from_Fernanda_3/pico-fesom/.direnv/python-3.8.6/lib/python3.8/site-packages/f90nml/parser.py", line 283, in read
    raise ValueError('End-of-file reached before end of namelist.')
ValueError: End-of-file reached before end of namelist.
```

**System (please complete the following information):**
 - Supercomputer: mistral
 - Version
 ```
+---------------------+-----------+------------------------------------------------------------------------------------------------------------------------------------------+------------+---------------------------+
| package_name        | version   | file                                                                                                                                     | branch     | tags                      |
|---------------------+-----------+------------------------------------------------------------------------------------------------------------------------------------------+------------+---------------------------|
| esm_calendar        | 5.0.0     | /mnt/lustre02/work/ab0246/a270188/awiesm-2.1-wiso_copy_model_from_Fernanda_3/pico-fesom/.direnv/python-3.8.6/lib/python3.8/site-packages |            |                           |
| esm_database        | 5.0.0     | /mnt/lustre02/work/ab0246/a270188/awiesm-2.1-wiso_copy_model_from_Fernanda_3/pico-fesom/.direnv/python-3.8.6/lib/python3.8/site-packages |            |                           |
| esm_environment     | 5.1.3     | /mnt/lustre02/work/ab0246/a270188/awiesm-2.1-wiso_copy_model_from_Fernanda_3/pico-fesom/.direnv/python-3.8.6/lib/python3.8/site-packages |            |                           |
| esm_master          | 5.1.6     | /mnt/lustre02/work/ab0246/a270188/awiesm-2.1-wiso_copy_model_from_Fernanda_3/pico-fesom/.direnv/python-3.8.6/lib/python3.8/site-packages |            |                           |
| esm_motd            | 5.0.2     | /mnt/lustre02/work/ab0246/a270188/awiesm-2.1-wiso_copy_model_from_Fernanda_3/pico-fesom/.direnv/python-3.8.6/lib/python3.8/site-packages |            |                           |
| esm_parser          | 5.1.12    | /mnt/lustre02/work/ab0246/a270188/awiesm-2.1-wiso_copy_model_from_Fernanda_3/pico-fesom/.direnv/python-3.8.6/lib/python3.8/site-packages |            |                           |
| esm_plugin_manager  | 5.0.1     | /mnt/lustre02/work/ab0246/a270188/awiesm-2.1-wiso_copy_model_from_Fernanda_3/pico-fesom/.direnv/python-3.8.6/lib/python3.8/site-packages |            |                           |
| esm_profile         | 5.0.0     | /mnt/lustre02/work/ab0246/a270188/awiesm-2.1-wiso_copy_model_from_Fernanda_3/pico-fesom/.direnv/python-3.8.6/lib/python3.8/site-packages |            |                           |
| esm_rcfile          | 5.1.0     | /mnt/lustre02/work/ab0246/a270188/awiesm-2.1-wiso_copy_model_from_Fernanda_3/pico-fesom/.direnv/python-3.8.6/lib/python3.8/site-packages |            |                           |
| esm_runscripts      | 5.0.17    | /mnt/lustre02/work/ab0246/a270188/awiesm-2.1-wiso_copy_model_from_Fernanda_3/pico-fesom/software/github.com/esm-tools/esm_runscripts     | hist_fixed | v5.0.17-80-g51d71e6       |
| esm_tools           | 5.1.23    | /mnt/lustre02/work/ab0246/a270188/awiesm-2.1-wiso_copy_model_from_Fernanda_3/pico-fesom/software/github.com/esm-tools/esm_tools          | hist_fixed | v5.1.23-3-ga9517323-dirty |
| esm_version_checker | 5.1.5     | /mnt/lustre02/work/ab0246/a270188/awiesm-2.1-wiso_copy_model_from_Fernanda_3/pico-fesom/.direnv/python-3.8.6/lib/python3.8/site-packages |            |                           |
+---------------------+-----------+------------------------------------------------------------------------------------------------------------------------------------------+------------+---------------------------+ 
```

**Comment by denizural** [comment]
Hi @christian-stepanek, I am having a look at this now

**Comment by chrisdane** [comment]
Missing ' in
```
/work/ab0246/a270188/awiesm-2.1-wiso_copy_model_from_Fernanda_3/pico-fesom/experiments/run_hist_f_new_32_minmax/run_18500101-18501231/config/echam/namelist.echam
    variables = 'temp2:max>t2max=201', 'temp2:min>t2min=202
-->
    variables = 'temp2:max>t2max=201', 'temp2:min>t2min=202'
```

The ">"-notation works in the esmtools.

**Comment by denizural** [comment]
Hi @christian-stepanek, here is the vimdiff of the previous vs the fixed one. Is this what you are looking for:
![image](https://user-images.githubusercontent.com/51913535/144061520-8fac9514-c4af-4553-8c80-94e10f6a41b2.png)

**Comment by christian-stepanek** [comment]
@chrisdane @denizural So it seems that indeed the problem was a missing closing quote. My sincere apologies for that. I had checked the syntax several times, but overlooked that.

Is there any (easy) way to have the parser provide more easy-to-understand error messages that would point to such a mistake in the YAML-namelist syntax, like "check for missing quotes"? When I saw the long list of python errors, and had not in mind the possibility of a missing quote, I thought that the most obvious thing would be that esm-tools do not understand the ECHAM6 namelist syntax with respect to the ">" operator - which to my understanding is anyway quite a tweaked version of standard Fortran namelist functionality.

**Comment by mandresm** [comment]
Hi @christian-stepanek ,

I think it is possible, but I also think this is something for the cleanup phase after release 6 (indeed, there is a similar request from @JanStreffing already #487).

Noted in our Jira [ESM-149]

[ESM-149]: https://esm-tools.atlassian.net/browse/ESM-149?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by denizural** [comment]
Hi @christian-stepanek,
thanks for your feedback. Here is the changes I made to the runscript that generates the desired difference (the figure above):
```yaml
echam:
    ...
    add_namelist_changes:       # you already have this section
        ...
        mvstreamctl:            # this line and below should be added
            interval: "1, 'days', 'last', 0"
            target: 'g3bdayminmax'
            source: 'g3b'
            variables: 'temp2:max>t2max=201'
```

`add_namelist_changes` command adds the desired section into the namelist. In this case to the echam `namelist.echam`.
We don't recommend to directly change the namelist.echam by hand. Here is how `esm-tools` operate:
* loads the default namelists (eg. templates that you can see in `esm_tools/namelists/<MODEL-NAME>` directories.
* `esm_runscripts` modifies the related date & time information and input & forcing files in the namelist
* `esm_parser` checks for the namelist modification commands such as `add_namelist_changes`. Any additional section can be added by using this command.
* You can always check the generated namelist that will be used by `echam` when you run the `esm-runscripts` with the `--check` flag. The `work` directory will contain the `namelist.echam` that echam will read.

If you have any further questions please don't hesitate to ask. If there are some missing functionalities, we will take care of them like the namelist error messages.

**Comment by pgierz** [comment]
Closing, since it is from November last year. If needed, please re-open.
