### ISSUE TITLE
Installation of ESMs including PISM

### ISSUE THREAD

**Issue by pgierz** [esm-tools/esm_tools#53]
Hi all,

I'm getting errors when compiling AWI-ESM (ECHAM6/FESOM2/PISM). There are a few commands which must be executed for PISM only when building the model, specifically:

```yaml
                add_module_actions:
                    - "unload netcdf"
                    - "unload intel.compiler"
                    - "load pism_externals"
                add_export_vars:
                    - "I_MPI_FABRICS=shm:tmi"
```

Including them in the other models yields:

```
/work/ollie/pgierz/esm_tools_ollie_ci/awiesm-2.2/model_sources/awiesm-2.2/oasis/lib/psmile/src/mod_oasis_io.F90(10): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [NETCDF]
   USE netcdf
-------^
/work/ollie/pgierz/esm_tools_ollie_ci/awiesm-2.2/model_sources/awiesm-2.2/oasis/lib/psmile/src/mod_oasis_io.F90(101): error #6404: This name does not have a type, and must have an explicit type.   [NF90_NOWRITE]
         status = nf90_open(trim(filename),NF90_NOWRITE,ncid)
-------------------------------------------^
/work/ollie/pgierz/esm_tools_ollie_ci/awiesm-2.2/model_sources/awiesm-2.2/oasis/lib/psmile/src/mod_oasis_io.F90(101): error #6404: This name does not have a type, and must have an explicit type.   [NF90_OPEN]
         status = nf90_open(trim(filename),NF90_NOWRITE,ncid)
------------------^
/work/ollie/pgierz/esm_tools_ollie_ci/awiesm-2.2/model_sources/awiesm-2.2/oasis/lib/psmile/src/mod_oasis_io.F90(102): error #6404: This name does not have a type, and must have an explicit type.   [NF90_NOERR]
         IF (status /= nf90_noerr) WRITE(nulprt,*) subname,' model :',compid,' proc :',&
-----------------------^
/work/ollie/pgierz/esm_tools_ollie_ci/awiesm-2.2/model_sources/awiesm-2.2/oasis/lib/psmile/src/mod_oasis_io.F90(103): error #6404: This name does not have a type, and must have an explicit type.   [NF90_STRERROR]
                                                   mpi_rank_local,':',TRIM(nf90_strerror(status))
---------------------------------------------------------------------------^
/work/ollie/pgierz/esm_tools_ollie_ci/awiesm-2.2/model_sources/awiesm-2.2/oasis/lib/psmile/src/mod_oasis_io.F90(103): error #6362: The data types of the argument(s) are invalid.   [TRIM]
                                                   mpi_rank_local,':',TRIM(nf90_strerror(status))
---------------------------------------------------------------------------^
/work/ollie/pgierz/esm_tools_ollie_ci/awiesm-2.2/model_sources/awiesm-2.2/oasis/lib/psmile/src/mod_oasis_io.F90(111): error #6404: This name does not have a type, and must have an explicit type.   [NF90_INQ_VARID]
      status = nf90_inq_varid(ncid,trim(filefld),varid)
---------------^
/work/ollie/pgierz/esm_tools_ollie_ci/awiesm-2.2/model_sources/awiesm-2.2/oasis/lib/psmile/src/mod_oasis_io.F90(113): error #6362: The data types of the argument(s) are invalid.   [TRIM]
         write(nulprt,*) subname,':',trim(nf90_strerror(status))
------------------------------------------^
/work/ollie/pgierz/esm_tools_ollie_ci/awiesm-2.2/model_sources/awiesm-2.2/oasis/lib/psmile/src/mod_oasis_io.F90(119): error #6632: Keyword arguments are invalid without an explicit interface.   [NDIMS]
      status = nf90_inquire_variable(ncid,varid,ndims=dlen,dimids=dimid2)
------------------------------------------------^
/work/ollie/pgierz/esm_tools_ollie_ci/awiesm-2.2/model_sources/awiesm-2.2/oasis/lib/psmile/src/mod_oasis_io.F90(119): error #6632: Keyword arguments are invalid without an explicit interface.   [DIMIDS]
      status = nf90_inquire_variable(ncid,varid,ndims=dlen,dimids=dimid2)
-----------------------------------------------------------^
/work/ollie/pgierz/esm_tools_ollie_ci/awiesm-2.2/model_sources/awiesm-2.2/oasis/lib/psmile/src/mod_oasis_io.F90(119): error #6404: This name does not have a type, and must have an explicit type.   [NF90_INQUIRE_VARIABLE]
      status = nf90_inquire_variable(ncid,varid,ndims=dlen,dimids=dimid2)
---------------^
/work/ollie/pgierz/esm_tools_ollie_ci/awiesm-2.2/model_sources/awiesm-2.2/oasis/lib/psmile/src/mod_oasis_io.F90(121): error #6362: The data types of the argument(s) are invalid.   [TRIM]
                                                mpi_rank_local,':',TRIM(nf90_strerror(status))
------------------------------------------------------------------------^
/work/ollie/pgierz/esm_tools_ollie_ci/awiesm-2.2/model_sources/awiesm-2.2/oasis/lib/psmile/src/mod_oasis_io.F90(128): error #6632: Keyword arguments are invalid without an explicit interface.   [LEN]
      status = nf90_inquire_dimension(ncid,dimid2(1),len=nx)
-----------------------------------------------------^
/work/ollie/pgierz/esm_tools_ollie_ci/awiesm-2.2/model_sources/awiesm-2.2/oasis/lib/psmile/src/mod_oasis_io.F90(128): error #6404: This name does not have a type, and must have an explicit type.   [NF90_INQUIRE_DIMENSION]
      status = nf90_inquire_dimension(ncid,dimid2(1),len=nx)
---------------^
/work/ollie/pgierz/esm_tools_ollie_ci/awiesm-2.2/model_sources/awiesm-2.2/oasis/lib/psmile/src/mod_oasis_io.F90(130): error #6362: The data types of the argument(s) are invalid.   [TRIM]
                                                mpi_rank_local,':',TRIM(nf90_strerror(status))
------------------------------------------------------------------------^
/work/ollie/pgierz/esm_tools_ollie_ci/awiesm-2.2/model_sources/awiesm-2.2/oasis/lib/psmile/src/mod_oasis_io.F90(131): error #6632: Keyword arguments are invalid without an explicit interface.   [LEN]
      status = nf90_inquire_dimension(ncid,dimid2(2),len=ny)
-----------------------------------------------------^
/work/ollie/pgierz/esm_tools_ollie_ci/awiesm-2.2/model_sources/awiesm-2.2/oasis/lib/psmile/src/mod_oasis_io.F90(133): error #6362: The data types of the argument(s) are invalid.   [TRIM]
                                                mpi_rank_local,':',TRIM(nf90_strerror(status))
------------------------------------------------------------------------^
/work/ollie/pgierz/esm_tools_ollie_ci/awiesm-2.2/model_sources/awiesm-2.2/oasis/lib/psmile/src/mod_oasis_io.F90(144): error #6404: This name does not have a type, and must have an explicit type.   [NF90_GET_VAR]
         status = nf90_get_var(ncid,varid,array2i)
------------------^
/work/ollie/pgierz/esm_tools_ollie_ci/awiesm-2.2/model_sources/awiesm-2.2/oasis/lib/psmile/src/mod_oasis_io.F90(146): error #6362: The data types of the argument(s) are invalid.   [TRIM]
                                                   mpi_rank_local,':',TRIM(nf90_strerror(status))
---------------------------------------------------------------------------^
/work/ollie/pgierz/esm_tools_ollie_ci/awiesm-2.2/model_sources/awiesm-2.2/oasis/lib/psmile/src/mod_oasis_io.F90(161): error #6362: The data types of the argument(s) are invalid.   [TRIM]
                                                   mpi_rank_local,':',TRIM(nf90_strerror(status))
---------------------------------------------------------------------------^
/work/ollie/pgierz/esm_tools_ollie_ci/awiesm-2.2/model_sources/awiesm-2.2/oasis/lib/psmile/src/mod_oasis_io.F90(174): error #6404: This name does not have a type, and must have an explicit type.   [NF90_CLOSE]
      status = nf90_close(ncid)
---------------^
/work/ollie/pgierz/esm_tools_ollie_ci/awiesm-2.2/model_sources/awiesm-2.2/oasis/lib/psmile/src/mod_oasis_io.F90(177): error #6362: The data types of the argument(s) are invalid.   [TRIM]
                          TRIM(nf90_strerror(status))
-------------------------------^
/work/ollie/pgierz/esm_tools_ollie_ci/awiesm-2.2/model_sources/awiesm-2.2/oasis/lib/psmile/src/mod_oasis_io.F90(260): error #6404: This name does not have a type, and must have an explicit type.   [NF90_WRITE]
         status = nf90_open(trim(rstfile),NF90_WRITE,ncid)
------------------------------------------^
/work/ollie/pgierz/esm_tools_ollie_ci/awiesm-2.2/model_sources/awiesm-2.2/oasis/lib/psmile/src/mod_oasis_io.F90(260): error #6404: This name does not have a type, and must have an explicit type.   [NF90_OPEN]
         status = nf90_open(trim(rstfile),NF90_WRITE,ncid)
------------------^
/work/ollie/pgierz/esm_tools_ollie_ci/awiesm-2.2/model_sources/awiesm-2.2/oasis/lib/psmile/src/mod_oasis_io.F90(262): error #6404: This name does not have a type, and must have an explicit type.   [NF90_STRERROR]
                                                   mpi_rank_local,':',TRIM(nf90_strerror(status))
---------------------------------------------------------------------------^
/work/ollie/pgierz/esm_tools_ollie_ci/awiesm-2.2/model_sources/awiesm-2.2/oasis/lib/psmile/src/mod_oasis_io.F90(262): error #6362: The data types of the argument(s) are invalid.   [TRIM]
                                                   mpi_rank_local,':',TRIM(nf90_strerror(status))
---------------------------------------------------------------------------^
/work/ollie/pgierz/esm_tools_ollie_ci/awiesm-2.2/model_sources/awiesm-2.2/oasis/lib/psmile/src/mod_oasis_io.F90(263): error #6404: This name does not have a type, and must have an explicit type.   [NF90_REDEF]
         status = nf90_redef(ncid)
------------------^
/work/ollie/pgierz/esm_tools_ollie_ci/awiesm-2.2/model_sources/awiesm-2.2/oasis/lib/psmile/src/mod_oasis_io.F90(265): error #6404: This name does not have a type, and must have an explicit type.   [NF90_CLOBBER]
         status = nf90_create(trim(rstfile),NF90_CLOBBER,ncid)
--------------------------------------------^
/work/ollie/pgierz/esm_tools_ollie_ci/awiesm-2.2/model_sources/awiesm-2.2/oasis/lib/psmile/src/mod_oasis_io.F90(265): error #6404: This name does not have a type, and must have an explicit type.   [NF90_CREATE]
         status = nf90_create(trim(rstfile),NF90_CLOBBER,ncid)
------------------^
/work/ollie/pgierz/esm_tools_ollie_ci/awiesm-2.2/model_sources/awiesm-2.2/oasis/lib/psmile/src/mod_oasis_io.F90(267): error #6362: The data types of the argument(s) are invalid.   [TRIM]
                                                   mpi_rank_local,':',TRIM(nf90_strerror(status))
---------------------------------------------------------------------------^
/tmp/ifortFt5a9n.i90(1638): catastrophic error: Too many errors, exiting
compilation aborted for /work/ollie/pgierz/esm_tools_ollie_ci/awiesm-2.2/model_sources/awiesm-2.2/oasis/lib/psmile/src/mod_oasis_io.F90 (code 1)
make[3]: *** [lib/psmile/CMakeFiles/psmile.dir/src/mod_oasis_io.F90.o] Error 1
make[2]: *** [lib/psmile/CMakeFiles/psmile.dir/src/mod_oasis_io.F90.o.provides] Error 2
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [lib/psmile/CMakeFiles/psmile.dir/all] Error 2
make: *** [all] Error 2
Traceback (most recent call last):
  File "/home/ollie/pgierz/.local/bin/esm_master", line 11, in <module>
    load_entry_point('esm-master', 'console_scripts', 'esm_master')()
  File "/home/ollie/pgierz/dev/esm_tools/esm_master/esm_master/cli.py", line 124, in main
    user_task.execute(env)
  File "/home/ollie/pgierz/dev/esm_tools/esm_master/esm_master/esm_master.py", line 864, in execute
    shell=(command.startswith("./") and command.endswith(".sh")),
  File "/global/AWIsoft/intel/2020/intelpython3/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['./comp-oasis3-mct-2.8_script.sh']' returned non-zero exit status 2.
```

Removing the relevant PISM commands gives:
```
Module for cmake version 3.13.3 loaded
Module for udunits version 2.2.26 loaded
Module for grib_api version 1.28.0 loaded.
Module for Intel Compiler and Libraries, ifort, icc, icpc; mkl, ipp, tbb,... version 2018.5.274 loaded.
Module for hdf5 version 1.10.2_gnu loaded
Module for centoslibs version 7.5 loaded.
Module for cdo version 1.9.6 loaded
Please add >module load centoslibs<, if you are on a compute node to get all libraries.
Module for nco version 4.7.7 loaded
Please add >module load centoslibs<, if you are on a compute node to get all libraries.
Module for netcdf version 4.6.2_intel_18.0.5 loaded
Module for automake version 1.16.2 loaded
Currently Loaded Modulefiles:
 1) cmake/3.13.3   2) udunits/2.2.26   3) gribapi/1.28.0   4) intel.compiler/18.0.5(default)   5) hdf5/1.10.2_gnu   6) centoslibs/7.5(default)   7) cdo/1.9.6(default)   8) nco/4.7.7(default)   9) netcdf/4.6.2_intel  10) automake/1.16.2  
Module for impi,  version 2018.4.274 loaded.
-- The C compiler identification is Intel 18.0.5.20180823
-- The CXX compiler identification is Intel 18.0.5.20180823
-- Check for working C compiler: /global/AWIsoft/intel/2018/impi/2018.4.274/bin64/mpiicc
-- Check for working C compiler: /global/AWIsoft/intel/2018/impi/2018.4.274/bin64/mpiicc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /global/AWIsoft/intel/2018/impi/2018.4.274/bin64/mpiicpc
-- Check for working CXX compiler: /global/AWIsoft/intel/2018/impi/2018.4.274/bin64/mpiicpc -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring PISM version 'stable v1.2 committed by Constantine Khrulev on 2020-02-11 20:24:05 -0900'
-- Setting PISM install prefix to /work/ollie/pgierz/esm_tools_ollie_ci/awiesm-2.2/model_sources/awiesm-2.2/pism-github1.2.
CMake Error at /global/AWIsoft/cmake/3.13.3/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  PETSc could not be found.  Be sure to set PETSC_DIR and PETSC_ARCH.
  (missing: PETSC_INCLUDES PETSC_LIBRARIES)
Call Stack (most recent call first):
  /global/AWIsoft/cmake/3.13.3/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  CMake/FindPETSc.cmake:344 (find_package_handle_standard_args)
  CMake/PISM_CMake_macros.cmake:132 (find_package)
  CMakeLists.txt:125 (pism_find_prerequisites)


-- Configuring incomplete, errors occurred!
See also "/work/ollie/pgierz/esm_tools_ollie_ci/awiesm-2.2/model_sources/awiesm-2.2/pism-github1.2/build/CMakeFiles/CMakeOutput.log".
Traceback (most recent call last):
  File "/home/ollie/pgierz/.local/bin/esm_master", line 11, in <module>
    load_entry_point('esm-master', 'console_scripts', 'esm_master')()
  File "/home/ollie/pgierz/dev/esm_tools/esm_master/esm_master/cli.py", line 124, in main
    user_task.execute(env)
  File "/home/ollie/pgierz/dev/esm_tools/esm_master/esm_master/esm_master.py", line 864, in execute
    shell=(command.startswith("./") and command.endswith(".sh")),
  File "/global/AWIsoft/intel/2020/intelpython3/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['./comp-pism-github1.2_script.sh']' returned non-zero exit status 1.

```

This is fairly critical and should be solved quickly as at least 6 colleagues in my department rely on this model on a daily basis. A reliable way to build PISM along with other models would be ideal. Please fix this. Running PISM and the coupling programs would be nice, too...

**Comment by pgierz** [comment]
fixed in prep release
