### ISSUE TITLE
Virtual env on juwels 

### ISSUE THREAD

**Issue by JanStreffing** [esm-tools/esm_tools#652]
I would like to make a longer production run on juwels. I got the following error message:

```
? Which of the following packages do you want to install in 'editable mode'? End with <Enter> done
Building virtual env, please be patient (this takes about 3 minutes)...
...finished 0:04:16.006684, restarting your job in the virtual env
Traceback (most recent call last):
  File "/p/scratch/chhb19/streffing1/runtime/awicm3-frontiers-xios/pi_controll_3-1-TCO95_CORE2/.venv_esmtools/bin/esm_runscripts", line 8, in <module>
    sys.exit(main())
  File "/p/scratch/chhb19/streffing1/runtime/awicm3-frontiers-xios/pi_controll_3-1-TCO95_CORE2/.venv_esmtools/lib/python3.9/site-packages/esm_runscripts/cli.py", line 264, in main
    Setup = SimulationSetup(command_line_config)
  File "/p/scratch/chhb19/streffing1/runtime/awicm3-frontiers-xios/pi_controll_3-1-TCO95_CORE2/.venv_esmtools/lib/python3.9/site-packages/esm_runscripts/sim_objects.py", line 42, in __init__
    self.config = prepare.run_job(self.config)
  File "/p/scratch/chhb19/streffing1/runtime/awicm3-frontiers-xios/pi_controll_3-1-TCO95_CORE2/.venv_esmtools/lib/python3.9/site-packages/esm_runscripts/prepare.py", line 13, in run_job
    helpers.evaluate(config, "prepare", "prepare_recipe")
  File "/p/scratch/chhb19/streffing1/runtime/awicm3-frontiers-xios/pi_controll_3-1-TCO95_CORE2/.venv_esmtools/lib/python3.9/site-packages/esm_runscripts/helpers.py", line 50, in evaluate
    framework_recipe = esm_plugin_manager.read_recipe(
  File "/p/scratch/chhb19/streffing1/runtime/awicm3-frontiers-xios/pi_controll_3-1-TCO95_CORE2/.venv_esmtools/lib/python3.9/site-packages/esm_plugin_manager/esm_plugin_manager.py", line 10, in read_recipe
    recipe = yaml_file_to_dict(recipe)
  File "/p/scratch/chhb19/streffing1/runtime/awicm3-frontiers-xios/pi_controll_3-1-TCO95_CORE2/.venv_esmtools/lib/python3.9/site-packages/esm_parser/yaml_to_dict.py", line 217, in yaml_file_to_dict
    raise FileNotFoundError(
FileNotFoundError: All file extensions tried and none worked for /p/scratch/chhb19/streffing1/runtime/awicm3-frontiers-xios/pi_controll_3-1-TCO95_CORE2/.venv_esmtools/lib/python3.9/site-packages/esm_tools/configsesm_software/esm_runscripts/esm_runscripts.yaml
Traceback (most recent call last):
  File "/p/home/jusers/streffing1/juwels/.local/bin/esm_runscripts", line 33, in <module>
    sys.exit(load_entry_point('esm-tools', 'console_scripts', 'esm_runscripts')())
  File "/p/project/chhb19/jstreffi/esm_tools/src/esm_runscripts/cli.py", line 268, in main
    Setup()
  File "/p/project/chhb19/jstreffi/esm_tools/src/esm_runscripts/sim_objects.py", line 55, in __call__
    self.config = prepexp.run_job(self.config)
  File "/p/project/chhb19/jstreffi/esm_tools/src/esm_runscripts/prepexp.py", line 26, in run_job
    evaluate(config, "prepexp", "prepexp_recipe")
  File "/p/project/chhb19/jstreffi/esm_tools/src/esm_runscripts/helpers.py", line 61, in evaluate
    config = esm_plugin_manager.work_through_recipe(
  File "/p/project/chhb19/jstreffi/esm_tools/src/esm_plugin_manager/esm_plugin_manager.py", line 141, in work_through_recipe
    config = getattr(submodule, workitem)(config)
  File "/p/project/chhb19/jstreffi/esm_tools/src/esm_runscripts/virtual_env_builder.py", line 274, in venv_bootstrap
    _source_and_run_bin_in_venv(
  File "/p/project/chhb19/jstreffi/esm_tools/src/esm_runscripts/virtual_env_builder.py", line 69, in _source_and_run_bin_in_venv
    return subprocess.check_call(command, shell=shell)
  File "/p/software/juwels/stages/2022/software/Python/3.9.6-GCCcore-11.2.0/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'source /p/scratch/chhb19/streffing1/runtime/awicm3-frontiers-xios/pi_controll_3-1-TCO95_CORE2/.venv_esmtools/bin/activate &&  esm_runscripts pi_controll.yaml -e pi_controll_3-1-TCO95_CORE2 --contained-run' returned non-zero exit status 1.
```

**Comment by pgierz** [comment]
Some notes before I forget them:

> Which of the following packages do you want to install in 'editable mode'?

That no longer needs to be a question.

This file:
> ```
> /p/scratch/chhb19/streffing1/runtime/awicm3-frontiers-xios/pi_controll_3-1-TCO95_CORE2/.venv_esmtools/lib/python3.9/site-> packages/esm_tools/configsesm_software/esm_runscripts/esm_runscripts.yaml


exists, correct? If not, well, then the answer is obvious. If it does, something is deeply messed up with the venv and unless @mandresm want's to go on a deep bug hunt that is something I will need to look at.

**Comment by pgierz** [comment]
But, it's Monday and not Tuesday, so @mandresm good luck ;-) hand off to me tomorrow and I will make some time in the afternoon

**Comment by JanStreffing** [comment]
That path is not complete it seems to me:
`packages/esm_tools/configsesm_software/esm_runscripts/esm_runscripts.yaml`

`/p/scratch/chhb19/streffing1/runtime/awicm3-frontiers-xios/pi_controll_3-1-TCO95_CORE2/.venv_esmtools/lib/python3.9/site `
does not exist. But
`/p/scratch/chhb19/streffing1/runtime/awicm3-frontiers-xios/pi_controll_3-1-TCO95_CORE2/.venv_esmtools/lib/python3.9/site-packages `
does

**Comment by pgierz** [comment]
that may have been me messing up the copy/paste with the GitHub "quote previous answer" syntax, sorry

**Comment by denizural** [comment]
I think I found the error. Have a look at this:
`esm_tools/configsesm_software/esm_runscripts/esm_runscripts.yaml`
There should be a slash in between.

**Comment by denizural** [comment]
Ops sorry, Jan already mentioned that 🤦‍♂️

**Comment by denizural** [comment]
Ok, this might be a problem. It is trying to reach the `FUNCTION_PATH`. If you have an `.esmtoolsrc` file that contains a line like `/path/to/esm_tools/configs`. Note that the there is no trailing slash. One solution is simply deleting `FUNCTION_PATH` and the other paths. 
@JanStreffing, could you try that if this apply to you?

**Comment by mandresm** [comment]
OKay, I thought we agreed on not replicating work by assigning support days... And today was my day. We can invent as many systems as we want to be efficient. If we don't follow them we will keep failing.

**Comment by mandresm** [comment]
The `.esmtoolsrc` file was removed in the latest version of ESM-Tools. @JanStreffing , what version of ESM-Tools are you using?

**Comment by JanStreffing** [comment]
I guess its a bit older on juwels:
b9e40401b6a0eca66f2849764329bd771d2ab257 which comes from 2891235e2807160ad31ad2b06ea5841825948ecb

**Comment by mandresm** [comment]
Then, @denizural solution is the one to go for.

**Comment by JanStreffing** [comment]
`FUNCTION_PATH` seems to be in a lot of places. where shall I delete it?

alternatively, would an update from release branch do the trick?

**Comment by mandresm** [comment]
I'm having the same problem with the latest release, and I don't have a `.esmtoolsrc` file. I'll be calling you.

**Comment by pgierz** [comment]
The problem is here:
```
 /p/scratch/chhb19/streffing1/runtime/awicm3-frontiers-xios/pi_controll_3-1- 
  TCO95_CORE2/.venv_esmtools/lib/python3.9/site-                              
  packages/esm_tools/configsesm_software/esm_runscripts/esm_runscripts.yaml
```
There is a missing slash after `config`.

Has this by now been solved? Otherwise I will have a look where that might be
put together and ensure that trailing slashes are used.

Note that there are better ways of handling paths, but that is a topic for the
cleanup phase.

**Comment by mandresm** [comment]
Yeah, this was solved in #653 

> Note that there are better ways of handling paths, but that is a topic for the
> cleanup phase.

Agreed

**Comment by pgierz** [comment]
This should not be a problem in the current release (commit a10c230f) or using
version `6.7.3`. 

In lines 45-52 of `src/esm_runscripts/helpers.py`:
```python
    recipe = FUNCTION_PATH + "/esm_software/esm_runscripts/esm_runscripts.yaml"
    need_to_parse_recipe = True
    plugins_bare = FUNCTION_PATH + "/esm_software/esm_runscripts/esm_plugins.yaml"
    need_to_parse_plugins = True

    framework_recipe = esm_plugin_manager.read_recipe(
        recipe, {"job_type": job_type}, need_to_parse_recipe
    )
```

Slashes are ensured before both `recipe` and `plugins_bare`. That was fixed by @mandresm via commit 711c244f. 

I'm closing this issue; please re-open if the problem persists.

**Comment by pgierz** [comment]
Damnit, @mandresm was faster than I was on pushing the button ;-)

**Comment by mandresm** [comment]
Yeah, sorry, I wanted to save you the pain of checking, but I was not fast enough...
