### ISSUE TITLE
New AWI-CM3.1 setup: ValueError: not enough values to unpack (expected 2, got 1)

### ISSUE THREAD

**Issue by JanStreffing** [esm-tools/esm_tools#699]
**Describe the problem you are facing**
I'm trying to prepare the release of awicm-3.1. I created a new setup version number, a new coupling, and not component version numbers to this effect. When trying to install the new model version via esm_master I get:

```
************************************************************************************
Traceback (most recent call last):
  File "/p/home/jusers/streffing1/juwels/.local/bin/esm_master", line 33, in <module>
    sys.exit(load_entry_point('esm-tools', 'console_scripts', 'esm_master')())
  File "/p/project/chhb19/jstreffi/esm_tools/src/esm_master/cli.py", line 103, in main
    main_flow(parsed_args, target)
  File "/p/project/chhb19/jstreffi/esm_tools/src/esm_master/esm_master.py", line 55, in main_flow
    complete_setup = SimulationSetup(user_config=user_config)
  File "/p/project/chhb19/jstreffi/esm_tools/src/esm_runscripts/sim_objects.py", line 42, in __init__
    self.config = prepare.run_job(self.config)
  File "/p/project/chhb19/jstreffi/esm_tools/src/esm_runscripts/prepare.py", line 13, in run_job
    helpers.evaluate(config, "prepare", "prepare_recipe")
  File "/p/project/chhb19/jstreffi/esm_tools/src/esm_runscripts/helpers.py", line 60, in evaluate
    config = esm_plugin_manager.work_through_recipe(
  File "/p/project/chhb19/jstreffi/esm_tools/src/esm_plugin_manager/esm_plugin_manager.py", line 141, in work_through_recipe
    config = getattr(submodule, workitem)(config)
  File "/p/project/chhb19/jstreffi/esm_tools/src/esm_runscripts/prepare.py", line 717, in initialize_coupler
    config["general"]["coupler"].add_files(config)
  File "/p/project/chhb19/jstreffi/esm_tools/src/esm_runscripts/coupler.py", line 79, in add_files
    leftside, rest = coupling.split("%")
ValueError: not enough values to unpack (expected 2, got 1)
```

**To Reproduce**
checkout branch `awi-cm3.1_testruns` and try to run `esm_master install-awicm3-v3.1`

I cannot infer from the error message what the problem is. Most likely I will have made a typo, or left out some of the required information to make a new coupled model version in esm_tools. I have looked over these commits twice now, and I have trouble spotting the issue. Maybe one of you can have a look at this?

Cheers, Jan

**Comment by mandresm** [comment]
Hi @JanStreffing,

I think the problem is here: https://github.com/esm-tools/esm_tools/blob/0481af7e34c90189b1bf7bbc9942c6bdd38479f0/configs/setups/awicm3/awicm3.yaml#L423-L439

A `choose_block` is only catch in the first level of nesting (with the exception of `_environment_changes` and when it is nested inside another choose).

For this case I suggest the following:
```
        choose_general.version:
                'frontiers-xios':
                        add_process_ordering:
                                - xios
                'v3.1':
                        add_process_ordering:
                                - xios
                        add_coupling_target_fields:
                                add_rstos.nc:
                                        - 'A_CurX:A_CurY <--gauswgt_i-- u_feom:v_feom'

        coupling_target_fields:
                rstas.nc:
                        - 'heat_oce:heat_swo <--gauswgt_gss-- A_Qns_oce:A_Qs_all'
                        - 'prec_oce:snow_oce:evap_oce:subl_oce <--gauswgt_gss-- A_Precip_liquid:A_Precip_solid:A_Evap:A_Subl'
                        - 'heat_ico <--gauswgt_gss-- A_Q_ice'
                        - 'taux_oce:tauy_oce:taux_ico:tauy_ico <--bicubic-- A_TauX_oce:A_TauY_oce:A_TauX_ice:A_TauY_ice'
                        - 'R_Runoff_atm:R_Calving_atm <--gauswgt_gss-- A_Runoff:A_Calving'
                        - 'hydr_oce:enth_oce <--gauswgt_gss-- R_Runoff_oce:R_Calving_oce'
                rstos.nc:
                        - 'A_SST:A_Ice_frac:A_Snow_thickness:A_Ice_temp:A_Ice_albedo <--gauswgt_i-- sst_feom:sie_feom:snt_feom:ist_feom:sia_feom'
```

**Comment by JanStreffing** [comment]
That solved the problem, thank you!
