### ISSUE TITLE
git feature #690 broken

### ISSUE THREAD

**Issue by JanStreffing** [esm-tools/esm_tools#734]
It seems to me that the git version feature #690 is not quite working.
After merging release into my current test branch in oder to get the latest levante flags, I recompiled awicm3-v3.1 on levante and tried to run a basic runscript (`/runscripts/awicm3/v3.1/awicm3-v3.1-levante-TCO95L91-CORE2_initial.yaml`)

I get:

```
Traceback (most recent call last):
  File "/home/a/a270092/.local/bin/esm_runscripts", line 33, in <module>
    sys.exit(load_entry_point('esm-tools', 'console_scripts', 'esm_runscripts')())
  File "/home/a/a270092/esm_tools/src/esm_runscripts/cli.py", line 278, in main
    Setup()
  File "/home/a/a270092/esm_tools/src/esm_runscripts/sim_objects.py", line 69, in __call__
    self.prepcompute()
  File "/home/a/a270092/esm_tools/src/esm_runscripts/sim_objects.py", line 161, in prepcompute
    self.config = prepcompute.run_job(self.config)
  File "/home/a/a270092/esm_tools/src/esm_runscripts/prepcompute.py", line 36, in run_job
    config = evaluate(config, "prepcompute", "prepcompute_recipe")
  File "/home/a/a270092/esm_tools/src/esm_runscripts/helpers.py", line 61, in evaluate
    config = esm_plugin_manager.work_through_recipe(
  File "/home/a/a270092/esm_tools/src/esm_plugin_manager/esm_plugin_manager.py", line 141, in work_through_recipe
    config = getattr(submodule, workitem)(config)
  File "/home/a/a270092/esm_tools/src/esm_runscripts/prepare.py", line 702, in add_vcs_info
    vcs_versions[model] = helpers.get_all_git_info(model_dir)
  File "/home/a/a270092/esm_tools/src/esm_runscripts/helpers.py", line 422, in get_all_git_info
    "branch_name": get_git_branch(path),
  File "/home/a/a270092/esm_tools/src/esm_runscripts/helpers.py", line 375, in get_git_branch
    return repo.head.reference.name
  File "/home/a/a270092/.local/lib/python3.9/site-packages/git/refs/symbolic.py", line 294, in _get_reference
    raise TypeError("%s is a detached symbolic reference as it points to %r" % (self, sha))
TypeError: HEAD is a detached symbolic reference as it points to 'e48c9f09ff85aaf7ccb4e20d84e06887eb99d824'
```

Some of my git "branches" are tags. Maybe this is tripping up the system?

**Comment by mandresm** [comment]
Indeed, some tests in `esm_tests` CI were marked as `failed submission` instead of the less worrying `files differ`

**Comment by pgierz** [comment]
...apologies, I'm on it

**Comment by denizural** [comment]
@pgierz, I think you need to use `active_branch` for that.
See: https://gitpython.readthedocs.io/en/stable/changes.html?highlight=active_branch#repo

**Comment by mandresm** [comment]
@pgierz, if it takes longer to fix and you need more time, it's always possible to push a fix that comments the two steps in the recipe that trigger the error (easily revert the changes). Let me know if you'd like me to do that so that we buy you some time.

**Comment by pgierz** [comment]
Seeing as I am already in the train home, please patch it out for now. I'll uncomment it when I add the rest of the fix
