### ISSUE TITLE
Trouble with vcs_info.yaml

### ISSUE THREAD

**Issue by pgierz** [esm-tools/esm_tools#778]
### Discussed in https://github.com/esm-tools/esm_tools/discussions/774

<div type='discussions-op-text'>

<sup>Originally posted by **fernandadialzira** August  9, 2022</sup>
I am running a pi simulation on levante with a restart rate of 5 years and right after the first 5 years run, the simulation crashes with the following message 

```
===================================================================================================
::: Executing the step:  check_vcs_info_against_last_run    (step [17/19] of the job:  prepcompute)
===================================================================================================
Traceback (most recent call last):
  File "/home/a/a270179/.local/bin/esm_runscripts", line 33, in <module>
    sys.exit(load_entry_point('esm-tools', 'console_scripts', 'esm_runscripts')())
  File "/home/a/a270179/esm_tools/src/esm_runscripts/cli.py", line 278, in main
    Setup()
  File "/home/a/a270179/esm_tools/src/esm_runscripts/sim_objects.py", line 90, in __call__
    resubmit.maybe_resubmit(self.config)
  File "/home/a/a270179/esm_tools/src/esm_runscripts/resubmit.py", line 148, in maybe_resubmit
    nextrun = resubmit_recursively(config, jobtype=jobtype)
  File "/home/a/a270179/esm_tools/src/esm_runscripts/resubmit.py", line 189, in resubmit_recursively
    resubmit_SimulationSetup(config, cluster)
  File "/home/a/a270179/esm_tools/src/esm_runscripts/resubmit.py", line 66, in resubmit_SimulationSetup
    config["general"]["experiment_over"] = cluster_obj(kill_after_submit=False)
  File "/home/a/a270179/esm_tools/src/esm_runscripts/sim_objects.py", line 90, in __call__
    resubmit.maybe_resubmit(self.config)
  File "/home/a/a270179/esm_tools/src/esm_runscripts/resubmit.py", line 164, in maybe_resubmit
    nextrun = resubmit_recursively(
  File "/home/a/a270179/esm_tools/src/esm_runscripts/resubmit.py", line 189, in resubmit_recursively
    resubmit_SimulationSetup(config, cluster)
  File "/home/a/a270179/esm_tools/src/esm_runscripts/resubmit.py", line 66, in resubmit_SimulationSetup
    config["general"]["experiment_over"] = cluster_obj(kill_after_submit=False)
  File "/home/a/a270179/esm_tools/src/esm_runscripts/sim_objects.py", line 69, in __call__
    self.prepcompute()
  File "/home/a/a270179/esm_tools/src/esm_runscripts/sim_objects.py", line 161, in prepcompute
    self.config = prepcompute.run_job(self.config)
  File "/home/a/a270179/esm_tools/src/esm_runscripts/prepcompute.py", line 32, in run_job
    config = evaluate(config, "prepcompute", "prepcompute_recipe")
  File "/home/a/a270179/esm_tools/src/esm_runscripts/helpers.py", line 69, in evaluate
    config = esm_plugin_manager.work_through_recipe(
  File "/home/a/a270179/esm_tools/src/esm_plugin_manager/esm_plugin_manager.py", line 141, in work_through_recipe
    config = getattr(submodule, workitem)(config)
  File "/home/a/a270179/esm_tools/src/esm_runscripts/prepare.py", line 755, in check_vcs_info_against_last_run
    with open(last_exp_vcs_info_file, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/work/ab0246/a270179/runtime/awicm3-v3.1/experiments_production//pi_tco95_core2_003/run_18500101-18541231/log//pi_tco95_core2_003_vcs_info.yaml'

```

I believe it is related to the #732 update (@pgierz, @mandresm). I checked whether this file was at this path, and it actually is on the log folder of the experiment, but not to the specific run.

`The path to the experiment is /work/ab0246/a270179/runtime/awicm3-v3.1/experiments_production/pi_tco95_core2_003/`

</div>

**Comment by fernandadialzira** [comment]
By the way, I tried commenting out the part in the recipe as advised in #782, but the simulation does not start, with the verbose in the submission process indicating:

```
================================================================================
::: Executing the step:  add_vcs_info    (step [16/19] of the job:  prepcompute)
================================================================================
Traceback (most recent call last):
  File "/home/a/a270179/.local/bin/esm_runscripts", line 33, in <module>
    sys.exit(load_entry_point('esm-tools', 'console_scripts', 'esm_runscripts')())
  File "/home/a/a270179/esm_tools/src/esm_runscripts/cli.py", line 278, in main
    Setup()
  File "/home/a/a270179/esm_tools/src/esm_runscripts/sim_objects.py", line 69, in __call__
    self.prepcompute()
  File "/home/a/a270179/esm_tools/src/esm_runscripts/sim_objects.py", line 161, in prepcompute
    self.config = prepcompute.run_job(self.config)
  File "/home/a/a270179/esm_tools/src/esm_runscripts/prepcompute.py", line 32, in run_job
    config = evaluate(config, "prepcompute", "prepcompute_recipe")
  File "/home/a/a270179/esm_tools/src/esm_runscripts/helpers.py", line 69, in evaluate
    config = esm_plugin_manager.work_through_recipe(
  File "/home/a/a270179/esm_tools/src/esm_plugin_manager/esm_plugin_manager.py", line 138, in work_through_recipe
    if plugins[workitem]["type"] == "core":
KeyError: 'add_vcs_info'
```
the log file containing submission information is under `/work/ab0246/a270179/runtime/awicm3-v3.1/run_configs_production/log/submit_mh_tco95_core2_005`

**Comment by fernandadialzira** [comment]
Workaround so far for `awi-cm3.1`:

commenting out the lines for vcs info in 
`esm_tools/configs/esm_software/esm_runscripts/esm_runscripts.yaml`
`esm_tools/configs/esm_software/esm_runscripts/esm_plugins.yaml`
`esm_tools/configs/components/oifs/oifs.yaml`

**Comment by pgierz** [comment]
To speed up, Fernanda and I just did a video meeting. Two weird problems popped up that should be looked at while solving this bug:

Problem 1:
* Run Number 1 has the internal config variable `general.run_number: null`
* Run Number 2 has the internal config variable `general.run_number: 1`

Problem 2:
* Monthly restarts exit after March of year number 23 with a FESOM clock mistake (but why then not directly at year 4?). I suspect a leap-year bug, but this might have coincidently been exactly the same time as Levante was experiencing SLURM problems.

**Comment by fernandadialzira** [comment]
> 

Update on problem 2: the monthly restart test worked past the 23 years in march. I could have been then the SLURM problem.
Update on simulations after commenting out the vcs recipe in the three files abovementioned: they are running well so far (~100y already)

**Comment by fernandadialzira** [comment]
Update on different systems and models:

Same error when doing a simulation with `AWI-ESM2.1` on `Ollie`
