### ISSUE TITLE
InvalidGitRepositoryError 

### ISSUE THREAD

**Issue by JanStreffing** [esm-tools/esm_tools#815]
**Describe the bug**
On release version 6.13.10 when trying to start awicm3-v3.1 as a contained run 
`esm_runscripts awicm3-v3.1-levante-TCO95L91-CORE2.yaml -e compression-0 --contained-run`

ones gets the following error:
```
Run number for internal OpenIFS timekeeping: 1
Traceback (most recent call last):
  File "/work/ab0246/a270092/runtime/awicm3-v3.1/compression-0/.venv_esmtools/bin/esm_runscripts", line 8, in <module>
    sys.exit(main())
  File "/work/ab0246/a270092/runtime/awicm3-v3.1/compression-0/.venv_esmtools/lib/python3.9/site-packages/esm_runscripts/cli.py", line 278, in main
    Setup()
  File "/work/ab0246/a270092/runtime/awicm3-v3.1/compression-0/.venv_esmtools/lib/python3.9/site-packages/esm_runscripts/sim_objects.py", line 69, in __call__
    self.prepcompute()
  File "/work/ab0246/a270092/runtime/awicm3-v3.1/compression-0/.venv_esmtools/lib/python3.9/site-packages/esm_runscripts/sim_objects.py", line 161, in prepcompute
    self.config = prepcompute.run_job(self.config)
  File "/work/ab0246/a270092/runtime/awicm3-v3.1/compression-0/.venv_esmtools/lib/python3.9/site-packages/esm_runscripts/prepcompute.py", line 32, in run_job
    config = evaluate(config, "prepcompute", "prepcompute_recipe")
  File "/work/ab0246/a270092/runtime/awicm3-v3.1/compression-0/.venv_esmtools/lib/python3.9/site-packages/esm_runscripts/helpers.py", line 69, in evaluate
    config = esm_plugin_manager.work_through_recipe(
  File "/work/ab0246/a270092/runtime/awicm3-v3.1/compression-0/.venv_esmtools/lib/python3.9/site-packages/esm_plugin_manager/esm_plugin_manager.py", line 141, in work_through_recipe
    config = getattr(submodule, workitem)(config)
  File "/work/ab0246/a270092/runtime/awicm3-v3.1/compression-0/.venv_esmtools/lib/python3.9/site-packages/esm_runscripts/prepare.py", line 716, in add_vcs_info
    vcs_versions["esm_tools"] = helpers.get_all_git_info(f"{esm_tools_repo}/../")
  File "/work/ab0246/a270092/runtime/awicm3-v3.1/compression-0/.venv_esmtools/lib/python3.9/site-packages/esm_runscripts/helpers.py", line 440, in get_all_git_info
    "hash": get_git_hash(path),
  File "/work/ab0246/a270092/runtime/awicm3-v3.1/compression-0/.venv_esmtools/lib/python3.9/site-packages/esm_runscripts/helpers.py", line 365, in get_git_hash
    repo = git.Repo(path)
  File "/work/ab0246/a270092/runtime/awicm3-v3.1/compression-0/.venv_esmtools/lib/python3.9/site-packages/git/repo/base.py", line 224, in __init__
    self.working_dir: Optional[PathLike] = self._working_tree_dir or self.common_dir
  File "/work/ab0246/a270092/runtime/awicm3-v3.1/compression-0/.venv_esmtools/lib/python3.9/site-packages/git/repo/base.py", line 307, in common_dir
    raise InvalidGitRepositoryError()
git.exc.InvalidGitRepositoryError
```

`--open-run` works.

**Comment by pgierz** [comment]
Does this happen in the very first run, or are you closing the experiment after one or two iterations?

**Comment by JanStreffing** [comment]
First run.

**Comment by pgierz** [comment]
Ok, good to know. And one more question: this is still on the login node, right?

I guess it is still useful to get the git info at the time the closed run was started, but that might take some fiddling. I'll make a draft PR for that, but for now the workaround is to remove the vcs elements from your recipe.

**Comment by JanStreffing** [comment]
Yes I'm still on the login node here. vcs elements? Version Check Something? ;-)

**Comment by pgierz** [comment]
Version control system ;-) 

Have a look in your awicm3 recipe. One of the steps will be record vcs info or something like that. Comment that one out.

**Comment by JanStreffing** [comment]
close enough!
Thanks, I'll do that if I need it before a fix.

**Comment by JanStreffing** [comment]
Should I close this issue?

**Comment by pgierz** [comment]
Yes, less open issues are better. I think @mandresm and I both have in our heads what needs to get done

**Comment by mandresm** [comment]
I will also open soon a project for that, so I agree, we can close this.
