### ISSUE TITLE
new fort.4 template can't be modified with f90nml

### ISSUE THREAD

**Issue by JanStreffing** [esm-tools/esm_tools#843]
Apparently the new fort.4 template that I got from the EC-Earth community does not mesh well with f90nml. This namelist:
https://github.com/esm-tools/esm_tools/blob/feat/ece4-f/namelists/oifs/43r3/awicm3/master/fort.4
seemingly contains a grammatical error or oddity:

``` python
Traceback (most recent call last):
  File "/p/home/jusers/streffing1/juwels/.local/bin/esm_runscripts", line 33, in <module>
    sys.exit(load_entry_point('esm-tools', 'console_scripts', 'esm_runscripts')())
  File "/p/project/chhb19/jstreffi/esm_tools/src/esm_runscripts/cli.py", line 278, in main
    Setup()
  File "/p/project/chhb19/jstreffi/esm_tools/src/esm_runscripts/sim_objects.py", line 69, in __call__
    self.prepcompute()
  File "/p/project/chhb19/jstreffi/esm_tools/src/esm_runscripts/sim_objects.py", line 161, in prepcompute
    self.config = prepcompute.run_job(self.config)
  File "/p/project/chhb19/jstreffi/esm_tools/src/esm_runscripts/prepcompute.py", line 32, in run_job
    config = evaluate(config, "prepcompute", "prepcompute_recipe")
  File "/p/project/chhb19/jstreffi/esm_tools/src/esm_runscripts/helpers.py", line 69, in evaluate
    config = esm_plugin_manager.work_through_recipe(
  File "/p/project/chhb19/jstreffi/esm_tools/src/esm_plugin_manager/esm_plugin_manager.py", line 141, in work_through_recipe
    config = getattr(submodule, workitem)(config)
  File "/p/project/chhb19/jstreffi/esm_tools/src/esm_runscripts/prepcompute.py", line 187, in modify_namelists
    config[model] = Namelist.nmls_modify(config[model])
  File "/p/project/chhb19/jstreffi/esm_tools/src/esm_runscripts/namelists.py", line 225, in nmls_modify
    mconfig["namelists"][namelist].patch(changes)
  File "/p/home/jusers/streffing1/juwels/.local/lib/python3.9/site-packages/f90nml/namelist.py", line 499, in patch
    self[sec].update(nml_patch[sec])
AttributeError: 'list' object has no attribute 'update'
```
Compare to the old one:
https://github.com/esm-tools/esm_tools/blob/release/namelists/oifs/43r3/awicm3/master/fort.4

I don't really see the issue with the new one. Do you?

**Comment by JanStreffing** [comment]
upgrading the version of f90nml from 1.3.0 to 1.4.3 changed the error to:
``` python
Run number for internal OpenIFS timekeeping: 1
Traceback (most recent call last):
  File "/p/home/jusers/streffing1/juwels/.local/bin/esm_runscripts", line 33, in <module>
    sys.exit(load_entry_point('esm-tools', 'console_scripts', 'esm_runscripts')())
  File "/p/project/chhb19/jstreffi/esm_tools/src/esm_runscripts/cli.py", line 278, in main
    Setup()
  File "/p/project/chhb19/jstreffi/esm_tools/src/esm_runscripts/sim_objects.py", line 69, in __call__
    self.prepcompute()
  File "/p/project/chhb19/jstreffi/esm_tools/src/esm_runscripts/sim_objects.py", line 161, in prepcompute
    self.config = prepcompute.run_job(self.config)
  File "/p/project/chhb19/jstreffi/esm_tools/src/esm_runscripts/prepcompute.py", line 32, in run_job
    config = evaluate(config, "prepcompute", "prepcompute_recipe")
  File "/p/project/chhb19/jstreffi/esm_tools/src/esm_runscripts/helpers.py", line 69, in evaluate
    config = esm_plugin_manager.work_through_recipe(
  File "/p/project/chhb19/jstreffi/esm_tools/src/esm_plugin_manager/esm_plugin_manager.py", line 141, in work_through_recipe
    config = getattr(submodule, workitem)(config)
  File "/p/project/chhb19/jstreffi/esm_tools/src/esm_runscripts/prepcompute.py", line 187, in modify_namelists
    config[model] = Namelist.nmls_modify(config[model])
  File "/p/project/chhb19/jstreffi/esm_tools/src/esm_runscripts/namelists.py", line 225, in nmls_modify
    mconfig["namelists"][namelist].patch(changes)
  File "/p/home/jusers/streffing1/juwels/.local/lib/python3.9/site-packages/f90nml/namelist.py", line 658, in patch
    self[sec].update(nml_patch[sec])
AttributeError: 'Cogroup' object has no attribute 'update'
```

**Comment by mandresm** [comment]
The problem was that the sections `NAERAD`, `NAMPAR0`, `NAEPHY` , `NAMDYN`, `NAMGFL`, `NAMRES`, `NAMPPC` were repeated in the namelist (the repetitions being empty). I just removed them from the namelist and pushed the new namelist without repeated sections. The error is not intuitive at all. I will report an issue to `f90nml` so that the error is clearer (once they fix this we can catch and report from ESM-Tools which variables are repeated)

**Comment by pgierz** [comment]
Thanks Miguel! The guy who runs f90nml is super nice, so I hope this can go through. 

Jan, I'm about halfway done with your xml stuff, I might need you to give me a few more examples.

**Comment by mandresm** [comment]
Yeah, last time I opened an issue, he fixed super fast :)

**Comment by JanStreffing** [comment]
problem solved, ty!
