### ISSUE TITLE
Job chain failed du to "SSL: CERTIFICATE_VERIFY_FAILED"

### ISSUE THREAD

**Issue by crodehacke** [esm-tools/esm_tools#926]
**Describe the bug**
Failed continuation of a chain of **esm-jobs** on _levante_ (2023-03-24). It might have been a temporal problem because after several attempts to start the job it worked and the problem disappeared.

I consider this report for documentation purposes and do not expect an immediate solution.

**To Reproduce**
Run it and hope it occurs ;-^

**Expected behavior**
Smooth continuation of running jobs

**Screenshots**
I have start a jobs by calling `esm_runscripts awiesm_pism.yaml -e test006` and obtained the following output
```
Starting the iterative coupling business
Traceback (most recent call last):
  File "/sw/spack-levante/mambaforge-4.11.0-0-Linux-x86_64-sobz6z/lib/python3.9/urllib/request.py", line 1346, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/sw/spack-levante/mambaforge-4.11.0-0-Linux-x86_64-sobz6z/lib/python3.9/http/client.py", line 1285, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/sw/spack-levante/mambaforge-4.11.0-0-Linux-x86_64-sobz6z/lib/python3.9/http/client.py", line 1331, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/sw/spack-levante/mambaforge-4.11.0-0-Linux-x86_64-sobz6z/lib/python3.9/http/client.py", line 1280, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/sw/spack-levante/mambaforge-4.11.0-0-Linux-x86_64-sobz6z/lib/python3.9/http/client.py", line 1040, in _send_output
    self.send(msg)
  File "/sw/spack-levante/mambaforge-4.11.0-0-Linux-x86_64-sobz6z/lib/python3.9/http/client.py", line 980, in send
    self.connect()
  File "/sw/spack-levante/mambaforge-4.11.0-0-Linux-x86_64-sobz6z/lib/python3.9/http/client.py", line 1454, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/sw/spack-levante/mambaforge-4.11.0-0-Linux-x86_64-sobz6z/lib/python3.9/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/sw/spack-levante/mambaforge-4.11.0-0-Linux-x86_64-sobz6z/lib/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/sw/spack-levante/mambaforge-4.11.0-0-Linux-x86_64-sobz6z/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/a/a270096/.local/bin/esm_runscripts", line 33, in <module>
    sys.exit(load_entry_point('esm-tools', 'console_scripts', 'esm_runscripts')())
  File "/home/a/a270096/awi.src/esm_tools/src/esm_runscripts/cli.py", line 267, in main
    check_all_esm_packages()
  File "/home/a/a270096/awi.src/esm_tools/src/esm_motd/esm_motd.py", line 214, in check_all_esm_packages
    motd = MessageOfTheDayHandler()
  File "/home/a/a270096/awi.src/esm_tools/src/esm_motd/esm_motd.py", line 31, in __init__
    self.motdfile = urllib.request.urlopen(url)
  File "/sw/spack-levante/mambaforge-4.11.0-0-Linux-x86_64-sobz6z/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/sw/spack-levante/mambaforge-4.11.0-0-Linux-x86_64-sobz6z/lib/python3.9/urllib/request.py", line 517, in open
    response = self._open(req, data)
  File "/sw/spack-levante/mambaforge-4.11.0-0-Linux-x86_64-sobz6z/lib/python3.9/urllib/request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/sw/spack-levante/mambaforge-4.11.0-0-Linux-x86_64-sobz6z/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/sw/spack-levante/mambaforge-4.11.0-0-Linux-x86_64-sobz6z/lib/python3.9/urllib/request.py", line 1389, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/sw/spack-levante/mambaforge-4.11.0-0-Linux-x86_64-sobz6z/lib/python3.9/urllib/request.py", line 1349, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)>
```

**System (please complete the following information):**
 - Supercomputer: _levante_ (DKRZ, 2023-03-24)
 - Version: `esm_tools, version 6.8.0`

**Additional context**
After several attempts to restart the job chain manually, the error disappeared.

**Comment by mandresm** [comment]
I've just seen the same type of error when trying to run ESM-Tools on my laptop without connection to internet. The problem is that the Message Of The Day feature (that allows us to communicate important ESM-Tools news or fixes whenever you run `esm_master` or `esm_runscripts`) crashes if there is no connection to the GitHub repo. Probably, when you were trying to run your simulation GitHub was down or there was a problem on the connection in Levante.

I solved this in one of the branches I was working on:
https://github.com/esm-tools/esm_tools/commit/ff87efd1f4788ec20e25e0d5e82334811987e7a5#diff-aa3f1fa8f56ddfc9e9ab0acad12456dc98a1259c07e097b3720d00efe0389bfdL32-R32

I will make a fix right now for it, so that this silly thing does not give problems to anyone else.
